### ISSUE TITLE
About ios device 

### ISSUE THREAD

**Issue by chaoslife** [De-Panther/unity-webxr-export#100]
Hi, i have a question, will webxr will support ios safari future? I see it can run on mazilla xrviewer now

**Comment by De-Panther** [comment]
That's a question for Apple.
I did saw some tweets on twitter about Apple Safari team looking for AR/VR developers, but they might want to have their own API instead of WebXR...
I prefer to be optimistic and hope that they'll work on adding the WebXR API to Safari.
