### ISSUE TITLE
WebXR2020 and WebXR2020FullView appear to be broken

### ISSUE THREAD

**Issue by devhims** [De-Panther/unity-webxr-export#106]
Hi @De-Panther , I tested all the templates, and while webxr and webxrfullview templates worked well, the other 2 templates webxr2020 and webxr2020 didn't work as expected. 

Here are the deployments:
https://webxr-2020-template.netlify.app/
https://webxr-fullview2020-template.netlify.app/

**Comment by msub2** [comment]
Did you export the 2020 templates in a version of Unity 2020? Your page looks similar to how mine did when I exported for the wrong version.

**Comment by devhims** [comment]
Thanks @msub2! You're right. I'm not using Unity 2020.
