### ISSUE TITLE
IntelliSense not working in Visual Studio

### ISSUE THREAD

**Issue by devhims** [De-Panther/unity-webxr-export#109]
My VS code Intellisense for Unity works fine for all projects except when working with the scripts that come with this project. If I create my own scripts, it works fine. Anyone else experienced this? 

Ex. this is the `SceneHitTest.cs` file that comes with the project. 

<img width="1440" alt="Screenshot 2021-01-17 at 2 35 04 PM" src="https://user-images.githubusercontent.com/17825870/104836099-70465a00-58d1-11eb-86a3-e9d1929fd12b.png">

**Comment by devhims** [comment]
I think it's because these scripts are in the packages folder.

**Comment by De-Panther** [comment]
Update the VSCode Unity package in the package manager to 1.2.3

**Comment by devhims** [comment]
@De-Panther I'm using visual studio (not code) for Unity. :)

**Comment by De-Panther** [comment]
https://forum.unity.com/threads/intellisense-not-working-with-visual-studio-fix.836599/

**Comment by devhims** [comment]
I found this exact solution.
https://forum.unity.com/threads/visual-studio-no-intellisense-only-project-or-package.885388/
