### ISSUE TITLE
"No active WebXR.WebXRSubsystem is available" Error - Can't See Anything in Oculus Quest via Link (Running in Editor)

### ISSUE THREAD

**Issue by jsfgreen** [De-Panther/unity-webxr-export#119]
I recently followed your [Getting Started](https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md) guide.  I've set up my project in Unity 2019.4.18f1 under the WebGL platform; but I can't see anything in the HMD.

I also get the following error:

```
No active WebXR.WebXRSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.Debug:LogWarningFormat(String, Object[])
WebXR.SubsystemLifecycleManager`2:GetActiveSubsystemInstance() (at Library/PackageCache/com.de-panther.webxr@803e390e10/Runtime/XRPlugin/XRSystemLifecycleManager.cs:57)
WebXR.SubsystemLifecycleManager`2:EnsureSubsystem() (at Library/PackageCache/com.de-panther.webxr@803e390e10/Runtime/XRPlugin/XRSystemLifecycleManager.cs:37)
WebXR.SubsystemLifecycleManager`2:Awake() (at Library/PackageCache/com.de-panther.webxr@803e390e10/Runtime/XRPlugin/XRSystemLifecycleManager.cs:26)
WebXR.WebXRManager:Awake() (at Library/PackageCache/com.de-panther.webxr@803e390e10/Runtime/Scripts/WebXRManager.cs:64)
```

I am not sure what that's all about or how to fix it.

**Comment by De-Panther** [comment]
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md
Did you opened the `XR Plug-in Management` tab in the `Project Settings` window and select the `WebXR Export` plug-in provider?

**Comment by jsfgreen** [comment]
Yes I definitely did that. 

![xr-plugin-mgmt](https://user-images.githubusercontent.com/2606025/106075209-cfc31780-60d2-11eb-8554-1cd6f0c749e3.png)

**Comment by De-Panther** [comment]
Are you trying to run it in the editor or in the web?
To run it in the editor, you need to select an XR Plugin for desktop (like the Oculus, WMR, SteamVR, OpenXR, etc...)

**Comment by jsfgreen** [comment]
In the editor, in all the videos/examples I saw I swore they left it in the WebGL platform and ran it.  So I need to switch platforms to PC, for example, with Oculus selected?

**Comment by De-Panther** [comment]
No need to switch to desktop, just add supported XR Plugin for desktop

**Comment by De-Panther** [comment]
You can clone this repo : https://github.com/De-Panther/WebXR-Unity-Samples
There's a VR sample there, you can check the settings there :)

**Comment by jsfgreen** [comment]
I am currently downloading the matching unity version for this project (2019.4.13f1).  Thanks for the tips!  I'm not sure what "add supported XR plugin for desktop" entails.  Unity won't let me add any other XR plugin to the WebGL platform..  

EDIT 1:

![Screenshot 2021-01-28 065218](https://user-images.githubusercontent.com/2606025/106141322-8821a780-6135-11eb-9f88-0cad31225236.png)

![Screenshot 2021-01-28 065425](https://user-images.githubusercontent.com/2606025/106141459-bb643680-6135-11eb-912e-9ac09b4c4ec1.png)

EDIT 2:

By the way, _thank you very much_ for the sample project; it definitely still helps in other ways like it gave me ideas on how to handle the input module stuff and event system.  So once I figure out how to test in my headset in the editor and build I'll be good to go! :)

**Comment by jsfgreen** [comment]
Based on the above issue there is clearly something that I'm missing or misunderstanding - I'm guessing it'll be something "simple" or "small" but since I am totally new to WebXR/WebGL I really have no clue.  There must be some seemingly obvious step that I forgot or missed that is probably obvious to experienced devs but not so obvious to novices like myself.  Any ideas?

**Comment by De-Panther** [comment]
You need to set WebXR Export in the WebGL platform
![image](https://user-images.githubusercontent.com/4749703/106171999-eb91f080-619a-11eb-9cab-43b0de9cce25.png)
Oculus or another (depends on your device) in the Desktop platform
![image](https://user-images.githubusercontent.com/4749703/106172013-f056a480-619a-11eb-865d-c4bca2d6d4d0.png)
And use the WebGL platform in the editor
![image](https://user-images.githubusercontent.com/4749703/106172052-fc426680-619a-11eb-8672-32fe4a259481.png)

**Comment by De-Panther** [comment]
Looking at the screenshots you captured from the Sample Project, it seems that it tried to run the Oculus XR Plugin.
Was the headset connected to your computer at the time? If it was connected you shouldn't get those errors
![image](https://user-images.githubusercontent.com/4749703/106264782-ca7adf80-622e-11eb-9079-ca6cf3c905e6.png)

**Comment by jsfgreen** [comment]
Thanks again. Ironically I have that, the only difference I see in my XR config compared to yours is I have android, should I get rid of android?

**Comment by jsfgreen** [comment]
@De-Panther I just found this a moment ago: https://forum.unity.com/threads/unable-to-start-oculus-xr-plugin.913883/

If you scroll down to Ayday96's response he states:

> I found a solution that worked for me. SInce I had the oculus loader selected in both the Windows and the Android platform (under XR Management in the project settings) it must only allow one to be selected at a time.
> 
> https://stackoverflow.com/questions...s-xr-plugin-error-when-starting-game-in-unity
> 
> 
> "In XR plugin Management (Edit > Project Settings > XR Plugin Management) remove the Oculus Loader from the Plugin Providers in the Windows (PC, Mac & Linux Standalone settings) Tab. List should be empty. That fixed it for me."

So I unchecked **Initialize XR on Startup** for both PC and Android then checked it again for PC and now it works!!

**Comment by De-Panther** [comment]
Thanks!
So next time someone ask, should tell them to uncheck `Initialize XR on Startup` for Android?

**Comment by jsfgreen** [comment]
Actually, thank _you_ for all the help!  And yes, and perhaps potentially add this to your docs. :)

**Comment by De-Panther** [comment]
Thanks!
I should create a FAQ page

**Comment by egrigori** [comment]
Hi!

Can this warning message: "No active WebXR.WebXRSubsystem is available" can be the reason for the AR/VR buttons not work in itch.io?

**Comment by De-Panther** [comment]
If the warning is in the editor, no.
If you get this warning in the browser console, maybe. make sure to set the XR Plugin where needed

**Comment by egrigori** [comment]
I'm using itch.io to check the build. Is that a good idea?

**Comment by De-Panther** [comment]
I suggest to first test it on a local server, uploading to itch might have other issues
