### ISSUE TITLE
Samples no longer work

### ISSUE THREAD

**Issue by marioslokas** [De-Panther/unity-webxr-export#120]
Hi,

I tried out the Desert scene sample appr. 2 weeks ago and it was all fine. I could run the AR and VR session on my Android phone on Chrome without any issues, it was working pretty well.
Tried the same thing now and the page mysteriously freezes when I press on either AR or VR buttons in a build. Pressing on AR stretches the view in a weird way and just stays there. Pressing on VR displays two views and does nothing.
I tried to uncheck "Initialize XR on Startup" as suggested from another issue just in case, did not help.
I am running the build through an HTTPS server.

Is it possible that Chrome got updated in the meantime and the samples are no longer compatible? Or is this a known issue that just appeared?

**Comment by De-Panther** [comment]
Did you update the plugin since the last time it worked?
Did you update the WebGLTemplates after that?

**Comment by marioslokas** [comment]
> 
> 
> Did you update the plugin since the last time it worked?
> Did you update the WebGLTemplates after that?

Yes and yes. I made a new project from scratch, pulled both required packages and copied the webgl templates as shown in the readme. Same thing happened.

**Comment by De-Panther** [comment]
Which Unity version?
I'll also test it, although it works for me... (Tested on Unity 2019.4.7f1 2019.4.16f1 and 2020.2.2f1)

Also "Initialize XR on Startup" on WebGL should be checked, not unchecked.
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md

Can you upload a web page to test?

Thanks

**Comment by De-Panther** [comment]
Closing for now. If the issue continue please comment and I'll re-open
