### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by romzih9** [De-Panther/unity-webxr-export#124]
hello,
so ive tried building and run the sample scene from git and run it on chrome , but the proggress bar stuck at 90% in browser .
ive using the webxr2020 and webxr2020fullview, while using the webxr and webxrfullview simply didnt show anything in browser 

im using unity 2020.1.17f1 

is there anything i missed in the instalation or something just not compatible
thanks!

**Comment by De-Panther** [comment]
I guess it's related to your server settings. Did you use compression (gzip/brotli)? Does your server support those compression for the Unity output files (`.unityweb` `.wasm`)?
Try to build with no compression
![image](https://user-images.githubusercontent.com/4749703/107629779-45022100-6c6b-11eb-9e4f-cbfeb00cb5ba.png)

**Comment by romzih9** [comment]
hi, 
thanks for the fast reply!

i dont know much about server settings, im using local server with xampp/apache.
btw your solution works!  
thanks !

**Comment by De-Panther** [comment]
Glad it worked.

It's Unity WebGL issue, and not WebXR.
It's a common issue you can read about in the Unity WebGL Forum.
https://forum.unity.com/forums/webgl.84/
https://forum.unity.com/threads/poll-which-web-server-would-you-like-to-see-more-hosting-documentation-about.983609/
