### ISSUE TITLE
Screen clicks do not work in AR mode on iOS WebXR Viewer (works on Chrome on Android)

### ISSUE THREAD

**Issue by octopus8** [De-Panther/unity-webxr-export#126]
When using the demo scene in AR mode on Chrome on an Android device, the cubes on the table can be dragged just like in the normal mode. On the WebXR Viewer on my iPhone 8, this does not work.

Doing some debugging, I see I am getting bad values returned from `Input.mousePosition`. The X value is correct, but the Y value is wrong. The following are some values I got from `Input.mousePosition` when tapping the screen (note: bottom clicks are off a bit in Y due to a UI element at the bottom of the view).

![image](https://user-images.githubusercontent.com/4854583/108902357-161b7180-75c0-11eb-9ae0-09c0f779cb8c.png)

I'm not really sure this is a WebXR plugin bug, but maybe I'm wrong. Either way, I thought it was important to point out to the community, and see if anyone has any suggestions on how to fix/handle this.

**Comment by De-Panther** [comment]
Thanks. this is a known issue, but I don't have an iOS device to debug it. Would be happy to get some help.

Can you join the WebXR discord and we'll talk there?
https://discord.gg/Jt5tfaM

**Comment by De-Panther** [comment]
There were some changes related changes in this package that should have fix this issue. Got a message that it works now, so I'm closing the issue

**Comment by rashedabuodeh** [comment]
I am facing the same problem now, in unity 6
