### ISSUE TITLE
How load new scene?

### ISSUE THREAD

**Issue by ilariadinardo3** [De-Panther/unity-webxr-export#130]
When i try to load new scene with the headset, don't work. I can't "look around".

**Comment by De-Panther** [comment]
It should work.
With no info, it's hard to know what went wrong...

Make sure that there's only one instance of the WebXRCameraSet. Once it was loaded, it set itself as `DontDestroyOnLoad`, so if you have WebXRCameraSet in more than one scene, that might be the issue.

**Comment by ilariadinardo3** [comment]
I have the same problem of #40 
I don't understand how to solve  😭

**Comment by De-Panther** [comment]
On the last GGJ we made a game that had more than one scene.
It wasn't finished and has lots of quick hacks. But maybe it'll help you to realize how to handle multiple scenes with the `WebXRCameraSet`
https://github.com/SoundGuy/GGJ2021

**Comment by ilariadinardo3** [comment]
Thank you so much. It helps me a lot!
One last question, I need a laser pointer to click on "door". is it possible? I have created the raycaster with the line renderer

**Comment by De-Panther** [comment]
Yes. And I see you asked more in the other repo, so I'll comment there
