### ISSUE TITLE
Compatible with IOS?

### ISSUE THREAD

**Issue by MarcoLavoro** [De-Panther/unity-webxr-export#131]
Hi, I tried the demo:
https://de-panther.github.io/unity-webxr-export/Build/
 with my android device and it works NICE!
But on both my iPhone 7 and iPhone 10 the AR button is NOT selectable... (ARFoundation works on both device)
This project is not compatible with IOS?

**Comment by De-Panther** [comment]
iOS doesn't support WebXR, the only option on iOS, is the Mozilla WebXR Viewer, which didn't get an update 8 months (or something like that)

**Comment by MarcoLavoro** [comment]
So 

> iOS doesn't support WebXR, the only option on iOS, is the Mozilla WebXR Viewer, which didn't get an update 8 months (or something like that)

Thanks a lot for the SUPER fast reply
In this case i can not use it on this project but THANKS A LOT
It work correctly on Mac for VR?

by the way, very awesome job!

**Comment by De-Panther** [comment]
Thanks.

On iOS, all the browsers are based on Safari.
Safari supports WebVR (old deprecated API), and there's a WebXR Polyfill script that use that old API and make it act like WebXR.
That's why the VR session works

**Comment by devesh-ls** [comment]
@De-Panther So is there any way to run AR thing of Safari with your sdk?
