### ISSUE TITLE
Not Working On iOS

### ISSUE THREAD

**Issue by lijualivenow** [De-Panther/unity-webxr-export#134]
Both AR and VR not working on iOS.

**Comment by TheXRMonk** [comment]
> Both AR and VR not working on iOS.

Not compatible - WebXR is not supported by Apple. Maybe just use 2 minutes to read the readme next time.

**Comment by De-Panther** [comment]
Please be nice to each other.

WebXR isn't supported on iOS by Apple, but there's the deprecated Mozilla WebXR Viewer.
It has some issues with WebXR Export, like this one https://github.com/De-Panther/unity-webxr-export/issues/126

**Comment by ROBYER1** [comment]
Keep an eye on IOS Safari WebXR support here, it is just blocked by two outstanding issues 
https://bugs.webkit.org/show_bug.cgi?id=208988
