### ISSUE TITLE
Make the WebXR.asmdef for WebGL builds only

### ISSUE THREAD

**Issue by wasplay** [De-Panther/unity-webxr-export#138]
Making cross-platform VR games is hard, but this makes it even harder since I have to replace the file with my own modified one each time Unity refreshes the packages. This is really easy to do, takes 10scd and shouldn't affect anything else.

**Comment by De-Panther** [comment]
Thanks for the feedback.

WebXR Export should work on other platforms.

The WebXRController wraps 'UnityEngine.XR.InputDevice' when in Editor or other platform.
So you won't have to use different rigs for different platforms.

Are you getting errors when compiling to other platforms?

**Comment by wasplay** [comment]
Yes, I'm getting IL2CPP errors when compiling to Android and Windows. ( https://pastebin.com/raw/ESNqkzKt )
Also the "Managed Stripping Level" setting is set to Low

**Comment by De-Panther** [comment]
Thanks for the log and info, helped me to reproduce and fix the bug.
You can now build to desktop using IL2CPP. You can even use the WebXR camera rig
