### ISSUE TITLE
Local= O.K., uploaded= fail.

### ISSUE THREAD

**Issue by fuzzy3d** [De-Panther/unity-webxr-export#140]
Hi De-panther, your WebXR packages work absolutely great when I build from Unity and run it locally (Firefox) on my PC, but if I upload the buil to my site it doesn't work. I don't know where I'm making a mistake - do I have to use https instead of http?

Edge:
UnityLoader.js:3 Invoking error handler due to
Uncaught TypeError: Cannot set property 'requestAnimationFrame' of undefined

Firefox:
![image](https://user-images.githubusercontent.com/49310746/115365372-9cb98d00-a1c4-11eb-9f67-a7d76e24ef80.png)

**Comment by De-Panther** [comment]
use HTTPS

**Comment by fuzzy3d** [comment]
Thank you, I'll try it!

**Comment by fuzzy3d** [comment]
It works flawlessly with the https protocol. Tested from Unity 2019.4.16f1 + de-panther.webxr-0.9.0-preview.unitypackage,
Firefox, HP Reverb G2 headset, HP Omen laptop with RTX 2070 Max-Q. Tested on stage with 7.6M polygons. Minor problem - The SteamVR headset must not be in sleep mode when the VR button on the page is pressed. Thank you for working on WebXR for Unity.
