### ISSUE TITLE
InputSystem package and Oculus browser

### ISSUE THREAD

**Issue by jmehh** [De-Panther/unity-webxr-export#145]
Hi, apologies if this is a silly question but I was wondering if you had any insight.

I've been trying to use this package along with the Unity InputSystem package. Testing over oculus link with a Quest 2 it seems to work fine, with each the oculus controllers presenting as joysticks with names 'Oculus Touch (Right)' and 'Oculus Touch (Left)'. However, when testing in the Quest 2 with the oculus browser instead of over oculus link, these devices do not exist. Infact, when using the oculus browser, the unity player only seems to be aware of 'Mouse' and 'Keyboard' input devices. 

Any idea on why this might be?

**Comment by jmehh** [comment]
To add to this, in Firefox Reality, the same thing occurs at first. However, if you put the headset down and let it sleep, then put it back on, the unity player will now have access to the Oculus touch input devices through its InputManager.

**Comment by De-Panther** [comment]
I never tried to enable the controllers using the InputSystem in WebXR, so the fact that it actually works in one browser in some cases is weird and new to me :)
I guess that using the InputSystem is better in some cases, but for now you'll have to use the `WebXRController` component for input.

Supporting the InputSystem is part of a bigger task of better support for Unity XR SDK, but as long as the XR SDK doesn't support WebGL, it's hard or impossible to support some of the systems.
But I'll try to see if there's a way to add WebXR controllers to the InputSystem outside of the XR SDK.

**Comment by jmehh** [comment]
Yeah, using the InputSystem is handy for my usecase. I ended up creating virtual devices with an XRController layout and queing events to them from based on what's recieved in 'OnControllerUpdate'. Seems to work well enough.

Thanks for the swift response, and thanks for working on this awesome project!

**Comment by De-Panther** [comment]
Interesting!

Is there a sample for how to create virtual devices for the InputSystem?

Thanks.
Closing the issue as you handled your problem, but you can keep comment here. If there's a solution for the InputSystem I'll open a new issue for a task about it.
