### ISSUE TITLE
webXR build not running

### ISSUE THREAD

**Issue by smallvalthoss** [De-Panther/unity-webxr-export#152]
I have been trying to build the webXR sample scene (dessert) and when I run it on the node.js npm server it just loads immediately to ~80% and stays there. 
- Unity 2020.3.10f1
- WebXR Export 0.10.1
- WebXR Interactions 0.10.0
<img width="1313" alt="Capture" src="https://user-images.githubusercontent.com/48263101/120123981-1b63fb80-c16f-11eb-883d-9aeee445a4e9.PNG">

**Comment by De-Panther** [comment]
Can you copy paste here the Chrome DevTools console log?

**Comment by smallvalthoss** [comment]
> 
> 
> Can you copy paste here the Chrome DevTools console log?

Here it is:

> Uncaught SyntaxError: Invalid or unexpected token
>Build.loader.js:1 Uncaught ReferenceError: unityFramework is not defined
    at HTMLScriptElement.r.onload (Build.loader.js:1)
>Build.loader.js:1 [UnityCache] 'https://127.0.0.1:8080/Build/Build.data.gz' successfully revalidated and served from the indexedDB cach

**Comment by De-Panther** [comment]
That's only one line... it seems that your server isn't defined correctly.
Maybe you are using gzip/brotly but the server doesn't define to serve them correctly.
Try to build uncompressed in the player settings

**Comment by smallvalthoss** [comment]
> 
> 
> That's only one line... it seems that your server isn't defined correctly.
> Maybe you are using gzip/brotly but the server doesn't define to serve them correctly.
> Try to build uncompressed in the player settings

That worked... Thank you so much for the help. I feel a little dumb

**Comment by smallvalthoss** [comment]
It worked for the sample scene, however I added some stuff from a project that uses "oculus integration" package. I removed everything oculus from the scene, replaced with the WebXRCameraSet and it gives me the dlopen linking message. Here is the console log:

Build.loader.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
printErr @ Build.loader.js:1
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
<img width="632" alt="Capture" src="https://user-images.githubusercontent.com/48263101/120138610-08175700-c194-11eb-8a1f-d29bf99b2848.PNG">

(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Build.loader.js:1 falling back to ArrayBuffer instantiation
printErr @ Build.loader.js:1
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Build.loader.js:1 [UnityCache] 'https://127.0.0.1:8080/Build/Build.data' successfully revalidated and served from the indexedDB cache
Build.framework.js:1186 Loading player data from data.unity3d

Build.framework.js:1186 Initialize engine version: 2020.3.10f1 (297d780c91bc)

Build.framework.js:1186 [Subsystems] Discovering subsystems at path UnitySubsystems

Build.framework.js:1186 [Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/__Internal/UnitySubsystemsManifest.json

Build.framework.js:1186 [Subsystems] 1 'displays' descriptors matched in UnitySubsystems/__Internal/UnitySubsystemsManifest.json

Build.framework.js:1186 [Subsystems] No descriptors matched for  meshings in UnitySubsystems/__Internal/UnitySubsystemsManifest.json.

Build.loader.js:1 Creating WebGL 2.0 context.
Build.framework.js:1186 Renderer: WebKit WebGL

Build.framework.js:1186 Vendor:   WebKit

Build.framework.js:1186 Version:  OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))

Build.framework.js:1186 GLES:     3

Build.framework.js:1186  EXT_color_buffer_float GL_EXT_color_buffer_float EXT_color_buffer_half_float GL_EXT_color_buffer_half_float EXT_disjoint_timer_query_webgl2 GL_EXT_disjoint_timer_query_webgl2 EXT_float_blend GL_EXT_float_blend EXT_texture_compression_bptc GL_EXT_texture_compression_bptc EXT_texture_compression_rgtc GL_EXT_texture_compression_rgtc EXT_texture_filter_anisotropic GL_EXT_texture_filter_anisotropic EXT_texture_norm16 GL_EXT_texture_norm16 KHR_parallel_shader_compile GL_KHR_parallel_shader_compile OES_texture_float_linear GL_OES_texture_float_linear WEBGL_compressed_texture_s3tc GL_WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb GL_WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info GL_WEBGL_debug_renderer_info WEBGL_debug_shaders GL_WEBGL_debug_shaders WEBGL_lose_context GL_WEBGL_lose_context WEBGL_multi_draw GL_WEBGL_multi_draw OVR_multiview2 GL_OVR_multiview2

Build.framework.js:1186 WebGL: INVALID_ENUM: getInternalformatParameter: invalid internalformat
_glGetInternalformativ @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x2f6606
(anonymous) @ 05fae84e:0x2ed0d2
(anonymous) @ 05fae84e:0x2eae39
(anonymous) @ 05fae84e:0x494921
(anonymous) @ 05fae84e:0x48b88a
(anonymous) @ 05fae84e:0x48a69c
(anonymous) @ 05fae84e:0x488151
(anonymous) @ 05fae84e:0x474d50
_main @ 05fae84e:0x474927
(anonymous) @ Build.framework.js:1186
callMain @ Build.framework.js:1186
doRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
doCallback @ Build.framework.js:1186
done @ Build.framework.js:1186
done @ Build.framework.js:1186
storeLocalEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
loadRemoteEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
reconcile @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
getDB @ Build.framework.js:1186
getRemoteSet @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
getLocalSet @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
callRuntimeCallbacks @ Build.framework.js:1186
preRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
receiveInstance @ Build.framework.js:1186
receiveInstantiatedSource @ Build.framework.js:1186
Promise.then (async)
instantiateArrayBuffer @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Build.framework.js:1186 WebGL: INVALID_ENUM: getInternalformatParameter: invalid internalformat
_glGetInternalformativ @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x2f6606
(anonymous) @ 05fae84e:0x2ed0d2
(anonymous) @ 05fae84e:0x2eae39
(anonymous) @ 05fae84e:0x494921
(anonymous) @ 05fae84e:0x48b88a
(anonymous) @ 05fae84e:0x48a69c
(anonymous) @ 05fae84e:0x488151
(anonymous) @ 05fae84e:0x474d50
_main @ 05fae84e:0x474927
(anonymous) @ Build.framework.js:1186
callMain @ Build.framework.js:1186
doRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
doCallback @ Build.framework.js:1186
done @ Build.framework.js:1186
done @ Build.framework.js:1186
storeLocalEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
loadRemoteEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
reconcile @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
getDB @ Build.framework.js:1186
getRemoteSet @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
getLocalSet @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
callRuntimeCallbacks @ Build.framework.js:1186
preRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
receiveInstance @ Build.framework.js:1186
receiveInstantiatedSource @ Build.framework.js:1186
Promise.then (async)
instantiateArrayBuffer @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Build.framework.js:1186 WebGL: INVALID_ENUM: getInternalformatParameter: invalid internalformat
_glGetInternalformativ @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x2f6606
(anonymous) @ 05fae84e:0x2ed0d2
(anonymous) @ 05fae84e:0x2eae39
(anonymous) @ 05fae84e:0x494921
(anonymous) @ 05fae84e:0x48b88a
(anonymous) @ 05fae84e:0x48a69c
(anonymous) @ 05fae84e:0x488151
(anonymous) @ 05fae84e:0x474d50
_main @ 05fae84e:0x474927
(anonymous) @ Build.framework.js:1186
callMain @ Build.framework.js:1186
doRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
doCallback @ Build.framework.js:1186
done @ Build.framework.js:1186
done @ Build.framework.js:1186
storeLocalEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
loadRemoteEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
reconcile @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
getDB @ Build.framework.js:1186
getRemoteSet @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
getLocalSet @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
callRuntimeCallbacks @ Build.framework.js:1186
preRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
receiveInstance @ Build.framework.js:1186
receiveInstantiatedSource @ Build.framework.js:1186
Promise.then (async)
instantiateArrayBuffer @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Build.framework.js:1186 OPENGL LOG: Creating OpenGL ES 3.0 graphics device ; Context level  <OpenGL ES 3.0> ; Context handle 29751304

119The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
Build.framework.js:1186 XRGeneral Settings awakening...


Build.framework.js:1186 Registered WebXRSubsystemDescriptor


Build.framework.js:1186 Got WebXRSettings


Build.framework.js:1186 {VRRequiredReferenceSpace: Array(1), VROptionalFeatures: Array(1), ARRequiredReferenceSpace: Array(1), AROptionalFeatures: Array(2)}
Build.framework.js:1186 Sent WebXRSettings


Build.framework.js:1186 Start WebXRSubsystem


Build.framework.js:1186 UnloadTime: 0.490000 ms

Build.loader.js:1 To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking
Build.loader.js:1 To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking
printErr @ Build.loader.js:1
abort @ Build.framework.js:1186
_dlopen @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x14f926d
(anonymous) @ 05fae84e:0x14f91d1
(anonymous) @ 05fae84e:0x153ca07
(anonymous) @ 05fae84e:0x11d288a
(anonymous) @ 05fae84e:0x11d281f
(anonymous) @ 05fae84e:0x11d26de
(anonymous) @ 05fae84e:0xd73813
dynCall_iiiii @ 05fae84e:0x156bd86
(anonymous) @ Build.framework.js:1186
invoke_iiiii @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x151a083
(anonymous) @ 05fae84e:0xcfda5b
(anonymous) @ 05fae84e:0x23aa60
(anonymous) @ 05fae84e:0x23a730
(anonymous) @ 05fae84e:0x412942
(anonymous) @ 05fae84e:0x4126e9
(anonymous) @ 05fae84e:0x5cf318
(anonymous) @ 05fae84e:0x22a4c1
(anonymous) @ 05fae84e:0x413542
(anonymous) @ 05fae84e:0x411e67
(anonymous) @ 05fae84e:0x412222
(anonymous) @ 05fae84e:0x41173c
(anonymous) @ 05fae84e:0x489a20
(anonymous) @ 05fae84e:0x48973c
(anonymous) @ 05fae84e:0x4895fb
(anonymous) @ 05fae84e:0x488e46
(anonymous) @ 05fae84e:0x488576
(anonymous) @ 05fae84e:0x474d8d
_main @ 05fae84e:0x474927
(anonymous) @ Build.framework.js:1186
callMain @ Build.framework.js:1186
doRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
doCallback @ Build.framework.js:1186
done @ Build.framework.js:1186
done @ Build.framework.js:1186
storeLocalEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
loadRemoteEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
reconcile @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
getDB @ Build.framework.js:1186
getRemoteSet @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
getLocalSet @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
callRuntimeCallbacks @ Build.framework.js:1186
preRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
receiveInstance @ Build.framework.js:1186
receiveInstantiatedSource @ Build.framework.js:1186
Promise.then (async)
instantiateArrayBuffer @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Show 15 more frames
Build.framework.js:1186 DllNotFoundException: Unable to load DLL 'AudioPluginOculusSpatializer': The specified module could not be found.



_JS_Log_Dump @ Build.framework.js:1186
(anonymous) @ 05fae84e:0x22a44b
(anonymous) @ 05fae84e:0x22a5ce
(anonymous) @ 05fae84e:0x22a25d
(anonymous) @ 05fae84e:0x22977f
(anonymous) @ 05fae84e:0x23af53
(anonymous) @ 05fae84e:0x23a7c2
(anonymous) @ 05fae84e:0x412942
(anonymous) @ 05fae84e:0x4126e9
(anonymous) @ 05fae84e:0x5cf318
(anonymous) @ 05fae84e:0x22a4c1
(anonymous) @ 05fae84e:0x413542
(anonymous) @ 05fae84e:0x411e67
(anonymous) @ 05fae84e:0x412222
(anonymous) @ 05fae84e:0x41173c
(anonymous) @ 05fae84e:0x489a20
(anonymous) @ 05fae84e:0x48973c
(anonymous) @ 05fae84e:0x4895fb
(anonymous) @ 05fae84e:0x488e46
(anonymous) @ 05fae84e:0x488576
(anonymous) @ 05fae84e:0x474d8d
_main @ 05fae84e:0x474927
(anonymous) @ Build.framework.js:1186
callMain @ Build.framework.js:1186
doRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
doCallback @ Build.framework.js:1186
done @ Build.framework.js:1186
done @ Build.framework.js:1186
storeLocalEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
loadRemoteEntry @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
reconcile @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
IndexedDB (async)
getDB @ Build.framework.js:1186
getRemoteSet @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
getLocalSet @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
syncfs @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
callRuntimeCallbacks @ Build.framework.js:1186
preRun @ Build.framework.js:1186
run @ Build.framework.js:1186
runCaller @ Build.framework.js:1186
removeRunDependency @ Build.framework.js:1186
receiveInstance @ Build.framework.js:1186
receiveInstantiatedSource @ Build.framework.js:1186
Promise.then (async)
instantiateArrayBuffer @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
Promise.catch (async)
doNativeWasm @ Build.framework.js:1186
(anonymous) @ Build.framework.js:1186
unityFramework @ Build.framework.js:1186
(anonymous) @ Build.loader.js:1
Promise.then (async)
u @ Build.loader.js:1
(anonymous) @ Build.loader.js:1
createUnityInstance @ Build.loader.js:1
script.onload @ (index):58
load (async)
(anonymous) @ (index):57
Show 5 more frames
Build.framework.js:1186 warning: 2 FS.syncfs operations in flight at once, probably just doing extra work

**Comment by De-Panther** [comment]
The Oculus integration doesn't work on WebGL.
the `AudioPluginOculusSpatializer` DLL doesn't have a port to WebGL... And I guess other stuff there won't work as well.
