### ISSUE TITLE
No active WebXR.WebXRSubszstem is available. XR Still works

### ISSUE THREAD

**Issue by J0ye** [De-Panther/unity-webxr-export#159]
I need to know if a VR system is set up correctly because I want to provide both VR and normal 3D controls for my application and I want the app to change dynamically. I think I can achieve this verification with the WebXRManager subsystem. However, I always get the following warning when testing the application. 
![Screenshot 2021-06-14 153819](https://user-images.githubusercontent.com/27226519/121901321-93f9b900-cd26-11eb-8261-1b28c8c6bb66.png)

My Unity version is 2019.4.17 LTS and i started the desert sample scene. I enabled the WebXR Export in the XR Plug-in Managment as you can see. The app throws an error when I try to call WebXRManager.instance.subsystem or .visibillitystate, because of this.

**Comment by De-Panther** [comment]
The WebXRSubsystem works only on WebGL runtime.
In the editor/other platforms some components (e.g. WebXRController) use the general XR subsystems functions
