### ISSUE TITLE
Getting an error after importing webxr plugin and webXR exporter

### ISSUE THREAD

**Issue by kamleshlohar2** [De-Panther/unity-webxr-export#165]
Hii,
After importing plug-ins and WebXR exporter package into Unity 2019.4.6f1, I am getting error as:- Assembly with name 'WebXR' already exists for both location ((Assets/WebXR/Scripts/WebXR.asmdef) and (Packages/com.de-panther.webxr/Runtime/WebXR.asmdef)).

​Please refer below screenshot for more clarification:-
![download](https://user-images.githubusercontent.com/86820409/124227765-ced25e00-db28-11eb-85a7-b9e81e0d834f.png)

I Tried with removing one of the assemblies. But after getting build and hosting over server, I'm getting this issue:-
![download (1)](https://user-images.githubusercontent.com/86820409/124227865-ef021d00-db28-11eb-8fb3-b6420c81672e.png)

Console Logs:- 
![download (2)](https://user-images.githubusercontent.com/86820409/124227893-fde8cf80-db28-11eb-8bcf-121765df7dec.png)

Can you please help me with it as I'm stuck in this stage since long time?

Thanks and Regards.
Kamlesh Lohar

**Comment by De-Panther** [comment]
Start a new project and follow the instructions in this repo's Getting Started.
It seems that you are using 2 different exporters.
