### ISSUE TITLE
VR split screen getting freeze on iPhone X and iPhone 12 pro

### ISSUE THREAD

**Issue by kamleshlohar2** [De-Panther/unity-webxr-export#166]
I have developed a sample WebXR application from your Youtube video. VR feature working well with Android devices, but somehow it is not working with iOS devices. So, I opened your application (https://github.com/De-Panther/unity-webxr-export/tree/master/Build) from my iPhone X and iPhone 12 pro for testing purpose. But still same issue (VR screen is getting freeze). You can refer below screenshot:. 
<img width="1075" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/86820409/124474949-c4c98d00-ddbe-11eb-9b32-4e11c131e743.png">

Thanks and Regards,
Kamlesh

**Comment by De-Panther** [comment]
WebXR is not supported on iOS.
There's a polyfill that try to use WebVR on iOS devices, and you can disable it.

**Comment by De-Panther** [comment]
Closing the issue, you are welcome to ask more questions or open new issues if needed.

**Comment by kamleshlohar2** [comment]
Sure, Thank you :-)
