### ISSUE TITLE
VR view not working and New Unity Input system

### ISSUE THREAD

**Issue by Yeisonlop10** [De-Panther/unity-webxr-export#170]
Hi.

Thank you for the hard work. I would like to ask for your help because I'm build the sample scene (Unity 2020.3.12)and access it in Oculus browser (oculus and firefox reality), I can interact with the objects in the '2D', but if I press the VR buttn, I get an awful divided 2D view that just renders a small portion of the scene, no interaction and movement happens and changing the view(180, 360, etc) just result in a completely black scene. I have checked the project settings and they are the same as in your project. Not sure if there is anything  I need to enable. Also I tried to implement a sample using the new input system and nothing happens.

**Comment by De-Panther** [comment]
Did you follow the getting started guides?
The function of 180/360 sounds like the general oculus menu for fullscreen view and not WebXR.

**Comment by Yeisonlop10** [comment]
Hi.

Thank you for your response. My SSL certificate wasn't working properly, and now it goes correctly into the VR view. Does it work for the XR interaction toolkit and the new input system?

**Comment by De-Panther** [comment]
Glad it works.

XR SDK support is in progress, ones that is done, XR Interaction Toolkit will be supported.

No support for the new input system right now.

**Comment by Yeisonlop10** [comment]
Great.

Looking forward to seeing it. Thank you for the hard work.
