### ISSUE TITLE
thumbstick to move

### ISSUE THREAD

**Issue by dplanz** [De-Panther/unity-webxr-export#171]
I am trying to use the thumbstick to move around the scene. I am not seeing any documentation for you to accomplish this. Is there documentation or an example on how to do this?

**Comment by De-Panther** [comment]
You can use `WebXRController.GetAxis2D(Axis2DTypes.Thumbstick)`, to move the `WebXRCameraSet`.
You can see a use of it at https://github.com/De-Panther/Simple-WebXR-Teleporter in the `WebXRTeleporterWrapper` script.

**Comment by dplanz** [comment]
Thanks so much! I'll dive into it today.
