### ISSUE TITLE
Does this package works also for an Oculus Quest App?

### ISSUE THREAD

**Issue by alamboley** [De-Panther/unity-webxr-export#175]
Hello, I've to do a 360 virtual tour which must work via a browser with WebXR and as an Oculus Quest offline app. I don't think the same code can be shared, right? I may keep the same scene, but having differents scripts if I'm in a browser or the app.

**Comment by De-Panther** [comment]
You can use a web service worker for cache.
Oculus not yet supports PWA, but it supports service workers.
You can try offline https://worldsdemolisher.totalviz.com/
We set PWA and service worker for it

**Comment by alamboley** [comment]
Thanks for the quick answer, Glad to know! How many MOs the service worker can keep in cache?

PWA for Oculus are coming https://twitter.com/rcabanier/status/1448675626496393223 ;)

**Comment by De-Panther** [comment]
What is MOs?
The capacity of the cache depends on the browser.
look for the capacity of chromium for Android.

PWAs for Oculus are in the roadmap for a year now (I think).
Looking forward for that.
