### ISSUE TITLE
issue when i import the repository

### ISSUE THREAD

**Issue by danielcv-dev** [De-Panther/unity-webxr-export#177]
Hello everyone,
i try to clone the project, but i have a problem.
when i clone the repository in Unity using the Package Manager, send me the next errors
`[Package Manager Window] Unable to add package [https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions  ]:
  Cannot checkout repository [https://github.com/De-Panther/unity-webxr-export.git] on target path [Packages/webxr-interactions  ]:
    Error when executing git command. error: pathspec 'Packages/webxr-interactions  ' did not match any file(s) known to git`

`[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions  ]:
  Cannot checkout repository [https://github.com/De-Panther/unity-webxr-export.git] on target path [Packages/webxr-interactions  ]:
    Error when executing git command. error: pathspec 'Packages/webxr-interactions  ' did not match any file(s) known to git
 [NotFound].`

`[Package Manager Window] Error adding package: https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions  .
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()`

And when i try the clone with git bash. the error is:

`Cloning into 'webxr-interactions'...
fatal: repository 'https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions/' not found`

Anyone could help me please.

**Comment by De-Panther** [comment]
Seems like you have a space at the end of the URL.
But it's better to use OpenUPM instead of Git.

There's an how-to at
https://github.com/De-Panther/unity-webxr-export/blob/master/Packages/webxr/README.md
