### ISSUE TITLE
How to Check if we exit the VR mode?

### ISSUE THREAD

**Issue by AbdullahBurhan** [De-Panther/unity-webxr-export#178]
Is there an event in which we can know that the user exit the VR mode ?

**Comment by De-Panther** [comment]
WebXRManager.OnXRChange

**Comment by AbdullahBurhan** [comment]
Thank you, 
How can I exit VR mode from WEBXR API ?

**Comment by De-Panther** [comment]
WebXRManager.ToggleVR()

**Comment by AbdullahBurhan** [comment]
Thank you so much
