### ISSUE TITLE
Play in the editor

### ISSUE THREAD

**Issue by AbdullahBurhan** [De-Panther/unity-webxr-export#179]
Is there a way to play the webxr plugin in the Unity  editor, ?cause the development cycle takes too much time until be tested in the browser..

**Comment by Adeptus-Astartes** [comment]
If you targeted on VR I recommend for you get oculus quest 2.
Then you could install Oculus app on windows PC.
Next step is in Unity in XR Manager set Oculus loader in standalone mode.
So then chain is Oculus Quest 2 -> AirLink Connect -> Unity Editor -> Play
