### ISSUE TITLE
Type Error: Cannot set properties of undefined (setting 'Settings')

### ISSUE THREAD

**Issue by Adeptus-Astartes** [De-Panther/unity-webxr-export#180]
Building clean project with:
- Desert sample from OpenUPM on 
- Unity 2021.2b16 
- Minimal code stripping
- IL2CPP generation: Faster runtime
- Code Optimization: Speed

throws thiis exception:
"Build.loader.js:1 exception thrown: TypeError: Cannot set properties of undefined (setting 'Settings'),TypeError: Cannot set properties of undefined (setting 'Settings')"
"Build.framework.js:2 Uncaught TypeError: Cannot set properties of undefined (setting 'Settings')
    at _SetWebXRSettings (Build.framework.js:2)
"

**Comment by Adeptus-Astartes** [comment]
Reason why I'm use beta is ASTC texture compression

**Comment by De-Panther** [comment]
Unity bug.
https://issuetracker.unity3d.com/issues/dot-jspre-files-being-ignored-in-release-build-after-emscripten-update

**Comment by Adeptus-Astartes** [comment]
Cool, at least it on scope

**Comment by De-Panther** [comment]
The fix is now in Unity 2021.2.2
https://unity3d.com/unity/whats-new/2021.2.2
