### ISSUE TITLE
Input.GetMouseButtonDown works only once

### ISSUE THREAD

**Issue by Adeptus-Astartes** [De-Panther/unity-webxr-export#181]
Just notice strange behaviour when using Input.GetMouseButtonDown
It works only once, easy to check by logs.
Also notice when you loose focus on app it also somehow get executed

**Comment by De-Panther** [comment]
Unity version, browser version, OS version, etc... Can't help if there are missing details.

**Comment by Adeptus-Astartes** [comment]
Reproducible only in AR Mode
Mobile Chrome
Samsung S21
Unity 2021.1.10

**Comment by De-Panther** [comment]
Which Chrome version?
Do you have a demo?
Seems to work as it should with the desert scene and my Samsung Galaxy S10e and latest Chrome.

The demo in this repo was built using 2020.3 is it working for you as it should?

**Comment by Adeptus-Astartes** [comment]
I recorded video, where I can drop it?

**Comment by De-Panther** [comment]
Upload somewhere and share it here?

**Comment by Adeptus-Astartes** [comment]
https://drive.google.com/file/d/1vL1FIyr3dtzY1Bg7l4CzSGoYLaLdUf33/view?usp=sharing

**Comment by De-Panther** [comment]
Which Chrome version?

**Comment by Adeptus-Astartes** [comment]
95.04.4638.50

**Comment by De-Panther** [comment]
Does the desert demo works for you? You can drag the sphere/boxes more than once?
Does your demo works on 2020.3?

Maybe the issue is in changes on 2021.1, but I want to confirm it first.

**Comment by Adeptus-Astartes** [comment]
I just tried desert demo and it works on 2021.1
Then I added simple script 
` void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Debug.LogError("Click");
        }
    }`

But this event get executed only once, while I still can drag boxes around

**Comment by Adeptus-Astartes** [comment]
Don't have opportunity to test on 2020.3 had to run, will try later tonight

**Comment by Adeptus-Astartes** [comment]
Can confrim that on 2020.3.21LTS it works as expected!

**Comment by De-Panther** [comment]
Great!

I'll have to look what changed in 2021.1 and I guess there are also relevant changes on 2021.2

**Comment by Adeptus-Astartes** [comment]
@De-Panther  Hey, do have a chance to look at it?

**Comment by De-Panther** [comment]
Sorry, I'll try to take a look at the next weekend
