### ISSUE TITLE
deploy to vps with nodejs camera stays in position

### ISSUE THREAD

**Issue by urbanpixellab** [De-Panther/unity-webxr-export#182]
I am deploying the testscene to a vps with nodejs. If it try it localy it works perfect, after move nodejs and the webcontent to a vps it is still working but the camera isnt moving only rotating, so if i move the camera stays locked and only rotation and hand movements are possible. Compression is disabled in unity.
I am using Unity 2019.4 and nodejs looks like this:

var fs = require('fs');
var http = require('http');
var https = require('https');
var privateKey  = fs.readFileSync('sslcert/key.pem', 'utf8');
var certificate = fs.readFileSync('sslcert/cert.pem', 'utf8');

var compression = require('compression');

var credentials = {key: privateKey, cert: certificate};
var express = require('express');
var app = express();

// your express configuration here
app.use(express.static(__dirname + '/public/'));
app.use(compression());
var httpsServer = https.createServer(credentials, app);

httpsServer.listen(5555);

**Comment by De-Panther** [comment]
Use HTTPS

**Comment by urbanpixellab** [comment]
i use https already, the webserver runs on https. but still the same, if i move around the world is moving with me and i cant reach tye boxes or sphere.

**Comment by De-Panther** [comment]
Are you sure that the URL that you enter is with HTTPS?
Even if your server supports HTTPS, it's not always configure to forward HTTP to HTTPS...

The only thing I can think about from your case, and without looking at the console log, is that you are using HTTP and the WebXR Polyfill is activated because of that

**Comment by urbanpixellab** [comment]
I doubble checked it and i can access it only via https, otherwise it is not visible. I opened it on my computer and got the error at the end. But this is on my computer and not on the oculus quest. Where i dont see a debug console.
Unknown Error 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by De-Panther** [comment]
If you are using Oculus Browser on Quest, you can connect it to the Chrome DevTools.
Please check the console log there.
And please provide more data, like Unity version and browsers versions. (also WebXR Export/Interactions version)

**Comment by urbanpixellab** [comment]
It is solved and a stupid mistake by me. The tracking on the oculus was disabled.
