### ISSUE TITLE
Fail to load on sandboxed iframe

### ISSUE THREAD

**Issue by DanielAbalde** [De-Panther/unity-webxr-export#187]
Hi! Thanks a lot for this, everything works well except that

I upload the exported project to a platform that embed the html in a sandboxed iframe, and it fails due to a postMessage call. The developer of that platform told me that sandboxes iframes doesn't have the same origin as parent window so postMessage is not allowed...

I don't know if this is true or not, I'm not a web programmer, but if it is true, is there any way to exporting for sandboxed iframes? or could you implement it please? The use case are html-based NFTs.

Thanks!

**Comment by De-Panther** [comment]
I don't see any use in 'postMessage' to communicate with this package.
But in order to run WebXR in an iframe you need to allow it.
add `allow="xr-spatial-tracking"` to the iframe tag

**Comment by DanielAbalde** [comment]
You're right, the call is in build.framework.js, which I guess is autogenerated by Unity... 
The iframe already allows xr-spatial-tracking. 

This is a pity. If you have any suggestions on how to get around this problem please let me know. I can't change the iframe as it is on a third party platform.
