### ISSUE TITLE
not support webGL 2.0 on ios

### ISSUE THREAD

**Issue by 0x3f97** [De-Panther/unity-webxr-export#188]
![ad8d319d73687060b921ab1e09fd334](https://user-images.githubusercontent.com/32476377/144895405-17245845-9242-4ab1-bdcf-77d585da2a73.jpg)

**Comment by Chopium** [comment]
Safari is backwards on WebGL 2.0. You need to turn off auto graphics api in your Unity project settings and make sure WebGL 1.0 is added as an API to support safari. Even then, it's buggy and jank, sorry to speak from experience.

**Comment by De-Panther** [comment]
Unity WebGL issue, not this package issue
