### ISSUE TITLE
Unity webGL related build issue with latest updated code 

### ISSUE THREAD

**Issue by Amar1312** [De-Panther/unity-webxr-export#200]
http://https//techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:16334stackTrace@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:16505abort@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:748_set_webxr_events@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:309856@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[38184]:0xc90226@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[38190]:0xc90ede@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[25421]:0x9f280a@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[41954]:0xd45f4funityFramework/Module.dynCall_iiiii@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:464452invoke_iiiii@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:338013@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[40077]:0xcf02c2@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[39547]:0xcd9c2e@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[4307]:0x192057@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[4305]:0x191d27@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[8272]:0x2f7448@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[8270]:0x2f62f3@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10464]:0x3ca274@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[8507]:0x31188c@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10885]:0x3f9941@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10565]:0x3d3e14@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10565]:0x3d3e29@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10560]:0x3d3937@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[10553]:0x3d1b43@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js%20line%202%20%3E%20WebAssembly.instantiate:wasm-function[41969]:0xd46197unityFramework/Module.dynCall_v@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:472281browserIterationFunc@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:175829runIter@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:178902Browser_mainLoop_runner@https://techavtra.com/WebUnity/websurfacechecking/Build/websurfacechecking.framework.js:2:177364

**Comment by De-Panther** [comment]
I don't know what you want with this out of nowhere error message, but read the docs and follow the getting started guide.
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md
