### ISSUE TITLE
No object placement in AR

### ISSUE THREAD

**Issue by XRAdventure** [De-Panther/unity-webxr-export#201]
Hi, 
I am having an issue with positioning objects when I try to get close to them, the objects move away and do not stay static in Augmented Reality. 

My current setup
Unity 2020.3.19
Android 9.0

This is what is happening
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/93439826/150597675-cc0546ca-6a71-4a86-897c-29adc71a580a.gif)

I don't understand how SceneHitTest` works. Is this the object that is in charge of the positioning of the objects in the scene? 

Or should I make any changes here? 
![image](https://user-images.githubusercontent.com/93439826/150597841-561a9bd2-e2e6-4d38-a933-6429d59cce41.png)

Thank you for your help

**Comment by De-Panther** [comment]
There can be few issues,
Optical illusion - the vegetation at the back is far, but projected on near object. same goes for the shark.
And device drifting, e.g. going too close to the wall, so the SLAM doesn't work or doesn't work well.

Better test it with an empty scene with only a small cube.

**Comment by marcusx2** [comment]
I somehow fucked up the project and now I'm having the same problem. It wasn't like this before though, I wonder what can cause this.

**Comment by marcusx2** [comment]
The issue on my case was that I had changed the AR settings. The AR Required Reference Space was set to `Viewer`, then I changed to `local_floor `and it worked again.
