### ISSUE TITLE
non-vr mode

### ISSUE THREAD

**Issue by rauwebieten** [De-Panther/unity-webxr-export#202]
Is there a way to allow people who don't have vr-glasses to enjoy the build in a "fallback mode" ?
For example to let them look around with mouse controls.
Or should i create a different build?

I'm new to Unity/VR, don't know if this is the right place to ask. Please show me the right direction.

**Comment by De-Panther** [comment]
Yes, you can add your own mouse controls to the 'WebXRCameraSet' GameObject, and to the child camera 'CameraMain'.

If you wants to move all the rig, so when user switch to XR, he'll be in the location of the non-xr camera, your script would need to update the position of the 'WebXRCameraSet' while the update of the rotation would be for the 'CameraMain'.

You might even want to rotate 'WebXRCameraSet' on Y axis around the 'CameraMain', and rotate 'CameraMain' only on X axis

**Comment by rauwebieten** [comment]
Hi, thanks for the quick reply, 

I'll try this setup today, and get back to you with the results.

**Comment by rauwebieten** [comment]
Hi, got it all working today. Thanks for the assistance!
