### ISSUE TITLE
Demo scene stuck on loading when switching to VR

### ISSUE THREAD

**Issue by jacoposcala** [De-Panther/unity-webxr-export#205]
Hello!
I built the demo scene with success and uploaded it on my https server, it works exept when switching to VR with my oculus rift connected, the loading screen appears in the oculus view but the application never actually starts.
The same issue happens with you demo scene at https://de-panther.github.io/unity-webxr-export/Build/

- Using google chrome on windows PC
- The permission for VR popup appears correctly
- Oculus Rift  works with other applications (ex https://www.xrdinosaurs.com/)

**Comment by De-Panther** [comment]
The samples at
https://immersive-web.github.io/webxr-samples/
Works for you with and without Polyfill?
Which Chrome version?

**Comment by De-Panther** [comment]
The issue was a Chrome bug, of opening multiple tabs with WebXR content.
