### ISSUE TITLE
Unity WebGL build failing to load status 400

### ISSUE THREAD

**Issue by k-g-j** [De-Panther/unity-webxr-export#207]
When I build the project and try and serve it locally, my project fails to load.  I followed all the steps except replaced the sample scene with my own scene. 

<img width="701" alt="Screen Shot 2022-03-15 at 11 04 57 AM" src="https://user-images.githubusercontent.com/91970214/158408356-2475d63a-b0e2-4954-9527-117c2a75f999.png">
<img width="1501" alt="Screen Shot 2022-03-15 at 11 07 21 AM" src="https://user-images.githubusercontent.com/91970214/158408420-d292c25a-bdc8-498f-be0e-1a3d3a858c32.png">

**Comment by De-Panther** [comment]
Please use relevant WebGLTemlate based on the Unity version.
WebXR for 2019.4
WebXR2020 for 2020.1 and up (include 2021 and 2022)

**Comment by k-g-j** [comment]
I am using 2020.1

**Comment by De-Panther** [comment]
So use the WebXR2020 or WebXRFull2020 templates

**Comment by dburnsii** [comment]
I had this issue, switching the template definitely solved it. Maybe it would be a good idea to rename the WebXR template to WebXR2019 to avoid confusion?

**Comment by k-g-j** [comment]
Yes that solved the problem for me!  You can close the issue.  Thank you!

**Comment by De-Panther** [comment]
@dburnsii renaming might help new users, but will confuse existing ones.
The getting started guide explains this issue.
I can't think of a better solution :/
