### ISSUE TITLE
position of main camera

### ISSUE THREAD

**Issue by rauwebieten** [De-Panther/unity-webxr-export#208]
Hi, 

A question, i'm playing with webxr-export with vrtk. 
I have a tracked alias camera rig with 1. a spatial simulator for development 2. the webxr camera rig for my build.

A have tooltip with "facing source" set to the "headset alias". This should make the tooltip always face the player.

In my unity preview, the tooltip is perfectly facing the headset.
In my webxr build the tooltip in direction of the headset, but facing the ground. 

Any ideas?

**Comment by De-Panther** [comment]
Try to set it to the GameObject CameraFollower
