### ISSUE TITLE
UI button interaction

### ISSUE THREAD

**Issue by joostVRbeelding** [De-Panther/unity-webxr-export#209]
I have a question, rather than an issue, but I don't see another place to ask it.

Is there an example on how to use an in-world UI canvas in WebXR? Through the documentation page I found VRTK and started looking at that, but got lost in the huge amount of packages and the complicated solution with camera aliases and event dispatchers.

And in the VRTK tutorial I saw that there is a WebXR namespace, where can I find the API documentation for that?

Are there components or prefabs like a WebXR pointer?

Thanks.

**Comment by De-Panther** [comment]
I'm not familiar with VRTK, so I can't help with that.
There's this repo where I implemented something similar as an example, but you'll have to dig into the code and figure out what was done there:
https://github.com/De-Panther/WebXR-Unity-Samples

If you are looking for more places to ask questions about WebXR or Unity+WebXR, there's the WebXR Discord server https://discord.gg/webxr
