### ISSUE TITLE
WebXR for augmented reality

### ISSUE THREAD

**Issue by antoniofurioso** [De-Panther/unity-webxr-export#210]
Hello everyone, I'm just asking myself if it's possible to use this cool package with AR foundation or Vuforia to build a cool AR experience on the internet.

If is it possible how can I do to implement all the things?

**Comment by De-Panther** [comment]
You can use this package for AR, but it doesn't work out of the box with AR Foundation or Vuforia, I guess you'll have to write your own interface for them to work in the same project.

**Comment by antoniofurioso** [comment]
Okay, but with your package, I could do an Image and world tracking?

**Comment by De-Panther** [comment]
I'm not sure what are you referring to as world tracking, but WebXR supports 6DOF tracking if the device allows that.
WebXR also supports Hit-Test if the device allows that.

There's an experimental image tracking for WebXR in Android Chrome behind a flag, but the package currently doesn't support it.

It's better to ask those types of questions at the Unity channel on WebXR Discord, as there are more people that can help https://discord.gg/webxr
