### ISSUE TITLE
Internal Unity error: gles::GetProcAddress

### ISSUE THREAD

**Issue by aaronvdbrugge** [De-Panther/unity-webxr-export#211]
Internal Unity error: gles::GetProcAddress("glFramebufferTextureMultiviewOVR") was called. gles::GetProcAddress() is not implemented on Unity WebGL. Please report a bug. 

I get this on web browser on Oculus Go and it was also reported on Oculus Quest with the provided demo.

Please advise.

**Comment by De-Panther** [comment]
The Oculus Browser on Oculus Go is no longer supported.
If you are using an updated version of the Oculus Browser on the Quest 1 or 2, you shouldn't get this message.
Or if you are using an up to date version of Unity either from the LTS (e.g. 2020.3.x) or the current tech stream (2021.2.x), it was fixed and backported in the last few months.

Not related to WebXR, just Oculus Browser and Unity WebGL issues.

**Comment by aaronvdbrugge** [comment]
Thank you very much for the reply. I am using Unity 2022.1 and the latest
demo download of your project. Should I downgrade or upgrade anything to
make it backwards compatible with Oculus Go or is that a bad idea? I'll get
a Quest 2 at some point so maybe it's pointless.

Thank you for the advice.

**Comment by De-Panther** [comment]
I recommend using the latest 2020.3 or the latest 2021.2
One of them *should* have a fix for this error.

**Comment by aaronvdbrugge** [comment]
Thank you, it works with 2021.2!
