### ISSUE TITLE
Adding UI?

### ISSUE THREAD

**Issue by aaronvdbrugge** [De-Panther/unity-webxr-export#213]
Excuse me if this is a basic question.

What is the recommended way to add UI to, for example, the demo scene?

Should it be a Canvas - Screen Overlay, Canvas attached to Camera L or R maybe? (For WebGL, WebXR VR)
Or a World Space, and if it's a world space, how to activate the 'targeting Raycast'? Not sure how to add these input triggers to the demo setup.

Thank you for your time.

**Comment by De-Panther** [comment]
There's no universal UI that would work on all cases.
Better have a UI for each type of interaction - flat screens (no XR, or handheld AR), and VR or headset based AR.
Regarding casting to the UI in XR mode, there's this old Samples repo https://github.com/De-Panther/WebXR-Unity-Samples that you can check.
But I think that VRTK also has some handles for this, so you can look for some youtube tutorials that explains how to intergate VRTK and this package.
