### ISSUE TITLE
Best way to add controls to package?

### ISSUE THREAD

**Issue by aaronvdbrugge** [De-Panther/unity-webxr-export#214]
Hi,

Apologies for adding one more 'Issue'.

I want to add some custom controls and I've been editing ControllerInteraction script, but it's part of the package and my edits get overwritten.

How can I add to this class (and package in general) properly? The way it's installed and setup, I can't get it out of the Packages folder. I am just wondering how you see it for users to create their own interaction classes without having to replace the entire ControllerInteraction script.

Thanks,

**Comment by SansoneKineton** [comment]
Did you find a solution?

**Comment by nsmith1024** [comment]
Did you figure this out because i cant do it either. Also there seems to be no way to access classes that are inside the package from a new class outside the package.

**Comment by andrea-sansone** [comment]
if you need to just access classes and methods, you have to define an Assembly Definition Reference that point to the WebXR Assembly Definition. You can try to understand more by searching on Google
