### ISSUE TITLE
VR only detected in mobile mode

### ISSUE THREAD

**Issue by MajorAjer** [De-Panther/unity-webxr-export#215]
Hey, 
I am having 2 issues with this and I suspect that they are related. 

-First, the sample project and the project I want to use this on, have their VR button disabled when in desktop mode on the browser. 
-Second, in VR while in mobile desktop mode, I can see both eyes as 2D objects mapped upon a sphere. They are not true VR and they do not track my movement.

I am testing this on Oculus Quest 1 Browser. The Unity versions I have tried are 2021, 2020, and 2019 for the sample project only. I would really appreciate help on this and thank you for putting this together!

**Comment by De-Panther** [comment]
I'm not sure I understand the issue?
Is this demo doesn't work? https://de-panther.github.io/unity-webxr-export/Build

Did you tried the VR samples of the WebXR Samples on those devices and browsers?
https://immersive-web.github.io/webxr-samples/

**Comment by MajorAjer** [comment]
Both of those demos work correctly. Building the webXR scene from scratch causes the browsers to only detect VR while in mobile mode. I can post a screenshot or a project file after I get some more time to work on this.

**Comment by De-Panther** [comment]
Are you following the getting started guide? Using HTTPS server?

**Comment by MajorAjer** [comment]
Yeah i followed the getting started guide and FusedVR's youtube video. I am not running on HTTPS but I am running on HTTP. I will check this and let you know if it fixes my issues

**Comment by De-Panther** [comment]
Both mentioned HTTPS for a reason :)
WebXR runs only on secured context - localhost or HTTPS.

Please update. Closing the issue for now.

**Comment by MajorAjer** [comment]
yeah no worries, someone on my team was insisting that HTTP vs HTTPS wouldnt matter - this gave me what I needed thanks!

**Comment by chadlyalan** [comment]
> I'm not sure I understand the issue? Is this demo doesn't work? https://de-panther.github.io/unity-webxr-export/Build
> 
> Did you tried the VR samples of the WebXR Samples on those devices and browsers? https://immersive-web.github.io/webxr-samples/

I've recently been getting development started using this. The sample build loads on my mobile device (pixel 3, up to date) but the AR scene doesn't show any objects to interact with. 
It simply opens the AR scene camera and that's it. 

After getting my own environment set up I found the same problem. Since I'm experiencing it on your sample build as well I assume it's something on my end. Do you know how I could troubleshoot this issue?

**Comment by De-Panther** [comment]
> > I'm not sure I understand the issue? Is this demo doesn't work? https://de-panther.github.io/unity-webxr-export/Build
> > Did you tried the VR samples of the WebXR Samples on those devices and browsers? https://immersive-web.github.io/webxr-samples/
> 
> I've recently been getting development started using this. The sample build loads on my mobile device (pixel 3, up to date) but the AR scene doesn't show any objects to interact with. It simply opens the AR scene camera and that's it.
> 
> After getting my own environment set up I found the same problem. Since I'm experiencing it on your sample build as well I assume it's something on my end. Do you know how I could troubleshoot this issue?

Is this works for you?
https://immersive-web.github.io/webxr-samples/immersive-ar-session.html
And this? https://worldsdemolisher.totalviz.com/
What device, browser and browser version?

**Comment by chadlyalan** [comment]
They both look fine until I click AR and enter AR mode. Then it's just the camera with nothing going on.
Pixel 3 android 12
Brave 1.40.106
Also on Chrome 103

**Comment by De-Panther** [comment]
I don't know if brave supports webxr.
Samsung Internet supports, if you can install on pixel 3.
If the sample from the webxr samples site doesn't work on chrome android, report about it in the chromium bug tracker https://bugs.chromium.org/p/chromium/issues/list

maybe an issue on your phone? I'm with chrome 102 on Galaxy S10e and it works fine

**Comment by chadlyalan** [comment]
Thanks for the help. Even on Chrome it's not working so I'll give samsung a shot and probably submit a bug. Thanks!
