### ISSUE TITLE
OpenXR Emulation

### ISSUE THREAD

**Issue by Sythelux** [De-Panther/unity-webxr-export#216]
Heya,

I'm currently Prototyping a WebXR Application in Unity 2021.3.0f1.
For some reason the build time takes very long. ~~For that reason I was wondering if I can somehow convince the Unity Editor to take the OpenXR Input from my Headset and emulate WebXR Input for playing in Editor.~~

I figured the issue was, that Active Input Handling was set to Input System Package. I changed it to both.

Now this is a feature request, on what could be done to make this plugin Input System compatible?

**Comment by De-Panther** [comment]
There's a work in progress support for Unity XR SDK that should also handle this.
But until then, maybe there's a way to support the input system (I guess the new input system?) without the XR SDK support.
I'm not familiar with it, but you are welcome to investigate and have a Pull Request if you managed to add support.

Join the WebXR Discord if you want to talk about it - https://discord.gg/webxr

**Comment by De-Panther** [comment]
The naming of this issue was confusing.
WebXR Export now supports Unity Input System - #313
With that, it's possible to use XR Interaction Toolkit Simulation, or OpenXR in editor and emulation.
There are some tweaks needed for emulation to work.
