### ISSUE TITLE
Sometimes it looses track 

### ISSUE THREAD

**Issue by nsmith1024** [De-Panther/unity-webxr-export#219]
Hello,

I'm looking at your demo on my phone, it seems it looses track of where to place the object very often, and the gameobjects (the blue platform) keeps jumping from place to place instead of staying in a fixed position.

I dont know if its my phone or what. I thought maybe it was too dark inside so i tried it outside in broad daylight, but still the same thing.

Anybody knows if that will be fixed or am i doing something wrong?

Thanks

**Comment by De-Panther** [comment]
The AR demo?
Once you enter AR mode, there's a white box that hits surfaces, tap on the screen to anchor it, and the blue platform will stay in place

**Comment by nsmith1024** [comment]
Yes you are correct, it does work, thanks!
