### ISSUE TITLE
Desert sample missing from repo

### ISSUE THREAD

**Issue by nsmith1024** [De-Panther/unity-webxr-export#221]
Hello,

I was trying to get your desert sample scene, but when i clone or download the zip file from github, there are no samples in there.

Would you please let us know where to find the desert sample?

Or, are there any Unity  samples with source code we can look at, i dont see any in the repo or the zip file.

Thanks

**Comment by De-Panther** [comment]
It's in the WebXR Interactions package.
Just read the getting started and the other docs.
If you still need to clone the repo, use symlink.
And read the readmes and the docs.
https://github.com/De-Panther/unity-webxr-export#-compatibility
