### ISSUE TITLE
UI button presses dont seem to work in AR mode

### ISSUE THREAD

**Issue by nsmith1024** [De-Panther/unity-webxr-export#222]
Hello,

I cant get UI button presses to work in AR mode? 

I have some UI buttons on a Screen Space overlay canvas, sometimes when i click some of them dont work when AR is turned on.

Is there something special i have to do?

To test out the UI in AR i clicked on the live link at 

https://github.com/De-Panther/WebXR-Unity-Samples

the live demo link works  on my phone, but when i compile it and load that into the browser it gives an error:

 "UnityLoader is not defined"

using Unity 2020.3.32f1

Thanks

**Comment by nsmith1024** [comment]
UPDATE:

I fixed the UnityLoader missing problem by updating the WebGL template. Apparently some smarty pants changed how the parser works and gummed everything up. See this link.

https://forum.unity.com/threads/webgl-build-not-working-correctly-unityloader-is-not-defined.976938/

After fixing that, next, seems the demo at this link where the UI button clicked was working

https://github.com/De-Panther/WebXR-Unity-Samples

seems to use an old version of the WebXRexporter, so i updated the WebXRExporter dependency to use the latest version, after doing that the UI button clicks are not working in AR mode anymore.

So im back to square one. Oh Well!!!

**Comment by De-Panther** [comment]
As is written in the getting started guide, use the WebXR2020 WebGLTemplates for Unity versions 2020 and up.

The Samples in the repo you mentioned are now old and are only for VR.

To support Unity's UI Canvas you'll have to update the `Camera.projectionMatrix` of the camera that is used for raycasting UI events.
Screen Space overlay shouldn't have issues, but if it does, use a disabled camera with updated `Camera.projectionMatrix` for raycasting UI events.
You can get the correct `Camera.projectionMatrix` from the left AR Camera (`CameraARL`).
