### ISSUE TITLE
Firefox on application load: Module.WebXR.onUnityLoaded is not a function

### ISSUE THREAD

**Issue by rauwebieten** [De-Panther/unity-webxr-export#223]
I have this exception, but only when my application is running in an unfocused tab in firefox (firefox 100.0.2 (64-bits)).
When the unity is running in the active tab, all goes well.

In google chrome this exception does not occur.

    TypeError: Module.WebXR.onUnityLoaded is not a function
    _InitXRSharedArray@http://localhost:62367/Build/Build.framework.js.gz:1119:21003

**Comment by De-Panther** [comment]
Couldn't reproduce in Firefox 101.0 (64-bits)
