### ISSUE TITLE
Missing a way to get WebXRController buttons' "touched" value

### ISSUE THREAD

**Issue by widrye** [De-Panther/unity-webxr-export#224]
Hello,

I believe there is currently no way to access the "touched" value of WebXRController, à la XR.
Something akin to `InputDevice.TryGetFeatureValue(CommonUsages.thumbTouch, out value)` would be a welcome addition to this package.

Thanks in advance for looking into it.

**Comment by De-Panther** [comment]
Thanks!
Added this.
Notice the note in the PR, regarding support on the Editor and other non-WebXR platforms.
