### ISSUE TITLE
Example using React?

### ISSUE THREAD

**Issue by DaveXR** [De-Panther/unity-webxr-export#228]
I'm using this repo as well as this React enabler: https://github.com/jeffreylanters/react-unity-webgl

I've gotten stuck on some messaging. Wondering if anyone else has mashed webXR and React this way, might have some sample code?

**Comment by De-Panther** [comment]
Closing as I see you got help on discord

**Comment by learning-github-zgy** [comment]
> Closing as I see you got help on discord

l have the same question, how to use it in react? l need help, thanks

**Comment by learning-github-zgy** [comment]
> I'm using this repo as well as this React enabler: https://github.com/jeffreylanters/react-unity-webgl
> 
> I've gotten stuck on some messaging. Wondering if anyone else has mashed webXR and React this way, might have some sample code?

can you solve it? l have the same question, thanks
