### ISSUE TITLE
Cant Access WebXRManager

### ISSUE THREAD

**Issue by nsmith1024** [De-Panther/unity-webxr-export#229]
Hello,

Im trying to use your desert demo in Unity, but it seems i cant access the WebXRManager class, or any other class inside your package.

I keep getting an error that says class not found, even though its right there i can double click on the class i the project and open it with Visual Studio editor.

For example in the SceneHitTest.cs file, you access the WebXRManager, but if i create a new C# file and try to do the same thing, i get an error, it doesnt even recognize. See this, i try to create a new class in the same namespace as done in SceneHitTest.cs, and make a new class name etc, but it doesnt work:

using UnityEngine;
namespace WebXR.Interactions {
    public class MyARController : ControllerBase {
          WebXRController leftController;   <<<<< error  WebXRController  - type or namespace could not be found
     .....
   }
}

Is there a tutorial on how to do it?

Thanks

**Comment by De-Panther** [comment]
Create asmdef at the folder of your script, and reference the WebXR asmdef in it.

**Comment by nsmith1024** [comment]
Hello, what is asmdef? Can you please tell me how to do it, thanks!

**Comment by De-Panther** [comment]
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by nsmith1024** [comment]
Maybe it would be a good idea to put that on the FRONT PAGE of the github, because not everybody knows about ASMDEF. 

I been trying to use this package literally for months and couldn't figure it out and GAVE UP until you told me about the ASMDEF. 

Also some demo code outside the package (other than the desert) would be REALLY HELPFUL. Its hard to know how to do things just from the raw API, AR itself is already hard to do, forcing ASMDEFS makes it worse. 

Also maybe another good idea is NOT to use ASMDEFS at all, just make it a regular package would make it easier to use. I mean packages made by other people, even unity themselves, dont force people to use ASMDEFS because many people dont know what that is and will just not use your package because they may think it dont work.

Just giving you some feedback based on what happened to me and from some of the comments.
