### ISSUE TITLE
Webgl template not work anymore

### ISSUE THREAD

**Issue by MarcoLavoro** [De-Panther/unity-webxr-export#230]
I tried to upgrade an old project that used the version 0.8.0-preview.
The vr button in the webgl template not work anymore
I also tried to create a new project but there is no wabgl template for webxr

Anyone can help?

**Comment by De-Panther** [comment]
Re-copy the templates 'windows/webxr/copy webgltemplates'
Use the relevant template for your Unity version
ends with 2020 for 2020 and up (2021, 2022...)
