### ISSUE TITLE
Error adding package: com.de-panther.webxr-input-profiles-loader@0.4.0.

### ISSUE THREAD

**Issue by ugurberkecan** [De-Panther/unity-webxr-export#233]
When I try to install webxr package I am getting this error.

https://pasteboard.co/BLGUI9dsE936.png

**Comment by De-Panther** [comment]
You need to add the scoped registry of gLTFast

**Comment by De-Panther** [comment]
As it has been some time since I commented here, I guess you figured out how to add `com.atteneder` to the OpenUPM registry scope.
Similar to:
https://github.com/De-Panther/unity-webxr-export/blob/76fca3581e642d54a95d65b80f7553305e3a6f89/MainProject/Packages/manifest.json#L8
