### ISSUE TITLE
brotli compression firefox error

### ISSUE THREAD

**Issue by Tripl3Design** [De-Panther/unity-webxr-export#234]
When I try to build the webXR demo with brotli compression and no fallback (Unity 2021.3.8f1), firefoxs failed to build the game.
I think it it's not related to the project but a general Unity bug.

[demo with brotli compression](https://furnitise.nl/webXR/)
[issuetracker](https://issuetracker.unity3d.com/issues/brotli-compressed-build-fails-to-run-in-firefox)

**Comment by De-Panther** [comment]
Firefox/Unity bug, not related to this repo
