### ISSUE TITLE
Unable to determine status using 'WebXrState'

### ISSUE THREAD

**Issue by gnguo** [De-Panther/unity-webxr-export#237]
I want to use the WebXrState enum value to check if the place I am currently playing is a web browser or a vr device.

When Mozilla's WebXR Exporter project, which is the basis of this project, was used, it worked normally to get WebXRState values per browser/vr mode.(Attach a photo)
![WebStateTest_Mozilla](https://user-images.githubusercontent.com/76513106/194458075-d44942df-63cf-4b8b-8f5b-216d61539b01.png)

However, when a 'WebXR state' value is received in this project, only one state value is displayed regardless of whether it is in vr mode (for example, only the NORMAL).
![WebStateTest_W3C](https://user-images.githubusercontent.com/76513106/194458070-1e367139-1bed-4f35-8198-66f843a1611a.png)

The code used in the test is

`        
        private WebXRState xrState = WebXRState.NORMAL;

        public Text text;

        private void Update()
        {
            text.text = xrState.ToString();
        }

`

Thank you for reading it I want you to tell me what I missed.

**Comment by gnguo** [comment]
> I want to use the WebXrState enum value to check if the place I am currently playing is a web browser or a vr device.
> 
> When Mozilla's WebXR Exporter project, which is the basis of this project, was used, it worked normally to get WebXRState values per browser/vr mode.(Attach a photo) ![WebStateTest_Mozilla](https://user-images.githubusercontent.com/76513106/194458075-d44942df-63cf-4b8b-8f5b-216d61539b01.png)
> 
> However, when a 'WebXR state' value is received in this project, only one state value is displayed regardless of whether it is in vr mode (for example, only the NORMAL). ![WebStateTest_W3C](https://user-images.githubusercontent.com/76513106/194458070-1e367139-1bed-4f35-8198-66f843a1611a.png)
> 
> The code used in the test is ` private WebXRState xrState = WebXRState.NORMAL;
> 
> ```
>     public Text text;
> 
>     private void Update()
>     {
>         text.text = xrState.ToString();
>     }
> ```
> 
> `
> 
> Thank you for reading it I want you to tell me what I missed.

**Comment by De-Panther** [comment]
Use the WebXRManager...

https://github.com/De-Panther/unity-webxr-export/blob/76fca3581e642d54a95d65b80f7553305e3a6f89/Packages/webxr/Runtime/Scripts/WebXRManager.cs#L18

https://github.com/De-Panther/unity-webxr-export/blob/76fca3581e642d54a95d65b80f7553305e3a6f89/Packages/webxr/Runtime/Scripts/WebXRManager.cs#L26

**Comment by gnguo** [comment]
Thanks for the reply!


I've tried it, too

        text.text = WebXRManager.Instance.*XRState*.ToString();

But it doesn't working...

-------------------

It runs normally when using the same enum type of 'visibilitystate'.

        text.text = WebXRManager.Instance.*visibilityState*.ToString();

After creating a new project, I followed the guide(
https://de-panther.github.io/unity-webxr-export/) and tried again, but the
same problem repeatedly.

this project unity Editor version : 2020.3.21


The sentence might be weird because I am not good at English😢. But I'm not
a robot. Please reply. Thank you.

2022년 10월 7일 (금) 오후 12:46, De-Panther ***@***.***>님이 작성:

**Comment by gnguo** [comment]
I sent it separately because I couldn't see the picture attached to the
mail.

2022년 10월 7일 (금) 오후 1:57, ᅭᅭ ***@***.***>님이 작성:

**Comment by De-Panther** [comment]
Did you try WebXRManager.Instance.XRState on web?
Also, use OnXRChange

**Comment by gnguo** [comment]
Thank you for your reply! I tried it again,
OnXRChange works within a web browser!  Thanks to you, I solved it Thank
you for sharing a good project😂

2022년 10월 7일 (금) 오후 2:07, De-Panther ***@***.***>님이 작성:
