### ISSUE TITLE
WEBGL ERROR

### ISSUE THREAD

**Issue by neizvedaniydag** [De-Panther/unity-webxr-export#238]
Webgl displays this error on a mobile device, but everything works fine on a PC
![IMG_1681](https://user-images.githubusercontent.com/62785983/194710545-96d82bc3-4c8d-46e5-8b89-0e7651ef2110.png)

**Comment by De-Panther** [comment]
There's no call to `dynCall_iii` in this package.
Looks like would be better to ask in the Unity WebGL forum.
https://forum.unity.com/forums/webgl.84/

You can try to debug it using emscripten `--profiling-funcs` option.
`PlayerSettings.WebGL.emscriptenArgs = "--profiling-funcs";`
https://medium.com/@depanther/unity-webgl-secrets-b6ddf214f1fd
