### ISSUE TITLE
WebAr interactions

### ISSUE THREAD

**Issue by neizvedaniydag** [De-Panther/unity-webxr-export#241]
Hi! I have a question about web ar. Is there an opportunity in your asset to interact with virtual ones in AR using real hands?

 Sorry for my English, I just use Google translator

**Comment by De-Panther** [comment]
If I understand your question, you are asking if the WebXR Hands module is supported in WebXR Export + AR mode?
Yes, it works on supported devices. Tested on Quest 2 with passthrough mode on and Hololens 2.
