### ISSUE TITLE
Thank you for your work on this. Got it to work but getting a Black Background.

### ISSUE THREAD

**Issue by vicodesigns** [De-Panther/unity-webxr-export#242]
Hello,

Go this up and running on one of my projects but while the model and the UI loads correctly I am getting Black for the color of the Background.  My model has a cast shadow on it and that is the only place I can see the background setting which is darkened by the shadow effect. 

Is there a setting that I am missing?

Thank you.

**Comment by De-Panther** [comment]
Thanks

Black background is a very vague description.
Black background of what? When? etc... Also, is the sample scene works for you with the same settings? Did you follow the getting started guide?
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md
