### ISSUE TITLE
VR/AR button not appearing on the desert demo...

### ISSUE THREAD

**Issue by quertenmont** [De-Panther/unity-webxr-export#243]
Hello,

When I build&run the desert demo,
I don't have the AR/VR buttons on the webpage, but only a "fullscreen" button.
See screenshot below...

![image](https://user-images.githubusercontent.com/4639944/205455001-645254e3-f833-42b4-8083-5e5a146abe18.png)

When I check the demo from the github build, I do see those buttons.
Could it be related to the fact I am using unity on linux (ubuntu 20.04) ?
I'd say, webxr and webgl are by essence independent of the OS, but could be that your plugin is not ?

Any other idea?
Thanks for helping,
Loic

**Comment by De-Panther** [comment]
Read the getting started guide
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md

**Comment by quertenmont** [comment]
Thanks, I am almost there...

But it looks like the variable were not replaced by value this time...
![image](https://user-images.githubusercontent.com/4639944/205456173-c073c771-d898-47c4-b38d-a61fc29b7881.png)

**Comment by De-Panther** [comment]
As written in the getting started guide, use the 2020 templates

**Comment by quertenmont** [comment]
Yes, I realised that...  sorry the documentation was unclear to me.
I am running unity 2021.3, so I thought I had to run the standard template, not the 2020 one.

Thanks for helping and sorry for the novice questions
Loic

**Comment by De-Panther** [comment]
No problem.
There's also the Unity channel at the WebXR Discord https://discord.gg/webxr
