### ISSUE TITLE
how to use it in react?

### ISSUE THREAD

**Issue by learning-github-zgy** [De-Panther/unity-webxr-export#244]
hello, recently l have the question, how can l use it in react? now l can only open the exported index.html to use webxr, but l want  to inset the webxr sence into the react? how can l do? thanks!

**Comment by De-Panther** [comment]
I don't know React, but I guess it won't be different than implementing other Unity WebGL instances.
Try asking in the WebXR Discord https://discord.gg/webxr
Or search the web on how to implement Unity WebGL in react.

**Comment by learning-github-zgy** [comment]
> I don't know React, but I guess it won't be different than implementing other Unity WebGL instances. Try asking in the WebXR Discord https://discord.gg/webxr Or search the web on how to implement Unity WebGL in react.

ok, thanks, l can implement the comman unity webgl instance, but the unity-webxr-export webgl include the webxr.js and other documents, the comman way can't do it.

**Comment by De-Panther** [comment]
There's no webxr.js in this package

**Comment by learning-github-zgy** [comment]
> There's no webxr.js in this package

sorry, l said it wrong, the unity-webxr-export webgl include the unityInstance.Module.WebXR.toggleAR(), as the picture, however the comman unity webgl instance didn't include the Module function, l can't call the webxr function, and can't into the  VR sence.
![image](https://user-images.githubusercontent.com/72602172/207582527-ec5a7727-1242-4302-91dd-b571bc3c4f12.png)

**Comment by De-Panther** [comment]
Well, I'm not familiar with react, I suggested to ask at the discord server, more devs are there, and it was asked there in the past.

**Comment by learning-github-zgy** [comment]
> Well, I'm not familiar with react, I suggested to ask at the discord server, more devs are there, and it was asked there in the past.

ok, thank you very much, l will try it.
