### ISSUE TITLE
Trouble enabling "AR mode"

### ISSUE THREAD

**Issue by SimonDarksideJ** [De-Panther/unity-webxr-export#245]
Digging into this awesome Unity plugin for creating WebXR builds, however, I'm unable to get "AR" view working.

The sample "Dessert" force switches to VR and even though it seems to be setup for AR too, the AR mode is not activatable (although showing as a greyed out option)

Any ideas?

**Comment by De-Panther** [comment]
Which device? Is the demo on github works on that device?

**Comment by SimonDarksideJ** [comment]
Tried on several devices using both Edge and Chrome, the result is always the same
![image](https://user-images.githubusercontent.com/1793042/211014669-1c3c41d7-02e0-42d9-bdce-5b5c720d9d01.png)
As you can see the AR button is greyed out and not usable, pressing VR goes into a stereoscopic VR view

**Comment by SimonDarksideJ** [comment]
Actually correction, VR mode takes it in to a dual camera view on mobile but there is no motion (aka cardboard).
Might try on Quest

**Comment by De-Panther** [comment]
Which device? Is the demo on github works on that device?

**Comment by SimonDarksideJ** [comment]
Using Android Mobiles, Huawei P30 and Samsun S22+

**Comment by De-Panther** [comment]
Is the demo on github works on those devices?
https://de-panther.github.io/unity-webxr-export/Build

Did you follow the Getting Started guide?
Are you using HTTPS server?

**Comment by SimonDarksideJ** [comment]
Interesting, the sample on that page does work so I must have missed something. I had gone through the getting started and using the sample provided in the package.  
Any suggestions to resolve it?

**Comment by De-Panther** [comment]
Are you using HTTPS server?

**Comment by SimonDarksideJ** [comment]
No I was just hosting using npm http-server

**Comment by De-Panther** [comment]
So use the HTTPS option of npm http-server

**Comment by SimonDarksideJ** [comment]
OK, yes, using https did resolve the issue.  Guessing that needs to be stated in the requirements.  Thanks for the help.

**Comment by De-Panther** [comment]
It's already mentioned since it was written.
Please follow the instructions better next time.
![image](https://user-images.githubusercontent.com/4749703/211021475-e731bc22-90b9-4a32-b9f6-c42a58604f96.png)

**Comment by SimonDarksideJ** [comment]
I would suggest updating that to be more clear.  Stating:

"To run Unity exported builds you need to publish the sample on a HTTPS server (**HTTP is not supported**).  HTTP only works for Unity's 'Build and run' method"

Simply making it specifically clear that HTTPS is required unless you are using Build and Run.

**Comment by De-Panther** [comment]
How is it more obvious than "Run the build on your own HTTPS server"?
If the getting started guide (which ment to be as short as possible, with minimum instructions), tells to "Run the build on your own HTTPS server", just do it :)

**Comment by De-Panther** [comment]
I updated the Getting Started page, hope now it's clearer
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md
And thanks for the feedback.

**Comment by SimonDarksideJ** [comment]
Thanks for the update

**Comment by snusharma** [comment]
Hi i have made a WebGL build with WebXR plugin. My problem is it does not work when i choose AR in browser as well as on device Could you please help me with it I am testing it in chrome browser and for AR i am testing it on device :
Details Error :
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at _JS_DOM_MapViewportCoordinateToElementLocalCoordinate (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:27466)
    at 04bf2efe:0x9fc9dd
    at 04bf2efe:0x99fec8
    at 52362a02-1928-4030-b2c0-cebf08c6b98b:1137:217673
    at Object.mouseEventHandlerFunc [as handlerFunc] (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:217709)
    at jsEventHandler (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:188085)
_JS_DOM_MapViewportCoordinateToElementLocalCoordinate @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
$func33655 @ 04bf2efe:0x9fc9dd
$ei @ 04bf2efe:0x99fec8
(anonymous) @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
mouseEventHandlerFunc @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
jsEventHandler @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
I am using unity 2021.3.16f1 LTS version
WebXR Expoter :0.16.1
WebXR Interaction : 0.16.3

**Comment by SimonDarksideJ** [comment]
Better to log a new issue @snusharma with replication instructions if you are having issues, this has long since been closed.
