### ISSUE TITLE
No VR Mode on Rift S

### ISSUE THREAD

**Issue by majortomL** [De-Panther/unity-webxr-export#255]
When switching to VR mode in my replica of the demo application you provide, I get the following error messages:

`WebGL: INVALID_FRAMEBUFFER_OPERATION: drawElements: Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback.`

`WebGL: INVALID_FRAMEBUFFER_OPERATION: drawArrays: Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback.`

`WebGL: INVALID_FRAMEBUFFER_OPERATION: clear: Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback.`

In fiddling around, I also tested your [demo app](https://de-panther.github.io/unity-webxr-export/Build), with the same problem. Is this device related, or has Oculus pushed updates that cause it? I tested both on chrome and edge, but nothing seems to help. Also restarted the oculus app and replugged the headset.

**Comment by De-Panther** [comment]
Oculus desktop app version 49 won't open WebXR.
In the app settings, you can opt in to the beta and get version 50 that should fix the issue

**Comment by majortomL** [comment]
Hey @De-Panther, thanks for the quick reply! Turns out I already **was** subscribed to public test channel, and still got that error. I tried to unsubscribe, and running the demo on version 49 displays the same error. Should I wait for an oculus app update,?

**Comment by De-Panther** [comment]
Were you on version 50 in the beta?
Are other WebXR samples works for you?
https://immersive-web.github.io/webxr-samples/

If not, report in the Oculus OpenXR forum about WebXR not working on version 50.
https://communityforums.atmeta.com/t5/OpenXR-Development/bd-p/dev-openxr

**Comment by majortomL** [comment]
The other samples you provided work for me on version 50 now. It's just the sample on your page, and stuff I created with your exporter...

**Comment by De-Panther** [comment]
Please try to close all browsers and tabs, and then try this demo:
https://de-panther.github.io/unity-webxr-export/Build

**Comment by majortomL** [comment]
Done on oculus app version 50.0.0.165.257, the error mentioned in the issue appears.

**Comment by De-Panther** [comment]
But did you see something on VR?
And as far as I know, those are not errors, but warnings that happen in a frame or two while waiting for VR.
Can you upload printscreens of your steps?

**Comment by majortomL** [comment]
Resolved by rebooting. Thanks so much for taking the time!

**Comment by majortomL** [comment]
...nevermind! The issue comes back. Your demo worked once, now it does not anymore...

**Comment by De-Panther** [comment]
Well, if it sometimes work and sometime don't it sounds like an issue with other parts of the system.
It can be the Oculus desktop app,
it can be the Oculus OpenXR runtime,
it can be the browser(s).

If you can share the steps that you do to get to this state, it would help to find the issue.

My guess is a number of WebXR sites open at the same time(there were reports of similar issues in the past).
See if you can make sure all browsers are closed, then open only one tab of a Chromium based browser and enter the demo. See if it can enter VR

**Comment by majortomL** [comment]
I will investigate this further and provide the background if it actually is caused by the exporter. Thanks for your help!

**Comment by majortomL** [comment]
Alright, I figured it out. Appears to have been a problem on my side, with XRTK I believe. Thanks for your time!
