### ISSUE TITLE
Disable body tracking

### ISSUE THREAD

**Issue by 253153** [De-Panther/unity-webxr-export#258]
Hi I have a static experience and don't need body tracking, for example for the camera to move up and down when you stand up and down. How do I disable this feature?
Thanks in advance!

**Comment by 253153** [comment]
Or at least how do we figure out how far away from the floor the camera should be?

**Comment by De-Panther** [comment]
I'm not sure about disabling body tracking, but if you want the pose of the player to start at the center of the rig, you can change the WebXR Settings (in project settings) the `VRRequiredReferenceSpace` to `local`.

The default for this package is `local_floor`.

More details can be found at https://developer.mozilla.org/en-US/docs/Web/API/XRReferenceSpace
