### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by wmd0701** [De-Panther/unity-webxr-export#259]
Hi dears, I am a WebXR learner and I am trying now the Unity WebXR demo ([this one](https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md)). My Unity version is `2021.3.21f1`, WebXR Interaction version `0.16.3-preview` (latest), WebXR Export version `0.16.0-preview` (latest). I follow the tutorials 100% step-by-step. The only thing that I am not sure is how to run the build on https server. What I do is simply build the project, and open the index.html in browser (just double-click). And what I get is then:

![image](https://user-images.githubusercontent.com/34072813/226699006-fa7ca05f-2283-4806-8b95-0cf93cbd5f11.png)

Nothing shows up in the webpage. I also tried to [import WebGL Publisher](https://learn.unity.com/tutorial/creating-and-publishing-webgl-builds#) but it doesnt help. What's wrong here? Any suggestions and ideas are appreciated, thanks!

**Comment by BryanChrisBrown** [comment]
I also recently ran into this issue in unity 2021, I was able to use unity 2019 properly though, I'm not sure what changed between versions that modified this.

**Comment by De-Panther** [comment]
Please read the getting started guide and select WebGLTemplate according to the Unity Editor version you are using.

Regarding HTTPS server, it's out of the scope of this repo, there are lots of different web servers with different configurations, and there's no one correct solution.
You can look for NodeJS, NGINX or any other server program that you can run locally.

**Comment by wmd0701** [comment]
> I also recently ran into this issue in unity 2021, I was able to use unity 2019 properly though, I'm not sure what changed between versions that modified this.

I guess they just never try their demos and tutorials on newer Unity version...

**Comment by wmd0701** [comment]
> Please read the getting started guide and select WebGLTemplate according to the Unity Editor version you are using.
> 
> Regarding HTTPS server, it's out of the scope of this repo, there are lots of different web servers with different configurations, and there's no one correct solution. You can look for NodeJS, NGINX or any other server program that you can run locally.

I have already read the getting started guide multiple times. As for WebGLTemplate, the lastest option is for Unity 2020.x. Actually there are four templates, I tried all of them, and neither of them works.

**Comment by De-Panther** [comment]
In the image you uploaded in the first post, it's clear that you are using a Unity 2019 template in a newer Unity Editor.

Also you should use HTTPS server. Opening the index file from your file explorer is not using HTTPS server.

If you insist on not following the guides, there's not much I can do to help you.

**Comment by wmd0701** [comment]
> In the image you uploaded in the first post, it's clear that you are using a Unity 2019 template in a newer Unity Editor. If you insist on not following the guides, there's not much I can do to help you.

Yes, in the screenshot I posted I was using a 2019 WebGLTemplate, but as I said in my last post today, all templates (see the image below) didnt work. I just put only one screenshot in my first post because I dont want to have multiple images explaining a same problem.

![Screenshot 2023-03-26 142240](https://user-images.githubusercontent.com/34072813/227775541-f7a0334f-c60b-4214-8852-0e7f65c6f2ca.png)

**Comment by De-Panther** [comment]
And you mentioned that you didn't use HTTPS server, to this I replied with some options for web servers, but you ignored that.
Instead you went for bashing the work with "I guess they just never try their demos and tutorials on newer Unity version...".

**Comment by wmd0701** [comment]
> And you mentioned that you didn't use HTTPS server, to this I replied with some options for web servers, but you ignored that. Instead you went for bashing the work with "I guess they just never try their demos and tutorials on newer Unity version...".

Sorry for this. I am indeed a noob on server setting, but I assume it is not a server issue, because I just installed an older version of Unity `2019.4.7f1` (the same version used in the tutorial) and tried the dessert scene, everything works fine. 

And I have to add something to what I have said: in the screenshot below, there are six WebGL templates. So far, on Unity `2021.3.21f1`, I tried all four templates with their names starting with "WebXR" (see image below), none of them work. Three ways I tried to run and build:   
- 1. `Build` in Unity, and then simply run the generated `index.html` with double-click left mouse button;
- 2. `Build` in Unity, and then run a simple server `python -m http.server --directory /name_of_your_build_directory/`, then access http://localhost:8000 in browser (sry I am truly a noob on server and I dont know how to access localhost using https); 
- 3. `Build and Run` in Unity;

Several mins ago I just tried the "Default" and the "Minimal" templates on Unity `2021.3.21f1`. They run well! And actually,they run well with `Build and Run` in Unity.

![Screenshot 2023-03-26 142240](https://user-images.githubusercontent.com/34072813/227779644-59ae8f12-b829-4784-85f9-0c2e3f61c671.png)

**Comment by wmd0701** [comment]
> > I also recently ran into this issue in unity 2021, I was able to use unity 2019 properly though, I'm not sure what changed between versions that modified this.
> 
> ~I guess they just never try their demos and tutorials on newer Unity version...~

Sorry I shouldnt have said that. Unity updates are really frequent and compatibility issues are quite common. Many thanks for your great work @De-Panther which realizes web VR implementation in Unity.
