### ISSUE TITLE
Feature request: look with mouse when not in VR

### ISSUE THREAD

**Issue by 253153** [De-Panther/unity-webxr-export#262]
The previous mozilla version of this project had a feature where if you aren't in a VR headset and are on a computer you can "look around" with the mouse by dragging. Is this feature disabled here or is there a way to bring it back?

**Comment by De-Panther** [comment]
It's not part of WebXR.
On flat mode you can have so many different options for controls...
Just create your own components, or use existing ones from other packages, and attach them to the rig or to the `CameraMain` depending on your use case.
