### ISSUE TITLE
Automatic return of 2D Input depending on Controller Type

### ISSUE THREAD

**Issue by majortomL** [De-Panther/unity-webxr-export#265]
Trying to implement a multi platform application, I want to retrieve 2D axis input from the controller. With Oculus Touch, this is the Thumbstick, but with e.g. HTC Vive, I would have to query the Touchpad. Is there a method that handles this whole "trouble" in your WebXRController script or elsewhere, which automatically returns the relevant 2D axis depending on the controller type used? If not, what are the possible values for the respective controller types that would be stored in the WebXRController.GetProfiles() return array?

**Comment by De-Panther** [comment]
Well, I think(not sure) that on the WebXR API you can query what axis are available.
But I don't think that we shared this in this package,
What you can do, is query both touchpad and thumbstick for value, and do something like

float x = touch.x == 0 ? thumb.x : touch.x;

And it'll return value from whatever has value

**Comment by majortomL** [comment]
Thanks, that's a great workaround! Maybe this is still a good feature to include in future releases, to increase platform independence?

**Comment by De-Panther** [comment]
Thanks for the suggestion. Not currently, but I'll think about it.
(Needs to figure out how to expose this info to developers in a way that would be similar to existing Unity APIs)
