### ISSUE TITLE
Resolution Increase when Zoom out to 33% on Chrome Tab

### ISSUE THREAD

**Issue by stephen-t-dodds** [De-Panther/unity-webxr-export#266]
If you take a look at this video you will see that when I load my Webxr experience initially it is high resolution. But when I click VR (using Immersive Web Emulator), the resolution goes way way down. I tested in Quest 2 headset and resolution drops there as well so I know it is not a simulator issue.

https://youtu.be/s7ne7XJRbz0

What you will see halfway through the video is that I zoom out on the chrome tab to about 33% zoom, refresh the screen, and then click VR. You will notice the resolution is now normal/high and rendering in VR mode.

I tried a million things to get the resolution higher, and I am not sure at all what got me even to think of trying this, but this is the only thing that actually worked to improve the resolution. 

Does anyone have any idea why this works and if there is a way to implement this in the source code? I know you are not able to control the actual zoom of the web page, but maybe there is some sort of part of the code base that is forcing the resolution lower that we can turn off?

The resolution difference in the video is easiest to tell when you look at the white arrow at the beginning and end. The beginning it is very pixelated and at the end it is normal.

**Comment by De-Panther** [comment]
I guess it's related to how Unity handles window.devicePixelRatio

There should be a WebXR API that allows to control the resolution on the device, I think we wanted to implement it in the past and weren't sure what would be the right way

**Comment by De-Panther** [comment]
I think the related issue is #80

**Comment by stephen-t-dodds** [comment]
Yes, I saw that issue raised and I tried changing getNativeFramebufferScaleFactor in a few different places, but did not see any changes in resolution so I am not sure if I made the change in the right place. Where do you suggest forcing this number to be 2 or higher? Like which file to change it in I mean.

**Comment by De-Panther** [comment]
In the `webxr.jspre`.
But maybe it's not something that you'll see affected in the emulator.
You can try this sample with the emulator: https://immersive-web.github.io/webxr-samples/framebuffer-scaling.html

**Comment by stephen-t-dodds** [comment]
Hmmm in the emulator it seems that each value has the same resolution which is decent resolution. But I will try to locate webxr.jspre and adjust it with my project and see if I see a difference.

**Comment by stephen-t-dodds** [comment]
Is this location in webxr.jspre a reasonable spot to place it?

Module['WebXR'].OnStartVR = function (views_count, left_rect, right_rect) {
  Module.WebXR.isInXR = true;
  Module.dynCall_viffffffff(Module.WebXR.onStartVRPtr, views_count,
                          left_rect.x, left_rect.y, left_rect.w, left_rect.h,
                          right_rect.x, right_rect.y, right_rect.w, right_rect.h);
  setFramebufferScaleFactor(2);
}

**Comment by stephen-t-dodds** [comment]
Wow! So, even using your https://immersive-web.github.io/webxr-samples/framebuffer-scaling.html
If I zoom out to 33% and then run in VR the resolution increases by like 400%. So I am not sure the pixelratio is the issue.

**Comment by stephen-t-dodds** [comment]
![Lowres](https://user-images.githubusercontent.com/8052989/229944476-07852a23-f0ea-4fcb-8c00-d22e81eacb83.png)
This is low res with normal 100% zoom before clicking VR

![Highres](https://user-images.githubusercontent.com/8052989/229944541-91c99187-7f77-4b66-b33c-7cce70945eab.png)
This is high res with 33% zoom before clicking VR

**Comment by De-Panther** [comment]
I'm not sure if the emulator is a good tool to test the actual behavior, as it runs in the page.
You'll have to test it on the actual device

**Comment by stephen-t-dodds** [comment]
Looks like the zoom out does not work in the headset browser to improve resolution.

**Comment by De-Panther** [comment]
If you connect your headset to PC,
open this demo on Chrome Desktop https://de-panther.github.io/unity-webxr-export/Build/
enter WebXR VR mode,
and change the zoom level.

Does it change the quality in the headset?
