### ISSUE TITLE
Live Demo on iOS

### ISSUE THREAD

**Issue by victoralvarezfs** [De-Panther/unity-webxr-export#267]
Hi, 
I'm using the De-Panther web exporter on my unity webgl project. And it works fine on desktop, quest and android browsers. But I still can't figure out how to make it run on my iOS browser. I'm asking this, because I've run your "Live Demo" on my iPhone X device and it worked perfect. Could you please give me some help if I'm missing any configuration on my Unity project to get my build running on iOS? Currently the error I'm receiving on my iOS browser is the following:

RuntimeError: Out of bounds memory access (evaluating 'dynCall_ii(index,a1)')
<?>.wasm-function[21422]@[wasm code]
<?>.wasm-function[23682]@[wasm code]
<?>.wasm-function[15763]@[wasm code]
wasm-stub@[native code]
invoke_ii@https://userfs.github.io/newnoneEnableExceptions/Build/NoneBuild.framework.js:1137:352331
<?>.wasm-function[15763]@[wasm code]
<?>.wasm-function[5736]@[wasm code]
<?>.wasm-function[637]@[wasm code]
<?>.wasm-function[11455]@[wasm code]
<?>.wasm-function[1940]@[wasm code]
<?>.wasm-function[25783]@[wasm code]
wasm-stub@[native code]
invoke_iii@https://userfs.github.io/newnoneEnableExceptions/Build/NoneBuild.framework.js:1137:351482
<?>.wasm-function[25783]@[wasm code]
<?>.wasm-function[1055]@[wasm code]
<?>.wasm-function[11941]@[wasm code]
<?>.wasm-function[7428]@[wasm code]
<?>.wasm-function[430]@[wasm code]
<?>.wasm-function[429]@[wasm code]
<?>.wasm-function[17572]@[wasm code]
<?>.wasm-function[9732]@[wasm code]
<?>.wasm-function[2614]@[wasm code]
<?>.wasm-function[1867]@[wasm code]
<?>.wasm-function[12815]@[wasm code]
<?>.wasm-function[6010]@[wasm code]
<?>.wasm-function[24914]@[wasm code]
<?>.wasm-function[36668]@[wasm code]
<?>.wasm-function[6735]@[wasm code]
<?>.wasm-function[25782]@[wasm code]
wasm-stub@[native code]
invoke_iiii@https://userfs.github.io/newnoneEnableExceptions/Build/NoneBuild.framework.js:1137:351996
<?>.wasm-function[25782]@[wasm code]
<?>.wasm-function[1241]@[wasm code]
<?>.wasm-function[16401]@[wasm code]
<?>.wasm-function[9513]@[wasm code]
<?>.wasm-function[9282]@[wasm code]
<?>.wasm-function[13176]@[wasm code]
<?>.wasm-function[8383]@[wasm code]
<?>.wasm-function[1649]@[wasm code]
<?>.wasm-function[28401]@[wasm code]
<?>.wasm-function[15819]@[wasm code]
<?>.wasm-function[6105]@[wasm code]
<?>.wasm-function[6104]@[wasm code]
<?>.wasm-function[29565]@[wasm code]
<?>.wasm-function[13679]@[wasm code]
<?>.wasm-function[13678]@[wasm code]
<?>.wasm-function[13219]@[wasm code]
<?>.wasm-function[25793]@

**Comment by De-Panther** [comment]
Out of bounds usually refers to memory issue.
I guess your issue is more relevant to a general Unity WebGL, and not specific to the WebXR Export.
Try to ask at the Unity WebGL forum
