### ISSUE TITLE
VR / AR Button grey on Oculus Browser

### ISSUE THREAD

**Issue by hugodigio** [De-Panther/unity-webxr-export#269]
Hi all !

I have a problem with my build. I tryed to build the sample scene on my server to work with Oculus/Meta Browser on my Meta Quest.
But when I try to open page on my headset, the VR Button to enter VR stay grey. 
On chrome on my desktop, it's working normally !

When I try the sample available on the README.md of this repo, it's work well. I don't know what I make wrong !

I implement the library on Unity 2022.2.13.
I disable Gzip compression.
I use WebXR Template for 2020.

**Comment by De-Panther** [comment]
Use HTTPS server
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md

**Comment by hugodigio** [comment]
thank you for your fast response ! my server is an HTTPS server, that's why I can't see what's wrong!
There is a link to my current testing build:
https://octarina.com/WIP/WebVR/

**Comment by De-Panther** [comment]
2 of the experiences works for me

**Comment by hugodigio** [comment]
I try to remake my project entierly, remake all steps and it's always the same:
- Work on Chrome
- Don't Work on Meta Browser into my headset ....

I really have no idea to explore :( 

![com oculus shellenv-20230512-174714](https://github.com/De-Panther/unity-webxr-export/assets/23705152/85b1ffc9-ccc5-45bb-9232-cb52ffd6e7b9)

**Comment by De-Panther** [comment]
The legacy, vr2 and uncompressed works for me

**Comment by hugodigio** [comment]
yes on my browser yes, but not on Meta Quest (WEBVR2 and uncompressed don't work on my headset :( ). Do you/can you try on Meta Quest Headset ? (native, not with Quest Link) I actually trying to downgrade my project to 2020.3

**Comment by hugodigio** [comment]
same on 2020.3.47f1 ...
I really don't know what I missed.

-> import WebXR Export+ WebXR Interactions from OpenUPM
-> import Desert Sample
-> Make Desert Scene Default
-> Switch project to WebGL
-> disable Gzip Compression
-> check WebXR Export in XR-Plugin Management, in WebGL tab
-> Import WebGL Template
-> Select WebGL 2020 Template
-> Build
![image](https://github.com/De-Panther/unity-webxr-export/assets/23705152/5b8b6d37-0ab3-4d3d-9d5f-bce1f0a72e25)
-> Transfer it on HTTPS server ...
https://octarina.com/WIP/WebVR/WebVR2020.3.47/

Don't work on my Oculus Quest 1 on Browser ...
Frustating to be stuck like that ...
![webXrFail](https://github.com/De-Panther/unity-webxr-export/assets/23705152/bbaab545-89e1-4594-b237-5d55d0eb34e0)

**Comment by De-Panther** [comment]
Did you try to connect it to chrome dev tools?
Anything strange in the console log?

**Comment by hugodigio** [comment]
I can't open Chrome dev tools on my Quest, but I think I can use Adb to catch embedded Logs of Meta Quest Browser, I will try

**Comment by De-Panther** [comment]
The desktop chrome should be able to connect to the Quest browser. Same as any other Chromium based browser on android devices

**Comment by hugodigio** [comment]
yes ! I just reading that on meta documentation ! It's really usefull ! 
there is my Logs :
![image](https://github.com/De-Panther/unity-webxr-export/assets/23705152/910980c3-21cf-4fef-a543-4bab344784bb)

I don't understand why he make a warning about HTTPS / localhost while I am on a https server ?

**Comment by De-Panther** [comment]
Seems like your server use both http and https. And instead of forwarding to https, it stays on http.
edit the url to https.
You can see at the last line that it loads the data from http

**Comment by hugodigio** [comment]
Ok ... i found the error ... I feel like a big Idiot ...
I wrote on the URL field:
"octarina.com/WIP/WebVR/WebVR2022.3.47/" with the keyboard of the headset... by default Meta Browser don't use https but http... I add https:// at start of my URL and it's working ....

really feel idiot right now  ...

**Comment by hugodigio** [comment]
Why this limitation of HTTPS ? 
WebXR standard ? or Meta standard ?

**Comment by hugodigio** [comment]
thank you very much for helping me despite my clumsiness... I wasted your time
