### ISSUE TITLE
Any way to manually disable the Template's VR button, or cancel changing to VR?

### ISSUE THREAD

**Issue by JBerubeSS** [De-Panther/unity-webxr-export#271]
Hello,

I am making a game that has both VR controls and Keyboard/Mouse control options. Due to the nature of this, I would like to be able disable the option to go into VR once they have confirmed Keyboard/Mouse controls, preferably through disabling the VR button in the template.  Is there a way to do this? If not, then is it possible to catch when the user is attempting to go into VR once they have confirmed Keyboard/Mouse, and cancel that action?

**Comment by De-Panther** [comment]
You can edit the template

**Comment by JBerubeSS** [comment]
I have found a way to disable the VR button mid-game, so I am closing this.
