### ISSUE TITLE
 'SubsystemRegistration' does not exist in the current context

### ISSUE THREAD

**Issue by lsqnet79** [De-Panther/unity-webxr-export#275]
Hi I got this missing SubsystemRegistration after I install from package Manager from 
https://openupm.com/packages/com.de-panther.webxr/

Works ok in Unity 2020 version 
with this Errors on Unity 2021 version

Library\PackageCache\com.de-panther.webxr@0.16.0-preview\Runtime\XRPlugin\WebXRSubsystem.cs(19,17): error CS0103: The name 'SubsystemRegistration' does not exist in the current context

**Comment by De-Panther** [comment]
There's a PR that would fix that. for now you can use an older version of com.unity.xr.management
it started on 4.3.1
so a version before that

**Comment by lsqnet79** [comment]
Yes I got it worker by lowering to 4.21 but now the inpit profiles unable to load 
![err](https://github.com/De-Panther/unity-webxr-export/assets/95261128/50e1d991-21b0-4ff5-a668-e82d6cacc6d6)

**Comment by De-Panther** [comment]
That is not related to lowering the version. you have missing dependencies.
Look at the WebXR Input Profiles repo for details
https://github.com/De-Panther/webxr-input-profiles-loader

**Comment by lsqnet79** [comment]
Yes you are right because your website didnt provide the correct link 
https://openupm.com/packages/com.de-panther.webxr/

**Comment by De-Panther** [comment]
What link it didn't provided?

**Comment by lsqnet79** [comment]
com.atteneder

**Comment by De-Panther** [comment]
Why should it be referenced in unrelated package page?
for the WebXR Export package there's no need for this scope, and the Input Profile Loader package is not mentioned there.

The scope is mentioned both at
https://openupm.com/packages/com.de-panther.webxr-interactions/
and at
https://openupm.com/packages/com.de-panther.webxr-input-profiles-loader/

Just make sure to go over instructions next time
