### ISSUE TITLE
Hand Tracking in Unity editor 

### ISSUE THREAD

**Issue by lsqnet79** [De-Panther/unity-webxr-export#277]
Hi De-Panther 

So far I only seem the hands only appear in the oculus device meta browser, Is the a way to integrad the hands manually to the unity editor or preload from gltf loader?

**Comment by De-Panther** [comment]
In versions 0.19.0 support for XR Interaction Toolkit and the new Input System was added. Including Hands Tracking support.
Using the XRI Sample from the WebXR Interactions sample, and Unity's OpenXR package, then enabling OpenXR on desktop in the editor, would enable you to use Hand Tracking in the editor as well.

**Comment by De-Panther** [comment]
And a relevant video tutorial https://youtu.be/NDlc11CgnQM
