### ISSUE TITLE
Unity 2021.3.16f1 LTS WebXR WebGL AR Issue 

### ISSUE THREAD

**Issue by snusharma** [De-Panther/unity-webxr-export#279]
Hi i have made a WebGL build with WebXR plugin. My problem is it does not work when i choose AR in browser as well as on device Could you please help me with it I am testing it in chrome browser and for AR i am testing it on device :
Details Error :
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
at _JS_DOM_MapViewportCoordinateToElementLocalCoordinate (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:27466)
at 04bf2efe:0x9fc9dd
at 04bf2efe:0x99fec8
at 52362a02-1928-4030-b2c0-cebf08c6b98b:1137:217673
at Object.mouseEventHandlerFunc [as handlerFunc] (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:217709)
at jsEventHandler (52362a02-1928-4030-b2c0-cebf08c6b98b:1137:188085)
_JS_DOM_MapViewportCoordinateToElementLocalCoordinate @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
$func33655 @ 04bf2efe:0x9fc9dd
$ei @ 04bf2efe:0x99fec8
(anonymous) @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
mouseEventHandlerFunc @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
jsEventHandler @ 52362a02-1928-4030-b2c0-cebf08c6b98b:1137
I am using unity 2021.3.16f1 LTS version
WebXR Expoter :0.16.1
WebXR Interaction : 0.16.3

**Comment by De-Panther** [comment]
I tested it on devices with 2021.3.17, and I don't get this error.

Regarding emulators, you didn't specify which one, but I guess it's the Firefox/Mozilla one, which didn't get an update for a long time. It does some changes to the `canvas` element in the page, that doesn't happen on the device.
In that case, it should be fixed on the emulator.

If it really happen on the device (maybe you have another error on the device?), maybe you are using a custom WebGLTemplate with no `id="unity-canvas"` property for the unity canvas.

**Comment by snusharma** [comment]
Details : 
Unity Version : 2021.3.16f1 LTS
WebXR Expoter :0.16.1
WebXR Interaction : 0.16.3
Chrome bowser :Version 114.0.5735.110 (Official Build) (64-bit)
Packages taken from :https://openupm.com/packages/com.de-panther.webxr/
How I am testing: 
I am using XAMPP and putting the build file in htdocs and then running it, i haven't VR as well on the actual device but when i click on AR i am getting this error. and not able to place the AR Object in the scene.
**If any change is required to be done please let me know how to do it so that i can do it and get the project working** 

![PM](https://github.com/De-Panther/unity-webxr-export/assets/125341419/55b8f4a4-b329-47b4-bb27-2b60e47376e2)

![WebGlTemp](https://github.com/De-Panther/unity-webxr-export/assets/125341419/416ec7dc-4526-47b2-ba87-c58c0fcafb0f)

**Comment by De-Panther** [comment]
Can you share a screen capture of the error in the device?

**Comment by snusharma** [comment]
I am not able to place the AR Content, It does not shows me any error on the device
Link to test it on browser : https://snusharma.github.io/WebXRUnity/
https://github.com/De-Panther/unity-webxr-export/assets/125341419/9298c6c7-43cb-4580-99ee-3f2d1f2beb2d

**Comment by De-Panther** [comment]
So you have 2 different issues.
1. Error on old emulator.
2. Scene doesn't display on AR mode.

Regarding 1. It's an old emulator. Testing with the immersive web emulator, I don't get this error - https://github.com/meta-quest/immersive-web-emulator

Regarding 2. my guess is that you are using Linear Color Space, go to the Player Settings, and change Color Space to Gamma.

And in general, I suggest first to try and build the basic sample, as described in the getting started guide, and see if it works, before doing changes and adding/removing stuff from the sample scene.

**Comment by snusharma** [comment]
Okay, Let me check this and i will update you on this as soon as i finish testing the steps that you have mentioned here

**Comment by snusharma** [comment]
I got the project working by the steps that you've mentioned her but the thing is i am not able to place the AR content where i want to.. It's like just showing me the Model/Object in the scene. Could you please help me regarding that

**Comment by De-Panther** [comment]
Sounds like a new issue.
You are welcome to open a new issue with all the needed info. Also better to ask help in the discord, and keep the issues in the repo for bugs.

**Comment by snusharma** [comment]
Okay, I ll create a new bug for this
