### ISSUE TITLE
Keyboard inputs blocked

### ISSUE THREAD

**Issue by ulkpro** [De-Panther/unity-webxr-export#281]
I edited the the index.html of the WEBXR build to include 2 textboxes and a search button. So that, once the search button is clicked, values entered in the 2 textboxes will be communicated to a unity game object, and in the C# scripts, I manipulate this data as per project requirements.
Issue is, I cannot type anything in the 2 textboxes. Anything typed doesn't appear. Seems like typing is blocked from somewhere. No other overriding scripts also. Am I doing something wrong ?
Search buttons and script is as below

```
<div id="navigation-panel" style="position: fixed; top: 20px; right: 20px;">
  <input type="text" id="latitude-input" placeholder="Latitude" style="display: block; margin-bottom: 10px;" />
  <input type="text" id="longitude-input" placeholder="Longitude" style="display: block;" />
  <button id="search-button">Search</button>
</div>
```

```
<script>
    var searchButton = document.getElementById("search-button");
    searchButton.addEventListener("click", function () {
    var latitudeInput = document.getElementById("latitude-input");
    var longitudeInput = document.getElementById("longitude-input");
    var latitude = parseFloat(latitudeInput.value);
    var longitude = parseFloat(longitudeInput.value);
	sendCoordinatesToUnity(latitude, longitude);
  });
  
  // Function to send longitude and latitude values to Unity
  function sendCoordinatesToUnity(latitude, longitude) {
    var params = {
      latitude: latitude,
      longitude: longitude
    };
    var paramsJSON = JSON.stringify(params);
    unityInstance.SendMessage("GameManager", "jsSetMap", paramsJSON);
  }
    </script>
```
![WEBXR_Keyboard](https://github.com/De-Panther/unity-webxr-export/assets/31757133/ee5f1ec3-d7df-41ae-a9e8-c58ea2d3117b)

**Comment by De-Panther** [comment]
That's Unity WebGL issue.
Ask in the relevant forum
https://forum.unity.com/forums/webgl.84/
Or check Unity manual.

I remember there's a parameter in Unity to allow this.
