### ISSUE TITLE
Pico 4 support

### ISSUE THREAD

**Issue by smitdylan2001** [De-Panther/unity-webxr-export#283]
I tested the demo scene on the pico 4 and it worked great. Pico 3 runs the same OS and base specs (just lower clocks), so expect that to run as well.
The fps was around 55, so not sure if that's a lot lower than expected.

Might be good info to add to the readme under supported devices, as pico is used a ton in b2b applications. 
Can do more testing if needed, just link a build

**Comment by De-Panther** [comment]
Thanks.
On which device are the 55 FPS?
Is it using the demo scene hosted in this repo, or is it using your own build?

**Comment by smitdylan2001** [comment]
> Thanks. On which device are the 55 FPS? Is it using the demo scene hosted in this repo, or is it using your own build?

My bad, I had the spectator cam enabled. Without it the fps is around 72!

I tested on pico 4 (consumer edition), I can try on pico 3 link on another day when I'm at the office

I used the demo hosted in this repo

**Comment by De-Panther** [comment]
Great!
I'll add Pico 4 to the list.
What do they call the default browser in Pico 4?

**Comment by smitdylan2001** [comment]
It's just called PICO Browser

**Comment by De-Panther** [comment]
Thanks
