### ISSUE TITLE
The transparent_bg.jslib clears my UI canvas, how can I redraw it?

### ISSUE THREAD

**Issue by marcusx2** [De-Panther/unity-webxr-export#286]
Title says it all, the transparent_bg.jslib is clearing stuff it shouldn't. Only happens on iPhone. How can I redraw after it was cleared?

**Comment by De-Panther** [comment]
Are you using URP or Built-in RP?

**Comment by De-Panther** [comment]
And try to attach it to a camera. if it's for mobile AR, the CameraARL

**Comment by De-Panther** [comment]
Also provide more data, like Unity version, packages versions, etc... I can't guess those

**Comment by marcusx2** [comment]
Solved I think. Thanks!

**Comment by De-Panther** [comment]
How?

**Comment by marcusx2** [comment]
It's completely unrelated to this plugin, sorry for the false alarm
