### ISSUE TITLE
WebXRController class can't be referenced to handle input

### ISSUE THREAD

**Issue by hugodigio** [De-Panther/unity-webxr-export#293]
Hi,
I'm trying to use webXR input in my script to handle UI interaction, but I can't make reference to a WebXRController script caused by assembly definition (I guess), we can't use WebXR namespace in any script (`using WebXR;` for example don't work) 

For example, I tried to Import in my project @De-Panther 's ControllerInputModule.cs from his [WebXR-Unity-Samples](https://github.com/De-Panther/WebXR-Unity-Samples/) repository but have some reference problems. 
`ControllerInputModule.cs(8,7): error CS0246: The type or namespace name 'WebXR' could not be found (are you missing a using directive or an assembly reference?)
ControllerInputModule.cs(12,10): error CS0246: The type or namespace name 'WebXRController' could not be found (are you missing a using directive or an assembly reference?)`
[screenshot of errors in visual code](https://freeimage.host/i/HsLmAMX)

I feel we can't handle input anymore for now.

**Comment by De-Panther** [comment]
Just use assembly definition and assembly reference as the error suggest
