### ISSUE TITLE
Are there anyway we could get XR controller for browser in VR headset out of immersive mode?

### ISSUE THREAD

**Issue by Thaina** [De-Panther/unity-webxr-export#296]
I wish I could just use your XR controller in oculus as a joystick even outside of immersive mode. And if I understand correctly it seem that the code in this project are not reading any input before session started?

Are there anyway possible, or do we need to always start inline session?

I am starting to add inline session code into the project, but another approach is to use InputSystem along with some code in original mozilla webxr repo. Which would be better?

**Comment by De-Panther** [comment]
Inline session is not relevant.
The XR controllers are active only on XR.

**Comment by Thaina** [comment]
I have test the code in oculus browser and it not report any value until I press VR or AR button

But I want the system to work even before I got into immersive mode

One way I have see it was possible is to always start session as inline, I am trying to test this idea. Are there any other way though?

**Comment by De-Panther** [comment]
As I wrote, inline session is not relevant.
It was used in the past and dropped.
The specs and the devices don't enable the controllers before entering XR sessions.

**Comment by Thaina** [comment]
> The specs and the devices don't enable the controllers before entering XR sessions.

What? That would be completely absurd decision. There are many webgl 2D game people would like to use VR controller, how that would possible?

**Comment by De-Panther** [comment]
If it's in a browser in a VR device, the controller acts like a mouse/touch input

**Comment by Thaina** [comment]
Yes, but then the thumbstick are completely useless?
