### ISSUE TITLE
Trouble to enable AR button in Edge browser

### ISSUE THREAD

**Issue by mkpark-VIRNECT** [De-Panther/unity-webxr-export#299]
Hello, I'm making web xr collaboration applicatioin with unity webxr export and Mirror network engine.
I having a issue about AR session with MS Edge browser.
When i open web page i built with webxr export in edge browser in hololens2, VR button does enabled and work, but AR button is not enabled, and even i try to enter [WebXR page](https://immersive-web.github.io/webxr-samples/immersive-ar-session.html) page, browser said, "AR NOT FOUND". 
and when i try with my android phone, in Edge browser even doesn't enabled VR mode too, but works fine in Chrome or other browser

**To Reproduce**
1. Try enter web xr page with Edge browser ( hololens2, android )

**Expected behavior**
AR button enable and can use immersive AR 

I know it would be Edge browser's problem but i just wonder is there any other way to use WebAR in HL2. 
Thanks for reading.

**Comment by De-Panther** [comment]
As you wrote, it's Edge issue.
You can ask about it in the WebXR Discord https://discord.gg/webxr
I think the last known Edge version to work was 109. Maybe there's a way to download older versions, but I don't know where. Again, better ask on the WebXR Discord.

You can see others complaining about it around the net...
https://learn.microsoft.com/en-us/answers/questions/1293414/unable-to-use-any-webxr-ar-app-on-ms-edge
