### ISSUE TITLE
Spectator camera doesn't work well with URP material 

### ISSUE THREAD

**Issue by CHRISLAUSC** [De-Panther/unity-webxr-export#300]
**Describe the bug**
 The camera of spectator view  appear in the oculus device after convert the pink material to URP.

**To Reproduce**
1. Open a new unity project with 3D URP scene.
2. Then import all the WEBXR stuffs from OpenURM.
4. Build and Run.

**Expected behavior**
It seems like you've encountered an issue while building a desert scene in 3D using Universal Render Pipeline (URP) for VR. When you created a simple 3D scene with standard materials, it worked fine. However, when attempting to create a desert scene with URP, the spectator view  appear inside in the Oculus device not in the browser.

**Screenshots**

Spectator camera Settings with URP 
<img width="370" alt="Screenshot 2023-07-24 232038" src="https://github.com/De-Panther/unity-webxr-export/assets/138863305/8fa17c03-f5ac-4592-90be-f3fd3730c604">

Spectator camera Settings with Standard Material (Working)
<img width="392" alt="Screenshot 2023-07-24 232126" src="https://github.com/De-Panther/unity-webxr-export/assets/138863305/5c58d63d-4e7a-4353-add2-74bee17bc7dc">

**Unity info (please complete the following information):**
- Editor version:                             Unity 2021.3.18f
- WebXR package version:             0.161
- WebXR Interactions version:       0.163
- Git or OpenUPM:                        OpenURM

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows 10]          Window 11 
 - Browser: [e.g. Chrome 104]                   Tested on both Edge and Chrome

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1]                   Meta Quest Pro
 - OS: [e.g. Meta Quest build 55.0]           Build 55 
 

**Additional context**

**Comment by De-Panther** [comment]
Fixed now that we moved to URP only.
Apparently the URP uses another method for pre rendering, so instead of `OnPreRender()` was needed to register to `RenderPipelineManager.beginCameraRendering`.

Fixed in versions 0.20.0.
