### ISSUE TITLE
nothing appear when switching AR mode

### ISSUE THREAD

**Issue by hugodigio** [De-Panther/unity-webxr-export#302]
I try to build desert's sample scene and open it with Google Chrome app on my phone.
When I switch to VR mode, it's works (cardboard stereoscopic view)
But when I try to switch into AR mode, I don't see desert scene, I just see what my phone camera see.

What I do:
- import @De-Panther unity-webxr-export packages
- enable WebXE plugin
- import WebXR Templates
- build desert sample scene with WebXRFullView2020 Template
- send build to my HTTPS server.

Does something more to do to start AR session and see my scene ?

my configuration:
- Samsung Galaxy S20 FE 5G
- Google Chrome app
- build on https server

**Comment by hugodigio** [comment]
there is a link to my last try:
https://octarina.com/WIP/Framatome/hugoar/

**Comment by De-Panther** [comment]
Next time, please use the bug report template.

My guess is that you are using URP or Linear Color Space. Try using Gamma color space (in the player settings)

**Comment by hugodigio** [comment]
Thx for your quick answer !

Sorry for bad usage.

yes I'm in URP  AND in Linear gamme space.
But my project need to work in URP :/ 

So I switch color space to Gamma and now it's works even with URP! 
I will make some tries but it's seems to work normally 👍  

thx again !
