### ISSUE TITLE
Builds not loading in browser, always getting 400 code

### ISSUE THREAD

**Issue by DewilLucas** [De-Panther/unity-webxr-export#305]
When I make a build of the WEBXR webgltemplate, it keeps giving me

%UNITY_WEBGL_LOADER_URL%:1     
Failed to load resource: the server responded with a status of 400 (Bad Request)
127.0.0.1/:22  Uncaught SyntaxError: Unexpected token 'var'

In the browser, tested it on multiple browsers, it keeps giving this, and I can't test my application because of this....

I've followed every step of the video I found on youtube.

**Comment by De-Panther** [comment]
1. There are templates for issues in this repo.
They are there to help the writer and the readers to describe all the details needed.

2. You are using the wrong WebGL Template.
Follow the steps in the getting started doc.
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md


For general help it's better to ask in the WebXR Discord server in the Unity channel.
https://discord.gg/webxr
