### ISSUE TITLE
WebAR Screenshoot

### ISSUE THREAD

**Issue by andresgutierrez17** [De-Panther/unity-webxr-export#308]
I am using the hit test AR, and I want to take a screenshot but the webcam is not in the screenshot, the image background is black.

**Comment by De-Panther** [comment]
The WebXR API doesn't allow this by default.
There's the WebXR Raw Camera Access module that can allow that, but is currently not implemented in WebXR Export
https://github.com/immersive-web/raw-camera-access/blob/main/explainer.md
https://immersive-web.github.io/raw-camera-access/
