### ISSUE TITLE
Hit Test doesn't access camera in Iphone

### ISSUE THREAD

**Issue by EmmaNaty** [De-Panther/unity-webxr-export#309]
Hi, I used the dessert scene as base an delete everething but the WebXRCameraAet in order to use the hitTest in AR and in Android whne I hit the AR button of the WebGL template it asks for camera permissions an then asks for Google Play AR services to update and it works finw, but in iphone devices it doesn't ask for camera permissions or anithyng else so it looks like:

![image](https://github.com/De-Panther/unity-webxr-export/assets/15250658/d912a04d-d076-400d-a8cb-12e2d6d29a3f)

**Comment by EmmaNaty** [comment]
Checki with the original template the AR button nevers enables when running on an Iphone, is not supported by any means?

![image](https://github.com/De-Panther/unity-webxr-export/assets/15250658/07910582-4834-4849-9511-be8ab7853ebd)

**Comment by andresgutierrez17** [comment]
Hello, for IOS is needed install the XRViewer browser and open the URL there. Safari does not have WebXR support!
