### ISSUE TITLE
mobile ar support

### ISSUE THREAD

**Issue by chaoslife** [De-Panther/unity-webxr-export#32]
Hello, does it support WebAR on iOS and Android or future?

**Comment by De-Panther** [comment]
Currently it supports the Immersive AR session of WebXR. So it works on browsers that supports it.
Chrome 81 for Android supports it - Needs a device that supports ARCore.
iOS doesn't support the Immersive AR session as far as I know.
Magic Leap Helio browser supports it, but it doesn't recognize the controller.

Also, I didn't implement yet a support for touch events, and didn't implement Hit-Test.

You can see how it currently works at:
https://de-panther.github.io/unity-webxr-export

**Comment by chaoslife** [comment]
Okay, Thanks a lot!
