### ISSUE TITLE
30fps on oculus quest 2 browser with URP

### ISSUE THREAD

**Issue by Gianluca-C90** [De-Panther/unity-webxr-export#326]
first of all thanks for the amazing work De-Panther. without you our project wouldnt be working at all, but now we are strugglin so hard with this weird behaviour, in oculus browser with a bare bone scene with almost zero objects we cant pass 30 fps, its like something is capping at 30. what am i missing ? in your demo i see it clearly at 90, im going nuts!
please shed some lights for me!

**Headset**
Oculus quest 2
Oculus quest 3

**Comment by De-Panther** [comment]
I can't help with no info.
Please use the proper bug template.

**Comment by Gianluca-C90** [comment]
ok let me do it in a min
