### ISSUE TITLE
capped at 30 fps in oculus browser

### ISSUE THREAD

**Issue by Gianluca-C90** [De-Panther/unity-webxr-export#327]
**Describe the bug**
a minimal scene in URP runs at 30 fps on the oculus browser with some sporadic spikes above that, but its objectively locked to 30 frame rate

**To Reproduce**
1. Build a simple scene in URP with webxr exporter
2. host it on a server
3. reach the link from the oculus browser
4. look at developer hub performances

**Expected behavior**
we are using framevr as benchmark and they can totally nail a 60fps stable

**Screenshots**

**Unity info (please complete the following information):**
- Editor version: 2021.3.27f1
- WebXR package version: 0.18
- WebXR Interactions version: 0.18
- Git or OpenUPM: OpenUpm

**Desktop (please complete the following information):**
 - OS + Version: windows 11
 - Browser: Chrome 119 

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1]
 - OS: [e.g. Meta Quest build 55.0]
 - Browser: [e.g. Meta Quest Browser 20.0]

**Smartphone (please complete the following information):**
 - Device: Oculus quest 2 and 3
 - OS: Android 12
 - Browser: Oculus Browser

**Additional context**
we are using also VRTK

**Comment by De-Panther** [comment]
On other reports you mentioned the use of URP.
I guess you tried to build the desert sample.
Is it the same with the built-in render pipeline?

Unity is not built from ground up for web, so there's a need for lots of optimizations for it to work well.
Better check profiler and other performance tools, to see if it's CPU bound or GPU bound, and see what can be optimized.

**Comment by Gianluca-C90** [comment]
thanks sir, i will run some tests with your suggestions, and then i'll come back here reporting what i've discovered.
