### ISSUE TITLE
Request Feature: Fullscreen Browser

### ISSUE THREAD

**Issue by voblinggit** [De-Panther/unity-webxr-export#33]
Currently, I can't use the Unity WebXR Plugin because of performance issue in the Oculus Quest but your tweak plugin is very smooth in the device. Very cool and awesome. 

It would be great if there would be a full screen button for browser. 
I did some tweaks as I only know the basics, but it seems creating this fullscreen is not simple. What I encounter is that, whenever I change the size of the desktop browser to a fullscreen, the screen size in the Oculus Quest doesn't run properly.

### (Not a good tweak as the VR in Oculus Quest is out of place)
The simple tweak I used is to force the browser stretched:
In html.index...
script> unityContainer.onclick = function() { unityContainer.requestPointerLock(); } </script

changed the code in html.index....
div id="unityContainer" style="width: %UNITY_WIDTH%px; height: %UNITY_HEIGHT%px"></div
into...
div id="unityContainer"></div"

and then add the width and height in style.css
.webgl-content {background-color: #ffffff; width: 100%; height: 100%; position: absolute; top: 50%; left: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%); }

**Comment by De-Panther** [comment]
When you say fullscreen, you want the real fullscreen option, or just stretch it like you did using CSS?

Regarding the CSS stretch way:
There's an issue with using style width/height 100% as each frame the browser would change the canvas view. And that would require you to edit the webxr.js animate function, to update the size of the canvas in each frame, instead of just when the onSessionStarted is called.
What you can do, is register to the window resize event, and then update both the style width/height of the canvas in pixels, and it's component width height. But I'm not sure how it'll work, it's just a guess.

**Comment by voblinggit** [comment]
The real fullscreen option might do if its faster enough to implement.

I am researching a simple full screen as maybe its fast enough, so far, no progress.
About the CSS, it seems that's very complicated.

**Comment by De-Panther** [comment]
Why complicated? tested now:

On style.css, replace the first .webgl-content .footer line with:
```
.webgl-content .footer {position: fixed; width: 100%; bottom: 0; margin-top: 5px; height: 38px; line-height: 38px; font-family: Helvetica, Verdana, Arial, sans-serif; font-size: 18px;}
```

On index.html, both div elements of "webgl-content" and "unityContainer" should have style="width: 100%; height: 100%".

You might want to also edit webxr.js:
onEndSession, replace canvas.width/height with
```
this.canvas.width = this.canvas.parentElement.clientWidth * window.devicePixelRatio;
this.canvas.height = this.canvas.parentElement.clientHeight * window.devicePixelRatio;
```
and you might need to add to animate after let glLayer = session.renderState.baseLayer:
```
if (this.canvas.width != glLayer.framebufferWidth ||
    this.canvas.height != glLayer.framebufferHeight) {
  this.canvas.width = glLayer.framebufferWidth;
  this.canvas.height = glLayer.framebufferHeight;
}
```

Maybe I'll add a WebGLTemplate with those changes

**Comment by De-Panther** [comment]
Added WebGLTemplate for WebXRFullView.

Tested on Chrome, Chrome for Android and Firefox.
Firefox has an issue that when changing the window size while in VR, the XRWebGLLayer size would change, so the VR view size would also change (would look more pixelate when scaling down the window).

**Comment by De-Panther** [comment]
@voblinggit did you got to check this with the new template?
