### ISSUE TITLE
Bug: "TypeError: Module._malloc is not a function" when entering VR mode

### ISSUE THREAD

**Issue by Quriz** [De-Panther/unity-webxr-export#345]
**Describe the bug**
When entering VR mode in the built XR Interaction Toolkit sample, the following error occurs and prevents the app from continuing to run:
```
TypeError: Module._malloc is not a function
    at Module.WebXR.OnInputProfiles (build.framework.js.gz:1250:26)
    at XRManager.animate (build.framework.js.gz:1115:33)
    at Object.tempRaf [as callback] (build.framework.js.gz:1001:32)
    at XRSession$1.<computed>.onDeviceFrame (<anonymous>:1281:42)
```
```js
Module['WebXR'].OnInputProfiles = function(input_profiles) {
    var strBufferSize = lengthBytesUTF8(input_profiles) + 1;
    var strBuffer = Module._malloc(strBufferSize); // <-- Error occurs here
    stringToUTF8(input_profiles, strBuffer, strBufferSize);
    Module.dynCall_vi(Module.WebXR.onInputProfilesPtr, strBuffer);
    Module._free(strBuffer);
}
```

**To Reproduce**
1. Import and configure the project with the XR Interaction Toolkit Sample.
2. Build & Run
3. Enter VR mode
4. See error in browser console

**Expected behavior**
Should enter VR mode successfully.

**Unity info (please complete the following information):**
- Editor version: 2023.2.1f1
- WebXR package version: 0.21.0
- WebXR Interactions version: 0.21.0
- WebXR Input Profiles Loader version : 0.6.2
- Git or OpenUPM: OpenUPM
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Input System + XR Interaction Toolkit
- Built-in render pipeline or URP: URP

**Desktop (please complete the following information):**
 - OS + Version: Windows 10
 - Browser: Chromium 120.0.6099.199 and Firefox 121.0.1

**Comment by De-Panther** [comment]
I never tried it on Unity 2023.2.

For now, you can use Unity 2022.3.

I'll test it on 2023.2 later.

**Comment by octopus8** [comment]
By opening up `ProjectSettings/ProjectSettings.asset` and setting `webGLEmscriptenArgs: -s EXPORTED_FUNCTIONS="['_malloc', '_main', '_free']"`, I was able to get past that error and get the "Desert" scene to start in VR, but still not quite right. It renders the full scene to the right eye, but only the background to the left.

**Comment by De-Panther** [comment]
Seems like I just need to use `_malloc` and `_free` without `Module.`. I guess they are already in the scope of the method.
I'll need to test if it works on older Unity versions.

**Comment by De-Panther** [comment]
> Seems like I just need to use `_malloc` and `_free` without `Module.`. I guess they are already in the scope of the method. I'll need to test if it works on older Unity versions.

And it works. I'll open PR
