### ISSUE TITLE
Touch input mobile

### ISSUE THREAD

**Issue by Yuro97** [De-Panther/unity-webxr-export#349]
Hello,

First of all, congratulations on the splendid work you've done; it's amazing! 

My request is regarding an implementation in case it's not already present. I tried to use Input.touchCount once the project was exported, but it doesn't work in AR mode. Is there already a way to use the device's touch? If it doesn't exist yet, it would be a very interesting feature.

Nevertheless, it's still a very useful plugin; congratulations!

Thank you in advance for the response.

Yuri Biasi

**Comment by De-Panther** [comment]
It should work on AR mode on mobile phones.
You should be able to test it with both demos in the repo.

**Comment by De-Panther** [comment]
Closing as there's no reply.
If there's a bug, please open a new issue using the bug report template.

**Comment by EddieBorbon** [comment]
The demos for Augmented Reality don't work for me
