### ISSUE TITLE
Adding Post-process Layer creates a weird fisheye effect

### ISSUE THREAD

**Issue by zer0grand** [De-Panther/unity-webxr-export#35]
Not sure if it's a user error, but I'm trying to use anti-aliasing on my left/right cameras, and placing a post-process layer on the camera (without any effects applied to it) will create some crazy zoom in fisheye effect.

To recreate: Apply a post-process layer to the CameraL/CameraR GameObjects in the WebXRCameraSet prefab.

BTW this repo is freaking awesome, thank you so much for making this.

**Comment by De-Panther** [comment]
Thanks :)

And interesting.
I won't recommend adding any post-process to WebGL.
But when you create the WebGL context, there's "antialias" WebGLContextAttributes.
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getContextAttributes
I think that by default it's false.
You can check webxr.jspre in the Assets/WebXR/Plugins folder, where we set xrCompatible to true, you can try and add antialias true as well.
Please update if it worked.

Also, which browser did you try?

**Comment by De-Panther** [comment]
Another option that might help you, is setting LayerInit attributes for the XRWebGLLayer.
It has options for antialias and framebufferScaleFactor.

You can check Framebuffer Scaling here:
https://immersive-web.github.io/webxr-samples/framebuffer-scaling.html

In webxr.js, when calling updateRenderState you can add those attributes.

**Comment by zer0grand** [comment]
Cool thanks! Also I was using Firefox.

**Comment by De-Panther** [comment]
Did you tried one of those options? Did it help?

**Comment by zer0grand** [comment]
I tried the first one and it didn't work. I took a look at the second one and the immersive-web link showed no difference on my headset when sliding the bar around... Then I saw https://developer.mozilla.org/en-US/docs/Web/API/XRSession/updateRenderState where it says that Firefox unfortunately doesn't support updateRenderState. (I'm using Firefox with an original Vive- for some reason Chrome XR doesn't work for me) 😢 While I wanted antialiasing I also wanted a bunch of other post-processing effects, so I'm thinking of keeping it closed if it's not recommended. If you find a way though please let me know!

**Comment by De-Panther** [comment]
To run WebXR on Chrome, you'll need to make sure that it isn't running (not even on background on Task Manager), and run it with the commands "--no-sandbox --test-type". You'll might want to set the #webxr-runtime flag in the Chrome flags, to select which headset to use.

I won't recommend post-processing for optimization reasons:
As far as I know, only part of the general Unity post-processing effects are available for VR.
As this is not an official Unity extension, it doesn't have some optimizations that official ones have (e.g. single pass rendering).
Then there's WebGL and post-processing, as WebGL runs slower than native OpenGL equivalent, as it has some overhead for some of the GL calls for security reasons.

BUT you still can try and use some of them. As long as you manage to keep the recommended frame rate for each headset, that's what matters.
