### ISSUE TITLE
Change "WebXR Export requires Gamma Color Space" to a warning and not an error.

### ISSUE THREAD

**Issue by ibytergj** [De-Panther/unity-webxr-export#356]
With Linear color space enabled vs Gamma, I can do a build and the WebGL can load in a browser if uploaded to a server, If I try to do a build and run so that Unity can spin up a temporary server, this error will cause the build to fail. This makes it harder to test the code.

**Comment by De-Panther** [comment]
1. Error shouldn't stop Unity from build. Check your editor settings.
2. I don't see a reason for color space to affect if build works on a server or not.
3. Please use the bug report template, lots of missing info in this post, the details asked in the bug report might help.

**Comment by ibytergj** [comment]
Thank you for the reply. I am not sure what Editor settings would affect this. 

I am able to do a build but not build and run.

It is the code LogError I believe that causes the build and run to fail. 

I did not feel this was a bug as it seems to be working as you intended. 

If linear may or may not cause issues then I would view that as something issue a warning about and not an error. 

I tried this in a brand new project and get the same result.

Perhaps you might try to recreate the issue?

**Comment by De-Panther** [comment]
This is why there's the bug report template, it has all the details to re-create.

The Unity console has some settings on how to react to error messages, one of those might stop the process.

**Comment by De-Panther** [comment]
Is "Error Pause" selected in your editor Console?
There are number of bugs with the combination of WebXR and Linear color space right now so I see this as an error.
And developers will notice an error message more than a warning.

**Comment by ibytergj** [comment]
Thanks for changing this for the short term. Your plan to support a configurable option is a great choice.
