### ISSUE TITLE
Microsoft Mixed Reality with WebXR

### ISSUE THREAD

**Issue by Noranius** [De-Panther/unity-webxr-export#358]
**Describe the bug**
I tried our Microsoft Mixed Reality headset on one example page [https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/](https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/). The VR Button is not clickable. Mixed Reality Portal is up and running. Desktop VR application work properly.

After starting the website directly from the Mixed Reality Portal, it is possible to click on the VR button. However, after confirming the access to the VR Headset, nothing happens.

**To Reproduce**
1. Attach Microsoft Mixed Reality headset to the computer
2. visit [https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/](https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/) 
3. VR Button is greyed out

**Expected behavior**
Displaying the demo in the headset

**Screenshots**
![image_2024-02-15_103746889](https://github.com/De-Panther/unity-webxr-export/assets/29037766/57c347b7-4506-4374-8d50-ca896e8b07ab)

**Unity info (please complete the following information):**
provided example from [https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/](https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: [Firefox 122.0.1, Edge 121.0]

**Headset (please complete the following information):**
 - Device: Asus MR
 - OS: OpenXR for Windows Mixed Reality 113.2402, Asus Windows Mixed Reality Headset 1.2.7
 - Browser: see above

**Comment by De-Panther** [comment]
Firefox on desktop used to support WebVR and could run WebXR using polyfill, but they dropped the support for both.
Try Chrome or Edge.

**Comment by Noranius** [comment]
Thank you for the fast answer. As written above I've tried it with Edge as well with the same problem.

**Comment by De-Panther** [comment]
Are there other tabs with WebXR open?
Try https://immersive-web.github.io/webxr-samples/controller-state.html
Is it working on your device?

**Comment by Noranius** [comment]
I can click on the Enter VR Button, but then it's shaking and greyed out. After a second or so it is clickable again. The permission for Virtual Reality is given.

**Comment by De-Panther** [comment]
So it seems like your device has issues with the OpenXR runtime

**Comment by Noranius** [comment]
I assume the same. We will try it with another device. I close this for now. If the problem persists with the other device, I'll get in touch again. Many thanks.

**Comment by De-Panther** [comment]
Microsoft are dropping the support for Windows Mixed Reality.
But maybe the SteamVR for WMR still works, so you might be able to use it and set SteamVR as your OpenXR runtime. Maybe that will work.
