### ISSUE TITLE
LogError in OnPostProcessAllAssets preventing build

### ISSUE THREAD

**Issue by bnco-dev** [De-Panther/unity-webxr-export#361]
**Describe the bug**
Building for Windows while the plugin is in the project fails if color space is not linear or render pipeline is not URP.

**To Reproduce**
1. Import com.de-panther.webxr
2. Attempt Windows build, get undefined errors (see screenshots)
3. Move com.de-panther.webxr into Packages folder to allow editing
4. Comment out LogErrors (lines 88-96 of WebXRBuildProcessor.cs in com.de-panther.webxr 0.21.1-preview)
5. Attempt build again, it works!

**Expected behavior**
Warn user but allow build to continue. Ideally, don't even warn user if build does not use WebXR (f.ex. a desktop build).

**Screenshots**
Note that the packages error messages are good and clear, but for some reason Unity does not print them. Instead it's just "2 errors".
![image](https://github.com/De-Panther/unity-webxr-export/assets/33021110/3dae0f54-550c-4320-89de-0ba4593a1c7e)

**Unity info (please complete the following information):**
- Editor version: 2022.3.14f1
- WebXR package version: 0.21.1-preview
- WebXR Interactions version: N/A
- Git or OpenUPM: Git
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: N/A
- Built-in render pipeline or URP: Built-in

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows 10] Win 11
 - Browser: [e.g. Chrome 104] N/A

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1] N/A
 - OS: [e.g. Meta Quest build 55.0] N/A
 - Browser: [e.g. Meta Quest Browser 2 0.0] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6] N/A
 - OS: [e.g. Android 12] N/A
 - Browser: [e.g. Chrome 104] N/A

**Additional context**
None.

**Comment by bnco-dev** [comment]
I see this is similar to #356. I'm not sure why Unity is failing on these LogErrors. Everything I've been able to find online suggests this should only happen if the BuildOptions.StrictMode flag is present. I can't find that anywhere in my project.

**Comment by De-Panther** [comment]
Thanks for the report. It shouldn't happen on other platforms build.
