### ISSUE TITLE
UI Canvas doesn't showed when it is configured as [Screen Space - Camera/Screen Space - Overlay] in AR mode (Android)

### ISSUE THREAD

**Issue by jesuscfp** [De-Panther/unity-webxr-export#363]
The Canvas is not showed when the render mode is configured as Screen Space - Camera or Screen Space - Overlay using the AR mode. If the render mode is configured as Screen Space - World Space then the Canvas is showed. From the Web Browser, everything is showed correctly. With the sample scene (Desert Example) the behaviour is wrong as well.

**Steps to reproduce the behavior:**
1. Go to Canvas
2. Set the render mode as _Screen Space - Camera_ or _Screen Space - Overlay_ adding a semi-transparent Panel as children.
3. Build project
4. Check that it is showed in Browser but not in AR mode.

**Unity info:**
- Editor version: 2021.3.15
- WebXR Export version: 0.21.0
- WebXR Interactions version: 0.21.0
- Git or OpenUPM:
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit:
- URP is used.

**Smartphone:**
 - OS Device: Android 11
 - Browser: Chrome 121

**Comment by De-Panther** [comment]
Can't reproduce, missing details in your post.

Can you upload the project to github?

Screen Space Camera should work with smartphone AR.
Need to make sure it reference the correct camera, and need to make sure the plane distance is larger than the near distance plane of the camera.

**Comment by jesuscfp** [comment]
> Can't reproduce, missing details in your post.
> 
> Can you upload the project to github?
> 
> Screen Space Camera should work with smartphone AR. Need to make sure it reference the correct camera, and need to make sure the plane distance is larger than the near distance plane of the camera.

Hi, thank you for the response.

Definetly, it has been a mine mistake. I took the sample desert scene using the same Canvas, which is added in WebXRModesNotifier and hidden when you leave the Normal state.

Sorry for the confusion and thanks again.
