### ISSUE TITLE
Streching of the view and no stereo vision

### ISSUE THREAD

**Issue by kimdt27** [De-Panther/unity-webxr-export#366]
I'm seeing an issue, where the whole camera FOV is stretched, and won't show stereo view.
The same happens in VR and AR in the quest 3 browser.
This is with a clean project in unity 2022.3.21 with only the export and interactions packages installed.
![billede](https://github.com/De-Panther/unity-webxr-export/assets/10096840/4646f758-4610-47d8-8e0c-98da045bc4a8)
Is this a bug, or is there a fix for it?

**Comment by De-Panther** [comment]
1. For bugs there's a bug form, it has all the relevant info we need to help solve the issue.
2. It happened to someone at the discord few days ago. Closing Unity, cleaning browser cache and building the project again somehow helped.

I'm closing the issue, as it doesn't use the bugs form. If it continues, please open an issue using the form.

**Comment by De-Panther** [comment]
Managed to replicate. Opened bug issue https://github.com/De-Panther/unity-webxr-export/issues/367
There's a comment there on how to go around this issue for now
