### ISSUE TITLE
Left and Right camera in Quest 2 look like missed allign and VR effect is broken.

### ISSUE THREAD

**Issue by AmalinTasnim** [De-Panther/unity-webxr-export#368]
**Describe the bug**
Left and Right camera in Oculus Quest 2 look like missed allign and VR effect is broken, if close one eye it show different view left eye and right eye. Its look like the stereo not function. I am using Unity 2022.3.12f1.

**To Reproduce**
1. Create a new Unity Project 2022.3.12f1. Switch platform to WebGL.
2. Import WebXR Export and WebXR Interaction Toolkit sample packages from OpenUPM.
3. Enter XR mode in headset.
4. Left and Right camera in headset look like missed allign and VR effect is broken, if close one eye it show different view Left eye and Right eye. Its look like we only can see Right and Left view without front view in headset.

**Expected behavior**
Expected to see the same view for both eyes and stereo.

**Screenshots**
This is the sample of what we see in the headset
![Screenshot 2024-03-27 081826](https://github.com/De-Panther/unity-webxr-export/assets/94503937/c11a6a9c-7498-4f05-9328-75f1749ae0f3)

**Unity info (please complete the following information):**
- Editor version: Unity 2022.3.12f1
- WebXR package version: 0.22.0
- WebXR Interactions version: 0.22.0
- Git or OpenUPM: OpenUPM
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Input System + XR Interaction Toolkit
- Built-in render pipeline or URP: Built-in render pipeline

**Desktop (please complete the following information):**
 - OS + Version: Windows 11
 - Browser: Chrome 123

**Headset (please complete the following information):**
 - Device: Meta Quest 2
 - OS: [e.g. Meta Quest build 55.0]
 - Browser:Meta Quest Browser

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any

**Additional context**
![Screenshot 2024-03-27 101307](https://github.com/De-Panther/unity-webxr-export/assets/94503937/b59dc1d3-3026-442e-8034-a407cf5d56a4)

**Comment by De-Panther** [comment]
Can you share screenshots from the headset and the the main camera in the hierarchy?
Also, any errors/warnings on build?
Or any warnings/errors in the console of Chrome DevTools?

**Comment by De-Panther** [comment]
Also what sample did you use? There are 4

**Comment by AmalinTasnim** [comment]
I used this sample, XR Interaction Toolkit
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Using-XR-Interaction-Toolkit.md

**Comment by AmalinTasnim** [comment]
![Screenshot 2024-03-27 103816](https://github.com/De-Panther/unity-webxr-export/assets/94503937/7a0f42db-ddb0-4b9d-a186-3d0792a6f230)

**Comment by De-Panther** [comment]
There are 2 XR Interactions Samples, which one of them?
"XR Interaction Toolkit Sample" or "XR Interaction Toolkit Sample - Built-in Render Pipeline"?

**Comment by De-Panther** [comment]
From the screenshot, it looks like you are using URP, but in the details you wrote that you are using Built-in RP.
It's diificult to solve the issue if the info is missing or not accurate.

Can you please share a screenshot of the WebXR settings page?

**Comment by AmalinTasnim** [comment]
Oh sorry, I am using URP and the samples that i refer is XR Interaction Toolkit Sample. I used that sample and apply it to my project which is i am developing a virtual museum tour that can be played both using laptop and headset through browser. 
![Screenshot 2024-03-27 104710](https://github.com/De-Panther/unity-webxr-export/assets/94503937/9cd8d4b3-e93c-4d0d-ae3c-023245147dba)

These are the view from headset left view and right view.
![left view](https://github.com/De-Panther/unity-webxr-export/assets/94503937/cc43a238-c6b4-486d-8d5c-39b284b74a57)
![right view](https://github.com/De-Panther/unity-webxr-export/assets/94503937/55eb54f1-0923-4584-a303-dcf36a30e713)

**Comment by De-Panther** [comment]
Thanks.
Why "DisableXRDisplaySubsystem" is true?
It should be false if using URP and the camera rig you are using.

**Comment by AmalinTasnim** [comment]
Thank you its working!! 
I have one more problem, where can I modify the input system for the controller to be interact with the 3D Model, like i want to rotate the model.

**Comment by De-Panther** [comment]
Great!
From here it's using XR Interaction toolkit like in every platform
