### ISSUE TITLE
Bug : TypeError: Module.dynCall_viffffffff is not a function at Module.WebXR.Onstart at XRManager.animate at XRSession.tempRaf

### ISSUE THREAD

**Issue by rafuryc** [De-Panther/unity-webxr-export#369]
**Describe the bug**
When I start VR mode on the Meta Quest 3 default navigator, it loads and drops this error message. Then, the VR mode won't continue. I tested on Google Chrome too and same results.

**To Reproduce**
1. Build the Desert Sample scene
2. Launch the WebXR on a HTTPS server
3. Access the server
4. Click the VR button

**Expected behavior**
Game shows up in VR

**Screenshots**
![image](https://github.com/De-Panther/unity-webxr-export/assets/98427113/6538db9d-9abe-41bd-a095-4c2fe41b47b2)

**Unity info (please complete the following information):**
- Editor version: 2023.3.0b6
- WebXR package version: 0.22.0
- WebXR Interactions version: 0.22.0
- Git or OpenUPM: Git
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Desert sample
- Built-in render pipeline or URP: Standard

**Desktop (please complete the following information):**
 - OS + Version: Windows 10 Pro 22H2 19045.4170
 - Browser: Chrome 123.0.6312.86

**Headset (please complete the following information):**
 - Device: Meta Quest 3
 - OS: Meta Quest build 63.0
 - Browser: Meta Quest Browser 32.1

**Additional context**
Same problem with AR mode

**Comment by rafuryc** [comment]
Hi, I just tested other stuff and I think I found my mistake.
![image_2024-03-29_140033076](https://github.com/De-Panther/unity-webxr-export/assets/98427113/9e2df025-f467-4fec-883d-b35d92122997)
I fixed it and now, the VR mode is working perfectly (with the same Unity Editor version).
Feel free to close the issue if you think that it is enough to resolve this "bug" :)

**Comment by De-Panther** [comment]
It shouldn't be related

**Comment by De-Panther** [comment]
Tested with Unity 6000.0.0b13 and it didn't happen. As all of those are versions of beta, and it doesn't happen in the latest beta, I guess it's safe to close this issue.
