### ISSUE TITLE
Meshes not rendering at VR browser

### ISSUE THREAD

**Issue by Luboteroa** [De-Panther/unity-webxr-export#370]
**Describe the bug**
Some meshes are not being shown on the VR headset browser

**To Reproduce**
1. On the VR headset. Go to [vr-qa-bcd.azurewebsites.net](vr-qa-bcd.azurewebsites.net)
2. Click on 'VR"
3. You can notice the meshes are not working properly
4. If you open this same link on your own device (not VR one) you can see the same build but with the meshes being rendered properly.

**Expected behavior**
Meshes being rendered as the demo shows.

**Screenshots**
![Imagen de WhatsApp 2024-03-29 a las 11 12 07_f9ec0f32](https://github.com/De-Panther/unity-webxr-export/assets/64756525/9aa6a530-163a-43d7-8f1f-b5cda4d27c36)

https://github.com/De-Panther/unity-webxr-export/assets/64756525/c61357d2-96ca-4623-9af7-ce0e4aabd7ae

**Unity info (please complete the following information):**
- Editor version: 2022.3.8
- WebXR package version: 0.22.0
- WebXR Interactions version: 0.22.0
- Git or OpenUPM: OpenUPM
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Using XR Interaction Toolking
- Built-in render pipeline or URP: URP

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows 10] Windows 10
 - Browser: [e.g. Chrome 104] Google Chrome

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1] Meta Quest 2
 - OS: [e.g. Meta Quest build 55.0] I don't know this. How can I find it?
 - Browser: [e.g. Meta Quest Browser 20.0] I don't know this. How can I find it?

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6] Iphone
 - OS: [e.g. Android 12] 13 pro max
 - Browser: [e.g. Chrome 104] Google Chrome

**Additional context**
I have another project with just XR stuff and it works properly but with the project where it should be working it doesn't work. Maybe I changed a setting and I don't know where?

**Comment by De-Panther** [comment]
I guess that when you build there's a warning about using gamma color space instead of linear.
Use gamma color space.

**Comment by De-Panther** [comment]
And maybe you also set some layers for objects and hide those layers in the camera.

**Comment by Luboteroa** [comment]
I already did the gamma color space setting, also with the layer on the camera. Still not working.

**Comment by De-Panther** [comment]
Can you share screenshots from the editor?
The cameras in the scene, the layer settings of the cameras, and the layer settings in the WebXRCameraSettings component

**Comment by Luboteroa** [comment]
Sure, look:

![Unity_eSzCtsXhaI](https://github.com/De-Panther/unity-webxr-export/assets/64756525/38bf3b55-aa69-40de-9f06-2e41a74dec53)
![Unity_XRSctajRwk](https://github.com/De-Panther/unity-webxr-export/assets/64756525/f848ec19-d18f-4a93-9b11-1fc44ecfcbf7)
![Unity_6kjx80ivkQ](https://github.com/De-Panther/unity-webxr-export/assets/64756525/eac790ec-d0d6-415d-9ab7-115eee8bbd87)
![Unity_TpcHVh5wqZ](https://github.com/De-Panther/unity-webxr-export/assets/64756525/d0f92f91-301c-449f-914e-f1f00219d04b)

**Comment by De-Panther** [comment]
I see that even in non-xr the objects are missing, so I guess it's related to some Unity Web settings in general, and not specific to WebXR.
Maybe some URP settings?
Can you check the Chrome DevTools console for errors/warnings?

**Comment by De-Panther** [comment]
I see that you are using URP High Fidelity Renderer, I guess it's too heavy for mobile web, try something simpler

**Comment by Luboteroa** [comment]
Yes, that's why I say it's weird. Because if you use it on a normal browser (computer or mobile) it shows the meshes but on VR it doesn't. I'll add some debug tools to see what logs I get on VR.

**Comment by Luboteroa** [comment]
Ok now I can see the meshes! I downgrade the URP settings for VR and looks great, but now It does not track my controllers and I can not move or grab things. I'll look if maybe did I change something by mistake.

https://github.com/De-Panther/unity-webxr-export/assets/64756525/6bc4f7b9-7f83-4469-b10d-71eaaae1fd7f

**Comment by Luboteroa** [comment]
It worked! Thanks ♥
