### ISSUE TITLE
Display AR and VR buttons in Unity Canvas

### ISSUE THREAD

**Issue by ragson** [De-Panther/unity-webxr-export#372]
Hi,

I would like to know how to show AR and VR buttons in Unity canvas from the WebGL page which are displaying in the bottom as default? Could you please help me on this solution.

Regards
Kiran.

**Comment by De-Panther** [comment]
Not sure what you are asking.
If it's how to enter AR/VR session from C# code, There's `WebXRManager.ToggleAR` and `WebXRManager.ToggleVR`.
You can check if the user is in non-XR mode, AR mode or VR mode using `WebXRManager.XRState‎` and `WebXRManager.OnXRChange`.

**Comment by ragson** [comment]
<img width="221" alt="image" src="https://github.com/De-Panther/unity-webxr-export/assets/11418848/1871b10e-0acb-451f-b214-3f2616e75d75">

Hi,
i unable to access the WebXRManager script getting compile error can you check the reference image where i missed?

**Comment by De-Panther** [comment]
You need to use assembly definition (asmdef), and reference the WebXR asmdef file.
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by ragson** [comment]
Thank you, Its working.
