### ISSUE TITLE
Screen orientation in AutoRotation mode doesn't work in AR Mode

### ISSUE THREAD

**Issue by jesuscfp** [De-Panther/unity-webxr-export#373]
If I add the line _Screen.orientation = ScreenOrientation.AutoRotation_ on the method Awake  of my script, when the App starts the AR Mode, it never changes the screen orientation when the device changes the rotation

**Steps to reproduce the behavior:**
1. Create a Script and and on Awake method, add the line _Screen.orientation = ScreenOrientation.AutoRotation_
2. Add a Canvas with a text.
3. Build the project.
4. Run project and into in AR mode, then turn left or right your device

**Unity info:**
Editor version: 2021.3.15
WebXR Export version: 0.21.0
WebXR Interactions version: 0.21.0

**Smartphone:**
OS Device: Android 11
Browser: Chrome 121

**Comment by De-Panther** [comment]
As far as I know, it's not something we have control over in WebXR.
The orientation the phone was at when requesting AR session, that would be the orientation for the duration of the session.

**Comment by jesuscfp** [comment]
I wasn't sure if it would be a enhancement more than a bug. I will try to implement my own method.

Thank you!
