### ISSUE TITLE
Unity XR hands not appearing in build 0.22.0

### ISSUE THREAD

**Issue by lsqnet79** [De-Panther/unity-webxr-export#375]
**Describe the bug**
Unity XR hands not appearing in Web.

**To Reproduce**
Follow  Unity XR Hands + WebXR: How To  https://www.youtube.com/watch?v=NDlc11CgnQM

1) Using Unity 2020.3.10f new URP sample build 
2) Install Unity XR hand 1.4.0-pre.1 with both samples imported
3) Set OpenXR Features Checked Hand Interaction Poses ,Hand Tracking subsystem and Meta Hand Tracking Aim. -Tested and working 
4) Link OpenUPM and install Web export 0.22.0 and Webxr interaction 0.22.0
5) Copy WebGLTemple 
6) Set WebGLtemple to WebXR 2020 and Compression format to Disable 
7) Input System Package create and set Background behavior to Ignore Forcus 
8) Checked  WebXR Export in XR Plug-in Mangaement.
9) In Hand Gestures scence - XR Orgin - Reset Camera Offset and set Main camera position Y to 1.1
10) Add WebXR Manager  and WebXR Input System and Set Tracking Orgin Mod to Floor
11) Build and run WebXR
12) Hands not appearing!!!

**Screenshots**

This is my Setup 
![Screenshot 2024-05-07 112533](https://github.com/De-Panther/unity-webxr-export/assets/95261128/dd0e6ec6-c15f-4f49-a8d3-b5b5fa6737fe)

I unchecked the auto load WebXR Manager and WebXR Input System
<img width="851" alt="Screenshot 2024-05-07 114335" src="https://github.com/De-Panther/unity-webxr-export/assets/95261128/eaac5aa0-5a90-4cd5-a0e4-8227ed28f316">

OpenXR for editor 
<img width="773" alt="Screenshot 2024-05-07 114409" src="https://github.com/De-Panther/unity-webxr-export/assets/95261128/e225a5b3-faea-46c2-a16c-02699b4e3327">

Chrome WebXR hands input enabled
![Screenshot 2024-05-07 114722](https://github.com/De-Panther/unity-webxr-export/assets/95261128/206f32c2-8625-4f70-8c16-528d664ca0d9)

**Desktop (please complete the following information):**
 - Window 11
 - Chrome Version 124.0.6367.119 (Official Build) (64-bit)
 - Edge Version 124.0.2478.80 (Official build) (64-bit)

**Headset (please complete the following information):**
 - Meta Quest Pro 
 - OS: Build 64
 - Browser: not using 

**Additional context**

**Comment by De-Panther** [comment]
Why did you unchecked the auto load for WebXRManager and WebXRInputSystem?

Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)

**Comment by lsqnet79** [comment]
> Why did you unchecked the auto load for WebXRManager and WebXRInputSystem?
   - From your video WebXRManager and WebXRInputSystem is aleady added in the XR Origin
> Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)
    Hands are working in the handGestures demo with openXR in editor mode

**Comment by De-Panther** [comment]
My video is for an older version of the package.(as you can see in the video, there's no option for auto load) Is in your version they are already in the scene?

**Comment by lsqnet79** [comment]
> My video is for an older version of the package. Is in your version they are already in the scene?




> My video is for an older version of the package.(as you can see in the video, there's no option for auto load) Is in your version they are already in the scene?

ok I checked the auto load and remove the component in XR origin the result is still the same.

**Comment by De-Panther** [comment]
Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)

**Comment by De-Panther** [comment]
Can you enter WebXR mode?

**Comment by lsqnet79** [comment]
> Can you enter WebXR mode?

Yes I can just the hands are not appearing.

**Comment by De-Panther** [comment]
Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)

**Comment by lsqnet79** [comment]
> Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)

Yes 
![Screenshot 2024-05-07 153737](https://github.com/De-Panther/unity-webxr-export/assets/95261128/7ecf771a-7055-4d3b-8eb4-aad9f5502956)

**Comment by De-Panther** [comment]
> > Does hands works with your setup in existing demos? (e.g. the demos in this repo, or the WebXR Samples repo)
> 
> Yes ![Screenshot 2024-05-07 153737](https://private-user-images.githubusercontent.com/95261128/328430935-7ecf771a-7055-4d3b-8eb4-aad9f5502956.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjc4MzEsIm5iZiI6MTcxNTA2NzUzMSwicGF0aCI6Ii85NTI2MTEyOC8zMjg0MzA5MzUtN2VjZjc3MWEtNzA1NS00ZDNiLThlYjQtYWFkOWY1NTAyOTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZWYwYjY3MTVhNDg5MWU3MWYwMzA0ZTFiMDM3N2MyMWFkNTc5MmM2YTQxNzI3ODE3ZGJiZTcyYWU5YzZhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B-LXFymeopiKcGI7RMyR6f8tIsnQqJ5gkmhhsszKvKI)

Is this WebXR demo or Unity editor/build?

Does hands works with your setup in existing WebXR demos? (e.g. the demos in this repo, or the WebXR Samples repo)
https://de-panther.github.io/unity-webxr-export/Build
https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo

**Comment by lsqnet79** [comment]
ok I know what the problem in Meta quest link the Developer runtime features didnt checked. Think Meta did some update to Meta quest link and looks diffetent. Now is working now appreciated your help. Thank you
