### ISSUE TITLE
Oculus Quest 2 gets spinning Hourglass when loading WebXR project via Quest 2 Link.

### ISSUE THREAD

**Issue by ibytergj** [De-Panther/unity-webxr-export#376]
**Describe the bug**
To rule out any issues from my side when building a project I tried to load your public project at https://de-panther.github.io/unity-webxr-export/Build in my Quest 2 via the Link

When I look in the web console I see the following errors

![image](https://github.com/De-Panther/unity-webxr-export/assets/52046406/b88e6c12-1b9d-492d-833c-82f837a9842b)

**To Reproduce**
1. Start Quest Link
2. Go to  https://de-panther.github.io/unity-webxr-export/Build
3. Click on VR

**Expected behavior**
it should load the scene as per the web page?

**Screenshots**
I see a spinning hour glass in the headset.

**Unity info (please complete the following information):**
- Editor version: 2022.3.27f1
- WebXR package version: .22
- WebXR Interactions version: .22
- Git or OpenUPM: OpenUPM Registry in Package Manager
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Project configured for both input systems
- Built-in render pipeline or URP: URP

**Desktop (please complete the following information):**
 - OS + Version: Windows 11 Pro - 22631.3527
 - Browser: Chrome Version 125.0.6422.60 (Official Build) (64-bit)

**Headset (please complete the following information):**
 - Device: Meta Quest 2
 - OS: Version 65.0.0.499.343
 - Browser: [e.g. Meta Quest Browser 20.0] 33.2.0.1.167.600287777

**Comment by De-Panther** [comment]
Are other WebXR Samples (non-unity) don't work on your device?
https://immersive-web.github.io/webxr-samples/immersive-vr-session.html

https://immersive-web.github.io/webxr-samples/immersive-hands.html

If so,
It might be an issue with OpenXR or browser on your device.

**Comment by ibytergj** [comment]
Hi both of those samples load successfully. The hands demo is a bit messed up as I see some black hand models not oriented correctly and not made out of cubes.

Your demo still hangs.

**Comment by De-Panther** [comment]
Is it the only tab, or only WebGL/WebXR tab open?

**Comment by ibytergj** [comment]
I closed chrome and reopened it. I went to your demo page first and it loaded this time. Thanks for your help debugging this issue.

**Comment by De-Panther** [comment]
Well, seems like a bug in Chrome or Meta OpenXR runtime.

**Comment by ibytergj** [comment]
Any suggestion on how to investigate for these errors

WebGL: INVALID_OPERATION: readBuffer: invalid read buffer
WebGL: INVALID_FRAMEBUFFER_OPERATION: drawElements: Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback.

**Comment by De-Panther** [comment]
Warnings. And no. It happens on the frame that switch between non-XR to XR mode. Doesn't affect performance or anything else.

**Comment by ibytergj** [comment]
I am a little confused. My assumption was my app isn’t loading because of those errors. Do you have any suggestions on how I can debug why I get the hourglass and my app is not loading?

**Comment by De-Panther** [comment]
Those are warnings, not errors.
The app isn't loading because of a bug in Chromium or OpenXR.
Try to open 2 tabs of the non-Unity WebXR Samples and enter VR. It won't work.

**Comment by ibytergj** [comment]
When I reload the browser and enter your demo app it works. When I reload the browser and open my app it hangs. I would like to determine why.

**Comment by De-Panther** [comment]
Is your project works on the Meta Quest Browser?

**Comment by De-Panther** [comment]
Also you didn't provide all the info that the bugs template ask for.

**Comment by ibytergj** [comment]
> Is your project works on the Meta Quest Browser?

It loads but the headset is not tracking properly.

In WebXR on the PC using the Immersive web emulator, I see double vision and the headset is not tracking properly.

![image](https://github.com/De-Panther/unity-webxr-export/assets/52046406/7bedf3a1-e721-4cb8-a16b-1cbd9176b558)

In an older version of the project using Unity WebXR export .14 it was working okay. I upgraded the project to .22 but did not change any of the WebXR components already in the scene.

**Comment by ibytergj** [comment]
To give you an update, I reverted back to 0.14.0-preview and our scene started working again. Is there a migration guide for moving from earlier versions of WebXR to the latest version?

**Comment by De-Panther** [comment]
Look at the latests Getting Started guides in the repo (the basic one and the xr interaction toolkit one).
They were updated recently.

If you are using latest XR Camera Rig prefab, the URP one needs XR Display Submodule to be enabled, and the BiRP one needs it to be disabled. There are notes about it in the guides.
