### ISSUE TITLE
FinalIK Not Tracking

### ISSUE THREAD

**Issue by troach06** [De-Panther/unity-webxr-export#378]
We are using FinalIK and WebXR in our project and all works in the editor with OpenXR, and worked with WebGL as well, however once we added WebXR, FinalIK doesn't seem to be functioning properly. We also are having issues with our Inworld AI and our XR Ray Interactor for our world space UI buttons. Any idea on why this is happening with WebXR and not WebGL?

**Comment by De-Panther** [comment]
There's a template for bug report. Can't help without it.
