### ISSUE TITLE
Detecting / launching VR mode

### ISSUE THREAD

**Issue by Lemovision** [De-Panther/unity-webxr-export#379]
I'm making some kind of art gallery which is meant to work on mobile, desktop and VR with the same web project
For mobile and desktop I have an avatar with a character controller and cinemachine camera
When opening the page in a browser, how can I detect when the user switched to VR mode?
In Unity I would need a script that disables the character controller/camera and enables XR rig at that time

**Comment by De-Panther** [comment]
Look at the methods of WebXRManager.
There's `XRState` and `OnXRChange`. And you can check `isSupportedAR` and `isSupportedVR`.

I'm not sure how well it'll work with enabling/disabling the Rig when switching modes. If it doesn't work well, you can use the character controller on the rig, and attach the cinemachine to the rig's camera (and disabling it when enter XR).

**Comment by Lemovision** [comment]
Thanks yeah that looks pretty handy
Actually now I'm thinking about making my own VR button inside Unity
This way I can use a fullscreen template and the VR mode switch is easier to detect
So then I guess I can use that `isSupportedVR` to make the button visible in that case
Then to launch the VR mode on button click I saw that `ToggleVR` also would that work?

**Comment by De-Panther** [comment]
Yes

**Comment by Lemovision** [comment]
Awesome yeah that button worked

But just a few things, as I'm using exclusively Visual Scripting in Unity please bear with me
So I don't do C# and get a bit confused when I have link external scripts
To make it work I had to create and empty game object and add the WebXRManager script to it from Packages
But then I have an error in the console at runtime "More than one WebXRManager components in scene. Disabling previous one."
Is there any other way to reference it in Visual Scripting, or how would you do it usually in C#?

Also at first I added the WebXR assembly to the available Visual Scripting nodes like on this page:
https://docs.unity3d.com/Packages/com.unity.visualscripting@1.9/manual/vs-add-remove-node-library.html
But when I first tried to build I also had this error because it couldn't find the WebXR assembly definition 
"The type or namespace name 'WebXR ' could not be found (are you missing a using directive or an assembly reference?)"
Eventually I fixed it like this guy by editing manually your WebXR.asmdef file and set "auto-referenced" to true
https://forum.unity.com/threads/object-variable-type-from-assembly-definition-not-found-when-building.1232727/
But I guess if I update your package later then that edit will be reverted?
Is there any other way to reference this assembly, or could you set it to auto-referenced to true by default on your side?

**Comment by De-Panther** [comment]
I don't know how visual scripting in Unity works, never used it.

You might want to create your own script to bridge the WebXRManager component.

I won't change this setting, as it affects script and project compiling time.
