### ISSUE TITLE
2023.3 Unity Version has depreciated functions used in this plugin

### ISSUE THREAD

**Issue by BlazedAhmad** [De-Panther/unity-webxr-export#382]
The plugin uses some functions like dynCall which is depreciated in the 2023.2.20f1 version of Unity.
See: https://docs.unity3d.com/2023.2/Documentation/Manual/web-interacting-browser-deprecated.html#dyncall

Hence the code needs to be modified otherwise it gives an error saying that the function Module.dynCall_vii does not exist.

**Comment by BlazedAhmad** [comment]
@De-Panther  Sorry I mistyped, I meant unity version 2023.2.20f1

**Comment by De-Panther** [comment]
I haven't tried it in 2023.2.20, but it seems to work in Unity 6, which is the LTS of 2023, so I guess it's an error for only small amount of editor versions?

Looking on a `framework.js` file generated by Unity, Unity code is both exposing `dyncall_*` functions and use it in different places.
Maybe they deprecated the `dyncall` function?
The only reference I see to `makeDynCall` is in error message
```
error.message = 'Detected use of deprecated "Module.dynCall_*" API. Use "makeDynCall" API instead. Refer to https://docs.unity3d.com/6000.0/Documentation/Manual/web-interacting-browser-deprecated.html#dyncall for more information.\n' + error.message
```

But I can't find such a function in the generated code.

**Comment by De-Panther** [comment]
Seems like it's related to what Unity calls WebAssembly 2023. If you enable some of it features it disable the 'dynCall' functions.
Seems like they ported it back to other LTS versions like 2022.3 and 2021.3.
I'll make sure to support both cases.
Thanks
