### ISSUE TITLE
How to Fire animations from move and turn methods ?

### ISSUE THREAD

**Issue by Gianlucccc** [De-Panther/unity-webxr-export#383]
I trying to fire animations as an event even player is moving his avatar with oculus joypads

i'd love to fire an event and in another class just play the animation

help please

**Comment by Gianlucccc** [comment]
Bump!

**Comment by De-Panther** [comment]
Missing data. Please look at the issues templates and provide relevant data.

**Comment by Gianlucccc** [comment]
Hello De-Panther.
im just asking how to use new inputsystem to trigger animations, i'm trying to use either WebXRInputActions and XRIDefaultInputActions classes but the input events are just not working

**Comment by De-Panther** [comment]
Again, missing data. There are so many variables that can affect that.
With the little data you provide, I can only guess it's a general issue related to Input System and XRI, and general tutorial on how to use them should help.
