### ISSUE TITLE
Tearing and latency running in browser

### ISSUE THREAD

**Issue by instbldrjems** [De-Panther/unity-webxr-export#386]
**Describe the bug**
When running in the Quest Browser, I get significant image tearing and heavy latency.  The scene runs fine on my Windows PC using Quest Link. I have turned off some components of the rig that I do not need for this demo, such as the Locomotion system, but this has not helped.  I also removed most of my objects, but the issue does not seem to be that I have too dense a scene.
![camera](https://github.com/user-attachments/assets/31a94ba7-5c36-454f-9bf9-2e8d7a55d2c8)
![origin](https://github.com/user-attachments/assets/b600e02e-e2bf-4289-9595-9ad8c470bc9b)
![camera](https://github.com/user-attachments/assets/331b52c2-1b49-4db6-8f9f-10875221cde8)

**To Reproduce**
1. Go to 'https://ww-webxr.com/' in the Quest browser
2. Click on 'VR'

**Expected behavior**
I should be able to have a smooth VR experience, and be able to use distance grab to pick up the rock object on the ground.

**Screenshots**

**Unity info (please complete the following information):**
- Editor version: 2021.3.41
- WebXR package version: 0.22
- WebXR Interactions version: 0.22
- Git or OpenUPM: OpenUPM
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: Using XR Interaction WebXR Setup, as shown in your January 2024 video.

- Built-in render pipeline or URP:  URP

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows 10] Windows 10
 - Browser: [e.g. Chrome 104] Chrome 127

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1] Quest 2
 - OS: [e.g. Meta Quest build 55.0]
 - Browser: [e.g. Meta Quest Browser 20.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - OS: [e.g. Android 12]
 - Browser: [e.g. Chrome 104]

**Additional context**

**Comment by instbldrjems** [comment]
Hi --I actually just upgraded my project to U2022.3.41, and the behavior is different. The VR is now stable, with no tearing and latency problems, but now it is only rendering the right eye -- the left eye is black.  So this is sort of an improvement.... 

 I see other posts regarding this, and will explore suggested solutions, but do you have any idea why only one eye would be rendering?

**Comment by De-Panther** [comment]
Didn't try 2022.3.41, maybe bug in the XR Display Subsystem on web in this version.

Regarding performance, URP has overhead over BiRP on web.
So you can try BiRP and the BiRP samples. The XR Display Subsystem has even more issues with BiRP on web, so disable it(in the WebXR Settings) when using BiRP with the BiRP samples.
(The BiRP samples have different XR Rig that use multiple cameras instead of one)

**Comment by instbldrjems** [comment]
Hi --

Your suggestion to revert to BiRP basically worked.  Disabling the XR Display Subsystem actually caused other problems, so I left that box unchecked in the WebXR settings. But I now have both eyes rendering, so thank you very much!

Jeremy

________________________________

**Comment by De-Panther** [comment]
As I said, the BiRP sample has different rig for no XR Display Subsystem. If you use the URP rig with BiRP you still need to use the display subsystem.

But whatever works for you. Different Unity versions, different issues.
