### ISSUE TITLE
HTC-VIVE controllers are not activated in the Chromium browser

### ISSUE THREAD

**Issue by vladlenKir** [De-Panther/unity-webxr-export#387]
Good day. My name is Vladlen. I don't know any programming. I know Unity 3D satisfactorily. According to your video, "How to use WebXR with Unity - January 2024 Edition" has implemented your plugin. The demo scene of the Starter Assets XR Interaction toolkit package was used. The problem: everything works fine in the editor, the HTC-VIVE controller models are not visible in the Chromium browser, respectively, there is no movement, teleportation of the player, and so on. On Oculus Rift (Windows 10), it works perfectly in the browser! can you tell me where to look for the reason? Thank you in advance.

Unity 2022.3.10.f1
WebXR 0.22.0 - install.
WebXR Input Profiles Loader 0.6.2 not install
WebXR Ineractios 0.22.0 not installed
OpenUPM
URP
Windows 10 + HTC-VIVE PRO
Windos 11 + HTC-VIVE
Chromium Version 130.0.6693.0 (Developer Build), (64 bit)

**Comment by vladlenKir** [comment]
https://realti.onh-project.ru/model/    - build demo scene

**Comment by De-Panther** [comment]
I'm not sure what you expect to see.
Please edit your issue to use the Bugs template.

My guess is an issue with OpenXR when using HTC Vive.

**Comment by vladlenKir** [comment]
https://github.com/user-attachments/assets/4c1bcb93-bbe6-49c6-a372-32ab89594bec


https://github.com/user-attachments/assets/52a2778a-c0a0-45e2-a2f9-4aaf2e6cce12

**Comment by vladlenKir** [comment]
The issue is resolved!
I turned on the Camera in SteamVR. Controllers began to be displayed. Locomotion is working.
Thanks for the support!
