### ISSUE TITLE
XR Interaction Toolkit - UI raycast bug on quest3 browser

### ISSUE THREAD

**Issue by meangpu** [De-Panther/unity-webxr-export#388]
**Describe the bug**
In MetaQuest3 Browser, a UI ray interaction won't disappear when user no longer point at UI

**To Reproduce**
1. Go to https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo on MetaQues 3 web browser
2. Point ray to UI object
3. The ray won't disappear after out of pointing range

**Expected behavior**
A ray disappear when user no longer pointing at ui element

**Screenshots**
I have attach the video file from MetaQuest3
https://github.com/user-attachments/assets/ca6d7d37-a9e5-4260-be77-cd1f51dd56ea

**Unity info**
- I setup project according to this video: [How to use WebXR with Unity - January 2024 Edition - YouTube](https://www.youtube.com/watch?v=4wQG8_pb3cs)

**Headset**
 - Device: [Meta Quest 3]
 - OS: [Meta Quest build 68.0 ]
 - Browser: [Meta Quest Browser 35.0.0.81.88.641734818]
 - Browser Chromium version: [Chromium version: 128.0.6613.127]

**Additional context**
In my project I have interaction that turn the UI object off after user click ui button and the ray is still point at the empty canvas, so I try it again at the example demo and found the same problem, The bug won't happen when run in unity editor, but it will happen when running on Meta quest browser

**Comment by De-Panther** [comment]
In the WebXRCamera GameObject/Component there's a field named `updateCameraTag` set it to true.

Also, please use the bugs template. Usually I can't help without it.

**Comment by meangpu** [comment]
Thank you so much🙇. That fixed it
