### ISSUE TITLE
Buttons and Joystick not working when exporting and playing from browser. 

### ISSUE THREAD

**Issue by genisbr** [De-Panther/unity-webxr-export#390]
Hi, 
I am trying to make the demoScene run in browser, I have imported the three packages and set up as the video from youtube 2024 says. 
In unity, executing works like a charm, everything works. When reproducing on the browser, headset is moving, also controllers. But the buttons are doing nothing. I cannot walk or grab things. What can I be missing? 

Steps I did: 
1- Create vr core project.
2- Import packages using the OpenUPM 
3- set everything like the video did
4- Set the environment to export as html5
build and export

Not working with real headset and not working with the webxr emulator cchrome extension. 

Thank you.

**Comment by De-Panther** [comment]
Can't help with no info. Please use the bugs template.
