### ISSUE TITLE
Low FPS on Quest 2 browser and unclear usage of webXR camera

### ISSUE THREAD

**Issue by blavVR** [De-Panther/unity-webxr-export#392]
**Describe the bug**
Hello,

I'm currently experiencing low fps on Quest 2 browser (about 45fps) even in a nearly empty scene.
I'm Using the URP webXR pipeline. I came across this issue: [357](https://github.com/De-Panther/unity-webxr-export/issues/357)
which sounds similar to my problem.
So I reverted to Built-in render pipeline and tried to disable XR display Subsystems. This is
where things get vague. The tooltip mentions to add the webXRcamera component, but to what? To
the existing camera? If so, do I manually create and offset the left and right eye cameras? 
I tried to do that, but now the screen is entirely black. I may be missing an example prefab for this, and 
can't find any documentation for the webXRCamera class. 

So 1 of 2 possible solutions would help me:

1. Dig deeper into why the fps is so low
2. Clearer instructions on how to use the webXRcamera so I can revert to BiRP

Thanks in advance for your help. And btw, thanks a lot for your work so far, 
aside from the FPS, your webXR export works really well!

**To Reproduce**
Make a build, upload it, run it through Quest browser, activate VR mode.

**Expected behavior**
I expect the scene to run with +/- 90fps since it's completely empty aside from the XR rig, and a teleport groundplane

**Unity info (please complete the following information):**
- Editor version: 2022.3.26f1
- WebXR package version: 0.22.0
- WebXR Interactions version: 0.22.0
- Using Input System + XR Interaction Toolkit
- Built-in render pipeline or URP: URP

**Desktop (please complete the following information):**
- Windows 10

**Headset (please complete the following information):**
 - Device: Meta Quest 2
 - OS: Meta Quest build 65.0
 - Browser: Meta Quest Browser 34.0

**Comment by De-Panther** [comment]
There are 2 Samples for URP and identical samples for BiRP.
Use one of the BiRP samples.

**Comment by blavVR** [comment]
Thank you! Had to download the latest release from github instead of through the asset browser to get these samples.

**Comment by De-Panther** [comment]
They are there in the package manager window, in the WebXR Interactions samples.

**Comment by blavVR** [comment]
Thanks a lot for the help!
