### ISSUE TITLE
PICO4 hand tracking and eye gazing

### ISSUE THREAD

**Issue by zy-lazytitan** [De-Panther/unity-webxr-export#395]
I am developing an application on PICO 4 Pro using WebXR and Unity. I noticed that PICO 4 has hand tracking and eye gazing features, and the official development toolkit is available at [https://developer-cn.picoxr.com/document/unity/]. I have been able to call the corresponding functionalities for Android development. However, it seems that WebXR does not support these two features. I would like to know how I can adapt them for the web platform.

**Comment by De-Panther** [comment]
Hand tracking is supported in WebXR and WebXR Export out of the box. Check the relevant samples, following one of the getting started guides in this repo.

Eye tracking is not supported in WebXR.

**Comment by zy-lazytitan** [comment]
Thank you for your response. Maybe I'll develop my application with the hand tracking module in WebXR, not which in PICO SDK
