### ISSUE TITLE
PICO4 + SteamVR Streaming to Open WebXR Application

### ISSUE THREAD

**Issue by zy-lazytitan** [De-Panther/unity-webxr-export#396]
Sorry, perhaps a stupid question, but I can't figure it out.

This work is meaningful. I am already able to open the live demo [](https://github.com/De-Panther/unity-webxr-export) on PICO4 using the PICO Browser. When I click the VR button in the bottom right corner, I can see the 3D scene instead of a 2D webpage. However, if my VR device is not connected to the internet, I need to access the WebXR application through SteamVR streaming.

Currently, I am using Chrome on my PC to access [](https://github.com/De-Panther/unity-webxr-export) and streaming it to PICO4 through SteamVR. In PICO4, I can see the 2D PC screen. When I use my PICO controller to click the VR button in the bottom right corner of the webpage, I see Figure 1, which is still a 2D screen. The 3D scene mentioned above does not appear in PICO. What could be the reason for this?

![Screenshot_com picovr picostreamassistant_2024 10 16-16 20 58 967_767](https://github.com/user-attachments/assets/b1964b16-7936-4a8f-a213-a0fdd9b2612a)

**Comment by De-Panther** [comment]
My guess is that you have WebXR emulator active on your desktop browser

**Comment by zy-lazytitan** [comment]
Sorry I'm new to this field. What does "WebXR emulator" mean? What can I do to check the bug and solve this problem? Sincerely thanks for your response.

**Comment by zy-lazytitan** [comment]
Sincerely thanks for your response. I found "WebXR Emulator" in my chrome extensions and uninstalled it. Now I can see the 3D scene in PICO!
