### ISSUE TITLE
XR Hands in PICO 4

### ISSUE THREAD

**Issue by zy-lazytitan** [De-Panther/unity-webxr-export#397]
I apologize for bothering you so many times, but I’m still quite new to this. I encountered some issues while configuring WebXR + hand input following [the YouTube tutorial](https://www.youtube.com/watch?v=NDlc11CgnQM). Since WebXR inherits XR Hands, I believed I needed to ensure PICO 4 + XR Hands was working first. Here’s what I did:

1. Using Unity 2021.3.22f1c1 new URP sample build.
2. Installed Unity XR Hands 1.5.0 with both samples imported.
3. Set OpenXR features with Hand Interaction Poses, Hand Tracking subsystem, Meta Hand Tracking Aim checked, and selected Hand Interaction Profile in Interaction Profiles, just like in the video.

Then, I streamed PICO 4 with SteamVR. In the Unity Editor, although I enabled the PICO hand tracking feature (which works fine on the device), the application didn’t track my hands and instead treated the controller as the hands.

For comparison, I switched to another VR device—Oculus Quest 2. Without changing anything in Unity (same project), I streamed Oculus Quest 2 using SteamVR + Meta Quest Link. In the Unity Editor, it tracked my hands perfectly, just like in the video!

Does this mean that XR Hands does not support hand tracking for PICO 4? What can I do to build a WebXR application with hand input on PICO 4? I'm so confused.

I would really appreciate your insights. Looking forward to your reply!

**Comment by De-Panther** [comment]
I'm not familiar with Pico devices. It's not WebXR Export related question.
Questions like those better ask on https://discord.gg/webxr
