### ISSUE TITLE
Output a depth texture from a camera

### ISSUE THREAD

**Issue by robotronex** [De-Panther/unity-webxr-export#399]
It would be nice to support the generation of a depth texture from the [camera output](https://docs.unity3d.com/Manual/CameraOutput-introduction.html).

This is often used by post processing effects which use depth information.

Excerpt from the camera output link.

The Camera’s depth Texture mode can be enabled using [Camera.depthTextureMode](https://docs.unity3d.com/ScriptReference/Camera-depthTextureMode.html) variable from script. It is also possible to build similar textures yourself, using [Shader Replacement](https://docs.unity3d.com/Manual/SL-ShaderReplacement.html) feature.

There are three possible depth texture modes:

DepthTextureMode.Depth: a depth texture.
DepthTextureMode.DepthNormals: depth and view space normals packed into one texture.
DepthTextureMode.MotionVectors: per-pixel screen space motion of each screen texel for the current frame. Packed into a RG16 texture.
These are flags, so it is possible to specify any combination of the above textures.

**Comment by De-Panther** [comment]
Doesn't sound related to WebXR Export.
Seems like a general feature of unity.
If it is supported on Unity WebGL it should be supported.
Do notice that postprocessing on XR is heavy, and in WebXR I guess it would be even more demanding.

**Comment by robotronex** [comment]
You're correct. It wasn't related to the exporter. There must be a setting to disable this as it was resolved by simply selecting the medium quality level in the project settings.
