### ISSUE TITLE
Head tracking stops when switching scenes depending on skybox/lighting

### ISSUE THREAD

**Issue by zer0grand** [De-Panther/unity-webxr-export#40]
Head tracking can stop when switching between scenes. I have a Vive and I'm using Firefox. If you duplicate the sample scene and switch between the two, it's fine. I have figured out it's something related to the skybox/lighting. Say I duplicate the scene and switch the skybox (ex. to something from https://assetstore.unity.com/packages/2d/textures-materials/sky/skybox-add-on-136594). When I switch from the sample scene to the duplicated one, the head tracking freezes even though the controllers can still move around. I can't pinpoint exactly what the issue is since some skyboxes don't freeze tracking... Any ideas?

**Comment by De-Panther** [comment]
It sounds weird. Are you sure you don't have existing cameras in those scenes?

**Comment by zer0grand** [comment]
Yeah, tested it a few more times to make sure. I'll put up a demo scene on github pages soon as an example

**Comment by De-Panther** [comment]
Sure. Upload a project (preferably a fork of this repo), and I'll check it

**Comment by zer0grand** [comment]
**Here is the pages link:** [https://zer0grand.github.io/unity-webxr-export/index.html](https://zer0grand.github.io/unity-webxr-export/index.html)
**Here is the repo:** [https://github.com/zer0grand/unity-webxr-export](https://github.com/zer0grand/unity-webxr-export)

I added a cube to the Desert scene. When the cube is touched by a hand, the scene switches to "Desert 1". This scene is the same as Desert with the only change being the skybox. Tested with a Vive on Firefox, the head tracking freezes (the hands still track). 

**On another note:**
If you touch the cube in the "Desert 1" scene, it will take you back to the "Desert" scene, though it will create the duplicate camera glitch. While this second part isn't really a bug or the issue I'm referencing, it might be worth adding some type of singleton behavior to the camera rig. ex:

namespace WebXR {
  public class XRCamera: MonoBehaviour {
    public static XRCamera current = null;

    void Awake() {
      if (null == current) {
        current = this;
      } else if (current != this) {
        Destroy(gameObject);
      }
    }

  }
}

(I can't figure out how to format that code with markup...) But this way there can't be duplicate XR camera rigs.

**Comment by zer0grand** [comment]
Just did a little testing and figured out changing the "Awake()" function in "WebXRManager.cs" to this will fix the camera duplication thing:

    private void Awake()
    {
      Debug.Log("Active Graphics Tier: " + Graphics.activeTier);
      if (null == instance) {
        instance = this;
      } else if (instance != this) {
        Destroy(gameObject);
      }

      if (instance.dontDestroyOnLoad)
      {
        DontDestroyOnLoad(instance);
      }
      xrState = WebXRState.NORMAL;
    }

**Comment by De-Panther** [comment]
Thanks!

Regarding the singleton, yes, it should be in the `WebXRManager`.

I'm trying to think of a good way to generalize all the Rig, so it would be easier to implement it in current AR/VR rigs.
Would like to hear what you think.
Which XR APIs are you working with in general(Not for WebXR) to get the Camera and Controllers poses?

**Comment by zer0grand** [comment]
What do you mean by generalize? Do you mean break it down into smaller prefabs that can create a rig when put together? I've been working on a hand interaction system that is more generalized, though not sure how much you would like it since it uses parenting instead of fixed joints.

Also when you say XR API do you mean the OVR Integration and SteamVR packages? I use those a fair amount but I've been using your exporter more recently because it is so much cooler/better to build stuff for the web due to accessibility.

**Comment by De-Panther** [comment]
Sorry, but I didn't get to check it yet. Did adding the `Destroy` method on `Awake` solves the issue?

**Comment by De-Panther** [comment]
Reading this issue https://github.com/MozillaReality/unity-webxr-export/issues/423
I guess it's the same, and by the look of it, it might already fixed in this repo in https://github.com/De-Panther/unity-webxr-export/pull/65

I'm closing this issue, as there wasn't a comment for a long time. If it still happens please comment.
