### ISSUE TITLE
Error upgrading from 0.22.0 to 0.22.1

### ISSUE THREAD

**Issue by ibytergj** [De-Panther/unity-webxr-export#406]
**Describe the bug**
Error upgrading from 0.22.0 to 0.22.1
[Package Manager Window] Error adding package: com.de-panther.webxr@0.22.1.
EPERM: operation not permitted, rename 'C:\src\Unity\Glenn\Library\PackageCache\com.de-panther.webxr' -> 'C:\src\Unity\Glenn\Library\PackageCache\.del--61340-Chq1NYRvNO3E'
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**To Reproduce**
1) Attempt up update the package as normal

**Expected behavior**
Successful upgrade

**Screenshots**

**Unity info (please complete the following information):**
- Editor version: Unity 6000.0..25f1
- WebXR package version: 00.22.0
- WebXR Interactions version:00.22.0
- Git or OpenUPM: openUPM
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit:
- Built-in render pipeline or URP: URP

**Desktop (please complete the following information):**
 - OS + Version: [e.g. Windows 10] Windows 11
 - Browser: [e.g. Chrome 104] N/A

**Headset (please complete the following information):**
 - Device: [e.g. Meta Quest 1] N/A
 - OS: [e.g. Meta Quest build 55.0] N/A
 - Browser: [e.g. Meta Quest Browser 20.0] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 6 ]N/A
 - OS: [e.g. Android 12 ]N/A
 - Browser: [e.g. Chrome 104 ]N/A

**Additional context**

**Comment by De-Panther** [comment]
Looks like Unity Package Manager Window issue.
You can try update manually, by closing Unity, edit the `Packages\manifest.json` file, and change the 0.22.0 version to 0.22.1.
That should solve the issue.
Please update here if it worked/failed.

**Comment by ibytergj** [comment]
I followed your suggestion - I received

An error occurred while resolving packages:
  One or more packages could not be added to the local file system:
    com.de-panther.webxr: EPERM: operation not permitted, rename 'C:\src\Unity\Glenn\Library\PackageCache\com.de-panther.webxr' -> 'C:\src\Unity\Glenn\Library\PackageCache\.del--56504-Kok8C9f2t1Zl'

So I manually remove the WebXR dir from the package cache and then reloaded the project. That seemed to work okay.
