### ISSUE TITLE
WebXR app doesn't run properly on Pico 4

### ISSUE THREAD

**Issue by AiriZzz** [De-Panther/unity-webxr-export#407]
Hello, I'm working on a project using the registry. I manage to build the project and test it on Oculus Rift browser and it works perfectly fine as intended, the project can even change to AR/VR mode. But when I am testing it on browser in Pico 4, the project does not run properly, so many bugs and can only use in the web version.

May I know what could be the issue on the project, or is it still a work in progress by Pico or something?

**Comment by De-Panther** [comment]
Use the bugs template. Can't help without it.

**Comment by AiriZzz** [comment]
Currently I am using Pico browser version 3.3.42 with Pico 4 system version 5.11.2.5

I have used the bug template and build test it and still the project cannot run properly. 
Its okay for now but as a heads up just incase. Thank you
