### ISSUE TITLE
When I press the vr button in quest 2 using Meta quest link, it keeps loading and doesn't load the webGL build In the VR.

### ISSUE THREAD

**Issue by rashedabuodeh** [De-Panther/unity-webxr-export#414]
**Expected behavior**
that when i connect Headset quest 2 and open meta quest link and on the desktop in chrome when I press the vr button on the webGL build it should run the app on vr, not keep loading

**Unity info (please complete the following information):**
- Editor version: 2022.3.27f1
- WebXR package version: 0.22.1
- WebXR Interactions version: 0.22.1-preview
- Git or OpenUPM: GIT
- Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: using any of them make the bug
- Built-in render pipeline or URP:URP

**Desktop (please complete the following information):**
Chrome 131.0.6778.204 (Official Build) 

**Headset (please complete the following information):**
 - Device: Meta Quest 2
 - 
<img width="1201" alt="Screenshot 2024-12-20 231128" src="https://github.com/user-attachments/assets/6ff4bf72-5d82-4356-b72d-a29e0a1cf17a" />

 - OS: [e.g. Meta Quest build 55.0]
 - Browser: [e.g. Meta Quest Browser 20.0]

Here is the warning in chrome consle: WebGL: INVALID_FRAMEBUFFER_OPERATION: drawElements: Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback.Understand this warningAI 24[.WebGL-0x62c400b43f00] GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs.

**Comment by BrennanCrowder** [comment]
It is working for me so something may be wrong with your setup. Have you tried with De-Panther's official demo https://de-panther.github.io/unity-webxr-export/XRInteractionToolkitDemo/?

**Comment by rashedabuodeh** [comment]
yes I have tried the official demo, and it's  the same, it doesn't work when I try it with I meta quest link, I mean I open my desktop on my vr.
But yeah when I open the demo from the quest browser it does work

**Comment by De-Panther** [comment]
You ignored some requested info (e.g. OS and version).
My guess is that you have issue with your setup, as Brennan mentioned.
I guess this basic sample https://immersive-web.github.io/webxr-samples/immersive-vr-session.html
also won't work.

There could be an issue with your OpenXR Runtime.
You can follow this thread for more suggestions https://github.com/aframevr/aframe/issues/4709

**Comment by rashedabuodeh** [comment]
yes this basic sample it works on the quest2 vr with meta quest link, how can i integrate it on unity ?

**Comment by De-Panther** [comment]
Try to close all tabs and open only the Unity WebXR demo.

**Comment by rashedabuodeh** [comment]
Thanks, it works when i close the tabs, can i know the reason ?
and there's no way to make it work with other tabs ?

**Comment by De-Panther** [comment]
I don't know why, but noticed it in the past.
Bug in Chrome/Chromium. Nothing I can do. You can report a bug at https://issues.chromium.org/issues?q=webxr
