### ISSUE TITLE
My AR app doesn't appear with it's ui when I press the ar button, it just show my camera feed

### ISSUE THREAD

**Issue by rashedabuodeh** [De-Panther/unity-webxr-export#415]
btw the ar app I'm testing  webxr Desert scene ( sample scene ), using unity webGL.
even though I tried your  sample scenes( Interactions,  desert) and both of them works good on my phone.

so what could be the problem?

I am building the project from build settings then build ( not build and run as it was suggested not to do),
and I'm  testing it on phone using ngrok server

**Comment by De-Panther** [comment]
When you open an issue, github suggests to use the bug report template. It has lots of relevant questions and info.
Please use it.
