### ISSUE TITLE
My AR build doesn't appear with it's ui when I press the ar button, it just show my camera feed

### ISSUE THREAD

**Issue by rashedabuodeh** [De-Panther/unity-webxr-export#416]
**Describe the bug**
when i build my unity webGL project and  then press the ar button on the webxr bar, it just show me the feed of the camera phone, without my build on it.

**To Reproduce**
 the ar app I'm testing is Desert scene ( webxr sample scene), using unity webGL.
I am building the project from build settings then build (not build and run as it was suggested not to do), and I'm testing it on phone using ngrok server ( it is giving secured server https ).

even though I tried the live demo ( Interactions, desert) and both of them, the ar feature works good on my phone. so what could be the problem with my build? 

**Expected behavior**
when i press the ar button, on webGL build on phone it should keep showing for me the unity ar build with camera fee as a background 

**Unity info :**
-  Editor version: 2022.3.27f1 
- WebXR - package version: 0.22.1 
- WebXR Interactions version: 0.22.1-preview . 
- Git or OpenUPM: GIT . Using old components (like the Desert sample) or Input System + XR Interaction Toolkit: using any of them make the bug .
-  Built-in render pipeline or URP:URP

**Desktop :**
 - OS + Version: [e.g. Windows 11]

**Smartphone :**
 - Device: [e.g. Samsung s22 ultra]
 - OS: [e.g. 14]
 - Browser: [e.g. 131.0.6778.200]

**Comment by De-Panther** [comment]
There's URP settings file for WebXR, try to use it.
Or you can try and disable Multisample anti-aliasing (MSAA).

**Comment by rashedabuodeh** [comment]
yes I did that, and still the same.
actually after using android studio to debug, i found those errors :

[ERROR:gl_utils.cc(420)] [.WebGL-0x20dc1dc00] GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs.
hit_test.cc:426] INTERNAL: No point hit.

**Comment by De-Panther** [comment]
Those warnings that can be ignored.

Are you using gamma or linear color space? Try to switch

**Comment by rashedabuodeh** [comment]
linear

**Comment by De-Panther** [comment]
Tried to switch to gamma? There should have been a warning suggesting that once you build the project:
"WebXR Export requires Gamma Color Space,
using Linear Color Space might cause issues."

In Unity 6 it's linear.

**Comment by De-Panther** [comment]
Does switching to gamma solved the issue?

**Comment by rashedabuodeh** [comment]
yeah thanks, it solved the issue.  but is there a way to make it  work with post processing enabled ?
and another issue is that I can't detect surfaces,  even though it was working as apk.

**Comment by De-Panther** [comment]
Post processing - you'll have to make your own tests.
Plane detection - there's experimental WebXR module for that, but it is not officially available in any browser. There's Origin Trial for it in Chromium https://chromestatus.com/feature/5732397976911872 , but it's not implemented in WebXR Export.
