### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by zer0grand** [De-Panther/unity-webxr-export#42]
I made a couple scripts that allow peer-to-peer multiplayer through WebRTC and was wondering if you would find it useful enough for the repo.

BTW: It currently uses the SendMessage command but I think it could be optimized by passing data between JS and Unity similar to how the XR data is passed. Also I have it functional between two players but currently working on an implementation for more.

**Comment by De-Panther** [comment]
That's great! I wanted to try and play a little with Multiplayer+Unity+WebXR.
But I don't think that it should be part of this repo.
You can make a new repo and I'll add it in a section in the README about projects that use this exporter.

How I see this repo:
I first started it when the origin repo was still using WebVR. In the start I did it only as an experiment, but later I wanted to use it in one of my games and other projects.
I'm helping in merging this repo to the origin, but I'll keep maintain this one, as I try to make it more suitable for my needs.

What are my needs:
- Once 2020.1 will be out of beta, I'll upgrade this repo to 2020.1, as they added the Package Manager an option to use path of git repos, and not just the root folder. I want to use this exporter as a package. I'll move the WebXR folder under the `Packages` folder.
- Strip out unnecessary code. The origin repo was built with `UnityEngine.XR` stuff in the components. Forced you to use specific hierarchy for the Camera Rig, and had specific interactions for the controllers. I already removed some of those, but I still have some work to do. I prefer to do this changes here, so in my projects I won't need to make lots of custom work just to implement this exporter.
- Add support for the new Unity XR Interaction Toolkit. I don't want it to be part of the base, So once I'll get to work on it, I guess that I'll add it as another folder under the `Packages` folder.

So once we'll get to those changes, you'll be able to refer to this repo from the `Packages/manifest.json` file.

**Comment by zer0grand** [comment]
Oh cool I had no idea you can do that in 2020.1! I'll clean up the project a little and send a link your way.
