### ISSUE TITLE
Suggestion: Non XR support controls

### ISSUE THREAD

**Issue by zer0grand** [De-Panther/unity-webxr-export#43]
The Mozilla repo has the click and drag to look around as well as WASD to move for people without XR devices. I was wondering if you thought it would be a good idea to have that, but instead use `Cursor.lockState = CursorLockMode.Locked;` and track mouse position for a better experience. This would make the cursor act like any normal first person game.

**Pros**: This method doesn't make the user move the mouse back and forth to turn the camera in a single direction.

**Cons**: People who haven't played first person games before may be more confused when using this method of looking around over the click/drag method

I've been using this in a project of mine so if you think this is a good idea I can give you some code

**Comment by De-Panther** [comment]
Hmmm... I don't think that it should be part of this repo. In the origin repo the script you describe is part of the sample scene.
How developers handle movement in the non XR session is up to them. One would like to move with WASD and cursor like FPS games, others would like to stay static, and others would like to only rotate the camera by dragging the cursor.

I'll write more about how I see this repo in the issue you opened regarding Multiplayer

**Comment by zer0grand** [comment]
👍
