### ISSUE TITLE
Unity package link not working anymore

### ISSUE THREAD

**Issue by FreekLabs** [De-Panther/unity-webxr-export#76]
Hello,

exciting to see this project be taken so far ahead, keen to try it out and noticed there might be a unitypackage around, would that still be available?

"Or just use this as a Unity Package (UPM), more info here" <---- that link where "here." points to

Thank you!

**Comment by De-Panther** [comment]
Thanks!

It's "Unity Package Manager" package, and not the old `.unitypackage` file. Fixed the link.
