### ISSUE TITLE
MSAA support

### ISSUE THREAD

**Issue by HawkenKing** [De-Panther/unity-webxr-export#80]
would be nice to get anti-aliasing working without the framerate hit. For example 4x MSAA

**Comment by De-Panther** [comment]
Some browsers supports `WebGLLayer` with antialiasing, but not all.
There's also the `framebufferScaleFactor` of `XRWebGLLayer`.
We can add `framebufferScaleFactor` to the WebXR settings asset in the editor.

**Comment by De-Panther** [comment]
Opinion needed:
The default `framebufferScaleFactor` value is `1.0` which represents the actual pixels resolution of the device.
`XRWebGLLayer` has `getNativeFramebufferScaleFactor(xrSession)`.
As I understand, it's the *recommended* scale factor (for low end devices it can be half of the resolution, so `0.5`), and not the native resolution factor (`1.0`).

So first, I need to confirm this.
Then, I need to figure out how to display it in the WebXR Settings window.
At first, I thought about a slider with a value between `0.25` to `2.0`.
But if you want to use the recommended, I need to represent it some how.
And what if we want to increase/decrease this value by the `getNativeFramebufferScaleFactor` value?

I'm not sure what is the right solution here.

**Comment by De-Panther** [comment]
Got some feedback on the WebXR discord.
`framebufferScaleFactor` default of `1.0` is actually the *recommended* scale factor.
`getNativeFramebufferScaleFactor` is as it's name suggest, the number you need to set in `framebufferScaleFactor` to run on native resolution.

So I can add in the WebXR Settings, `framebufferScaleFactor` for AR/VR, and it's default of it would be `1.0` and you would be able to set it between `0.2` and `2.0`. But there would also be "**Use native resolution**" bool, which would be `false` by default.

What do you think?

**Comment by HawkenKing** [comment]
so long as it's obvious how to turn MSAA on/off I'm sure anything is fine.
