### ISSUE TITLE
Foveated rendering support

### ISSUE THREAD

**Issue by HawkenKing** [De-Panther/unity-webxr-export#81]
Would be nice to have if possible, for performance on un-tethered

**Comment by De-Panther** [comment]
I don't know about current implementation of foveated rendering in WebXR.
Oculus added support to WebXR Layers under a flag in Oculus Browser recently, but I didn't see there something that can help implementing performant foveated rendering.
If you know about foveated rendering implementation in WebXR, I'll be happy to see some links and info.

Currently our main issue with performance is that Unity's XR SDK doesn't support WebGL, so we can't implement single pass rendering. Once it'll support WebGL, we'll be able to implement this (we already had some preparations for that).
I also think that Implementing layers support without the XR SDK support, would miss the performance gain, but that's something to research.

Thanks

**Comment by De-Panther** [comment]
Waiting for more info. Closing the issue for now.
