### ISSUE TITLE
Camera move

### ISSUE THREAD

**Issue by dthery** [De-Panther/unity-webxr-export#82]
Hi guys, I wish I could move around in VR with the controllers. Teleportation or other.
Do you have a script for that?

**Comment by De-Panther** [comment]
I don't have something like that, but you can adapt existing locomotion assets to work with this package.
Like this one https://github.com/IJEMIN/Simple-Unity-VR-Teleporter
Here's a sample by @Jocyf https://github.com/Jocyf/WebXR-Exporter-Advanced

**Comment by De-Panther** [comment]
I forked IJEMIN's repo, and added support for WebXR
https://github.com/De-Panther/Simple-WebXR-Teleporter

I hope that soon we'll be able to support Unity's XR Interaction Toolkit, and then developer would be able to use it with no changes.
