### ISSUE TITLE
Haptic feedback 

### ISSUE THREAD

**Issue by TheBricktop** [De-Panther/unity-webxr-export#88]
Is there any way to add haptic feedback to the basic setup?

**Comment by De-Panther** [comment]
Sure. It's already available.
`WebXRController` has `Pulse` method
https://github.com/De-Panther/unity-webxr-export/blob/9d1e8c8b769ac14831c7ec3c9101cd893fc3ff76/Packages/webxr/Runtime/Scripts/WebXRController.cs#L372
You can see how we use it in `ControllerInteraction`
https://github.com/De-Panther/unity-webxr-export/blob/9d1e8c8b769ac14831c7ec3c9101cd893fc3ff76/Packages/webxr-interactions/Runtime/Scripts/ControllerInteraction.cs#L59
Provide `intensity` between 0 to 1, and `duration` in milliseconds.

**Comment by De-Panther** [comment]
Just make sure that you use supported browser.
As far as I know:
Oculus Browser on Quest supports it.
Firefox on desktop supports it (Firefox runs WebVR, the exporter uses Polyfill to work on Firefox).
And Chrome on desktop currently doesn't support it.

**Comment by De-Panther** [comment]
Closing the issue. Hope the answers helped :)
