### ISSUE TITLE
2020 support? (what actually doesnt work?)

### ISSUE THREAD

**Issue by TheBricktop** [De-Panther/unity-webxr-export#89]
As in title i've made mistake and didn't read about the lack of support for 2020 edition, 
Is that not a big deal or should I migrate assets to 2019 lts?

**Comment by De-Panther** [comment]
I didn't test it on 2020.x, but Unity changed the structure of the `WebGLTemplates` and some `UnityLoader` settings.
So I'm sure it won't work, but I'll have to test it to see what exactly changed and needs to fix

**Comment by TheBricktop** [comment]
Oof, back to refactoring then.

**Comment by De-Panther** [comment]
You can try and check what are the differences and PR a fix here.
My plan for 2020.x support, is to add 2020.x project in a subfolder for tests, and add `WebXR2020` and `WebXRFullView2020` to the `WebGLTemplates`.

**Comment by octopus8** [comment]
Hey there and thanks for all the work! I've made some progress on Unity 2020, but I've become a bit stuck. After switching to VR, the display is only in the bottom left of the screen. I can see it has head and hand tracking but I can't get the display right. 
![com oculus browser-20201124-131657](https://user-images.githubusercontent.com/4854583/100162866-9fec5f00-2e58-11eb-8014-a10999746b27.jpg)

**Comment by De-Panther** [comment]
I also tried to add support for 2020.
Started to make a new WebGLTemplates, and all seemed to work well. But...

In 2019.x - Changing the `width` and `height` of the canvas element changed Unity's `Screen.width` `Screen.height` and the `GLContext.viewport`.
In 2020.1 - It seems that changing those canvas values doesn't change them.

I'm trying to figure out how to set `Screen.width` `Screen.height` and the `GLContext.viewport` in 2020.1.
That's the current stopper.

**Comment by De-Panther** [comment]
One possible solution is to also change the canvas `style.width` and `style.height`, but that'll affect the actual web page.

**Comment by De-Panther** [comment]
Found a solution by overriding `JS_SystemInfo_GetCanvasClientSize` and `JS_SystemInfo_GetPreferredDevicePixelRatio`.
