### ISSUE TITLE
Support for Unity XR Interaction Toolkit

### ISSUE THREAD

**Issue by De-Panther** [De-Panther/unity-webxr-export#95]
While Unity XR SDK doesn't support WebGL, which hinders #3 (Use Unity's new XR Management package), it may be possible to inject data to packages that rely on the XR SDK and XR Providers.

https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@latest/index.html
Unity XR Interaction Toolkit is a popular package, with lots of ready made components for AR and VR.
Might be relevant to create a new UPM Package for a layer between XR Interaction Toolkit and WebXR Export.

**Comment by MarcoLavoro** [comment]
Hi, i find here:
https://github.com/MozillaReality/unity-webxr-export/issues/369

That seems the older version with the new package:
this:
2019.3.9f1 and XR Plugin Management 3.2.6, XR Legacy Input Helpers 2.1.3, XR Interaction Subsystems 1.0.1, and XR Interaction Toolkit (preview) 0.9.4.

seems to work.

Anyone have tried and can confirm that?
maybe is because an update in the xr interaction toolkit?

I need to convert a standard vr project with xr toolkit in a webvr solution

**Comment by De-Panther** [comment]
I don't know about any support of Mozilla WebXR Exporter for Unity's XR Interaction Toolkit, Mozilla didn't update their repo for almost 10 months now.

I tried to dive in to how the XR Interaction Toolkit works, and there'll be lots of work to make it compatible with no Unity XR SDK support for WebGL.

@marwie and @hybridherbst have a private experimental project in which they managed to make the XR SDK and the XR Interaction Toolkit to work with WebXR Export (this repo/fork).
https://twitter.com/marcel_wiessler/status/1356376306968109068
But the solution would be to wait for Unity to add WebGL support for the XR SDK.

For now, if you need a toolkit that allows interactions and locomotion and works in WebXR, try VRTK, there's a video tutorial by FusedVR https://www.youtube.com/watch?v=RKpa2tDvNiQ

**Comment by antont** [comment]
Now you have WebXR Interactions package, so is this actually closed, or am I missing something? Getting to know these things more now, testing as well, thanks for all the work.

**Comment by De-Panther** [comment]
The WebXR Interactions package is not related to Unity XR Interaction Toolkit.
It's a package with some sample scripts/prefabs and a scene, that shows how you can use the WebXR Export

**Comment by antont** [comment]
Right, sorry for the noise, just saw this in the release notes of that package and came to edit my comment.

I get it now, thanks!

--
[0.2.0] - 2020-10-30

**Comment by CryptoverseGirl** [comment]
Hi @De-Panther ! I built a app with XR interaction toolkit, now i want the same application to work in the WEBGL. is it possible ? or Should I create it with WEBXR from scratch again. pls help me !
