### ISSUE TITLE
Allow user to start session from inside Unity

### ISSUE THREAD

**Issue by HawkenKing** [De-Panther/unity-webxr-export#96]
This an enhancement idea, would be nice if we can control the VR (or AR) start process from inside Unity (using a UI button), allowing for fullscreen webgl wrapper templates.

**Comment by jamwitk** [comment]
Actually, you may do it with little trick, that you will build 2 scene first will normal second will integrated webXR. In normal scene you may add UI button for switch to webXR. You will upload both of scene in different folders like (.com/normalScene) (.com/vrScene) when you click to button it will navigate to (.com/vrScene) and opposite of that when you click button in vrScene it will load (normalScene). Maybe it sounds unproductive but it can be tried. What you think about this ?

**Comment by De-Panther** [comment]
You can now check if AR or VR is supported, and toggle them from WebXRManager
