### ISSUE TITLE
Allow start height / floor plane to come from VR device

### ISSUE THREAD

**Issue by HawkenKing** [De-Panther/unity-webxr-export#97]
On default scene / settings, the user is started at around 2 units / 2 meters, even when sitting down.

Tested on Oculus Quest.

**Comment by De-Panther** [comment]
Setting `VRRequiredReferenceSpace` and `ARRequiredReferenceSpace` to `local_floor` should do what you asked...
![image](https://user-images.githubusercontent.com/4749703/101522330-ba155980-398f-11eb-92f0-c651f068a8f3.png)

Make sure that the Cameras parent Transform is reset
![image](https://user-images.githubusercontent.com/4749703/101522584-1b3d2d00-3990-11eb-9839-a564818c96c0.png)

**Comment by HawkenKing** [comment]
I checked and I have the same set up as above. When starting a session the camera root or floor jumps up on Quest, the floor is set as the starting hmd height.

Might be related to this? https://forum.unity.com/threads/xr-floor-position-native-unity.675136/

Seems like a known issue, the fix in that thread is using obsolete code though, so it doesn't fix anything.

**Comment by De-Panther** [comment]
Your issue is in the Editor or in the Build?

**Comment by HawkenKing** [comment]
in the build when viewed in the browser

**Comment by De-Panther** [comment]
Does `Project Settings > XR Plug-in Management > WebGL > Plug-in Providers > WebXR Export` is checked?
![image](https://user-images.githubusercontent.com/4749703/101785052-f9b18200-3b04-11eb-86c1-abc774c56372.png)

**Comment by HawkenKing** [comment]
yes this is as above

**Comment by De-Panther** [comment]
Does updating to the latest packages solved your issue?

**Comment by De-Panther** [comment]
Closing the issue. If it still happens comment here and I'll re-open.
